### ISSUE TITLE
3.15.x doesn't build on FreeBSD cause of missing endian.h

### ISSUE THREAD

**Issue by dmilith** [protocolbuffers/protobuf#8373] opened 2021-03-04 09:53 UTC
**What version of protobuf and what language are you using?**
Version: 3.15.4
Language: C++

**What operating system (Linux, Windows, ...) and version?**
FreeBSD x86_64, v12.2

**What runtime / compiler are you using (e.g., python version or gcc version)**
clang 10.0.1

**What did you do?**
Either autotools build with ./configure && make or cd cmake && cmake ../ … && make

**What did you expect to see**
Properly built library

**What did you see instead?**

A lot of errors like this in multiple files, example:

```
src/google/protobuf/stubs/port.h:63:10: fatal error: 'endian.h' file not found
#include <endian.h>  // __BYTE_ORDER
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
No. It's a pretty standard environment.

**Comment by dmilith** [comment] 2021-03-05 07:54
This can be hacked by:

```
sed -i '' -e 's|endian.h|machine/endian.h|g' src/google/protobuf/*.cc src/google/protobuf/*.h src/google/protobuf/stubs/*.h src/google/protobuf/io/*.h
```

So it's just wrong include path on FreeBSD. After that hack project builds w/o issues.

**Comment by Mizux** [comment] 2021-03-05 12:38
Strange FreeBSD seems already supported...
https://github.com/protocolbuffers/protobuf/blob/87dd07b4367b7676af42105d0d102f4e536c248b/src/google/protobuf/stubs/port.h#L60-L66

FYI in google/or-tools we are using (and we test using github macos runner (ed provide virtualbox support), and a Vagrant FreeBSD box)
```cpp
#if (defined(__APPLE__) || defined(__FreeBSD__)) && defined(__GNUC__)
#include <machine/endian.h>
#elif !defined(_MSC_VER)
#include <endian.h>
#endif
```

**Comment by scddev** [comment] 2021-05-18 14:33
Same behavior also on AIX and SunOS:

```
-bash-4.4$ cmake -S cmake -B _build -Dprotobuf_BUILD_TESTS=OFF
-- 
-- 3.17.0.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/foo/protobuf-3.17.0/_build
-bash-4.4$ cmake --build _build
gmake[1]: Entering directory '/home/foo/protobuf-3.17.0/_build'
gmake[2]: Entering directory '/home/foo/protobuf-3.17.0/_build'
Scanning dependencies of target libprotobuf-lite
gmake[2]: Leaving directory '/home/foo/protobuf-3.17.0/_build'
gmake[2]: Entering directory '/home/foo/protobuf-3.17.0/_build'
[  0%] Building CXX object CMakeFiles/libprotobuf-lite.dir/home/foo/protobuf-3.17.0/src/google/protobuf/any_lite.cc.o
In file included from /home/foo/protobuf-3.17.0/src/google/protobuf/stubs/common.h:48:0,
                 from /home/foo/protobuf-3.17.0/src/google/protobuf/any.h:36,
                 from /home/foo/protobuf-3.17.0/src/google/protobuf/any_lite.cc:31:
/home/foo/protobuf-3.17.0/src/google/protobuf/stubs/port.h:65:37: fatal error: endian.h: No such file or directory
 #include <endian.h>  // __BYTE_ORDER
                                     ^
compilation terminated.
gmake[2]: *** [CMakeFiles/libprotobuf-lite.dir/build.make;63: CMakeFiles/libprotobuf-lite.dir/home/foo/protobuf-3.17.0/src/google/protobuf/any_lite.cc.o] Error 1
gmake[2]: Leaving directory '/home/foo/protobuf-3.17.0/_build'
gmake[1]: *** [CMakeFiles/Makefile2;73: CMakeFiles/libprotobuf-lite.dir/all] Error 2
gmake[1]: Leaving directory '/home/foo/protobuf-3.17.0/_build'
gmake: *** [Makefile;130: all] Error 2
-bash-4.4$ uname
AIX
```

**Comment by Mizux** [comment] 2021-05-19 08:02
@scdded do you have `machine/endian.h` or `sys/endian.h` on your system ?

**Comment by scddev** [comment] 2021-05-19 14:03
@Mizux endian.h does not exist on AIX (sys/machine.h) and SunOS (sys/isa_defs.h)

**Comment by gdharley** [comment] 2021-09-23 15:48
I can confirm the same error on AIX 7.1.
Is there a work around?

**Comment by scddev** [comment] 2021-09-23 18:05
@gdharley yes, this could be fixed by using sys/machine.h instead of endian.h.

You will end up with adding the following snippet to `src/google/protobuf/stubs/port.h` and `src/google/protobuf/io/coded_stream.h` before the else to include `endian.h`:

```
#elif defined(_AIX) || defined(__TOS_AIX__)
#include <sys/machine.h>  // BYTE_ORDER
```

**Comment by deannagarcia** [comment] 2022-07-21 23:36
Closing since it looks like the fix has been merged. If I'm missing anything feel free to reopen!

**Closed by deannagarcia** 2022-07-21 23:36 UTC
Labels: platform related
