### ISSUE TITLE
[Ruby] Message hashes including non-oneof values

### ISSUE THREAD

**Issue by blowmage** [protocolbuffers/protobuf#6167] opened 2019-05-22 22:30 UTC
**What language does this apply to?**

Ruby

**Describe the problem you are trying to solve.**

The Ruby Hash a Message object creates sometimes includes values for fields that are not applicable, specifically fields that are not set as part of the `oneof`.

**Describe the solution you'd like**

The Ruby Hash a Message object creates does not include any field that is set to the default value.

**Describe alternatives you've considered**

The Ruby Hash a Message object creates excludes values for `oneof` fields that are not set.

**Additional context**

The Ruby Hash produced by `Message#to_h` sometimes contain fields of a `oneof` that are not currently set, or were reset to their default value. Currently, if a `oneof` value is changed from one field to another, the previous field (with it's default value) will be in the hash along with the new field (and the set value). This makes it difficult to recreate the Message object from the hash. Ideally, the Message should be able to round-trip to/from a Ruby Hash just as it can round-trip to/from a binary proto stream and to/from JSON.

The `ruby/tests/basic_proto2.rb` file has the following test:

```ruby
def test_to_h
  m = TestMessage.new(:optional_bool => true, :optional_double => -10.100001, :optional_string => 'foo', :repeated_string => ['bar1', 'bar2'])
  expected_result = {
    :optional_bool=>true,
    :optional_double=>-10.100001,
    :optional_string=>"foo",
    :repeated_string=>["bar1", "bar2"],
  }
  assert_equal expected_result, m.to_h

  m = OneofMessage.new(:a => "foo")
  expected_result = {:a => "foo"}
  assert_equal expected_result, m.to_h
end
```

This test can be updated with the following code to demonstrate the problematic behavior:

```ruby
# oneof is not set
m = OneofMessage.new
assert_equal "", m.a
assert_equal 0, m.b
assert_nil m.my_oneof
expected_result = {}
assert_equal expected_result, m.to_h

# oneof is updated to a
m.a = "foo"
assert_equal "foo", m.a
assert_equal 0, m.b
assert_equal :a, m.my_oneof
expected_result = {:a => "foo"}
assert_equal expected_result, m.to_h

# oneof is updated to b
m.b = 42
assert_equal "", m.a
assert_equal 42, m.b
assert_equal :b, m.my_oneof
expected_result = {:b => 42}
assert_equal expected_result, m.to_h # actual is {:a=>"", :b=>42}

# create new message object, using incorrect hash
m = OneofMessage.new({:a=>"foo", :b=>0})
assert_equal :a, m.my_oneof # actual is :b
expected_result = {:a => "foo"}
assert_equal expected_result, m.to_h # actual is {:a=>"foo", :b=>0}
```

Additionally, I think it might be a good idea if the Ruby Hash objects simply omitted any field that was set to it's default value. I believe that would correct this issue and the Ruby Hash would be more concise.

**Comment by blowmage** [comment] 2019-11-11 18:28
Ping.

**Comment by bobbytables** [comment] 2020-03-10 17:48
We just hit this as well.

**Comment by haberman** [comment] 2021-02-15 08:42
I agree this should be fixed. My only concern at this point is backward compatibility. There could be code depending on all of the fields being set.

There are two cases I think:
1. For fields with presence (fields in `oneof` and `optional` fields), I think the correct behavior is clearly to emit them only if they are present.
2. For fields without presence (repeated fields and proto3 fields without `optional`), it's less clear to me what the right answer is. We could omit them when they are empty or 0, but that seems more likely to potentially cause breakage.

I suppose we can start by at least fixing (1).

**Comment by dorner** [comment] 2023-11-15 19:59
Specifically for the oneof case, we're being dinged by this because we're hitting a Go server. If you have (say) three possible `oneof` values, and you set the first one, Ruby will emit all three values (with the second and third being blank) and Go will read it in as blank. Essentially you can't use the Ruby types at all if you're talking to a Go server and you have a `oneof`.

**Comment by haberman** [comment] 2023-11-15 20:10
Wait, how does this affect interop with Go? The issue described in this bug only affects `Message#to_h`, which converts a message into a Ruby `Hash` (data structure). AFAIK it does not affect serialization to any wire format (JSON or binary).

**Comment by dorner** [comment] 2023-11-15 20:17
I can play around with it a bit more - we're using `gruf` to send the message and the message itself didn't work, only the hash did, and this bug stopped us from using it. (Sorry for the disjointed info - we were using the hash in one case for a while where there wasn't a \`oneof\`, and then got bitten by this when we tried it in a case where there was.) I'll collect a bit more info early next week.

**Comment by dorner** [comment] 2023-11-16 18:59
Yep. Looks like the issue is with `gruf` - it only supports a hash, not a request object for some reason. [https://github.com/bigcommerce/gruf/blob/main/lib/gruf/client.rb#L158](https://github.com/bigcommerce/gruf/blob/main/lib/gruf/client.rb#L158) So either `gruf` is changed to support the direct request objects, or this bug is fixed in order for us to continue :frowning:

**Comment by haberman** [comment] 2024-01-04 00:56
At long last, we are able to make a breaking change and fix this behavior: https://github.com/protocolbuffers/protobuf/pull/15234

One thing we never included in `to_h` output before is extensions. We should figure out what key extensions should use. Probably the most straightforward would be to use: `:"[pkg.ext]"`.

**Comment by haberman** [comment] 2024-01-04 17:45
> Ideally, the Message should be able to round-trip to/from a Ruby Hash just as it can round-trip to/from a binary proto stream and to/from JSON.

If we are trying to preserve this invariant, we need to take this into account when deciding how extensions should be represented.

Two options come to mind:

1. Use `:"[pkg.ext]"` as the key for an extension, and accept this when constructing a proto.
2. Use the extension's field descriptor as the key for the extension, and accept this when constructing a proto.

**Closed** 2024-01-04 18:02 UTC
Labels: ruby
