### ISSUE TITLE
Protobuf is broken with Bazel 6

### ISSUE THREAD

**Issue by sgowroji** [protocolbuffers/protobuf#12509] opened 2023-04-20 07:15 UTC
Error in building with Bazel 6.1.2. Could you please upgrade to the latest bazel version.

https://github.com/protocolbuffers/protobuf/blob/e5679c01e8f47e8a5e7172444676bda1c2ada875/.github/workflows/test_cpp.yml#L36

Protobuf: :ubuntu:[ 20.04 LTS (OpenJDK 11, gcc 9.4.0)](https://buildkite.com/bazel/protobuf/builds/4513#018796d9-8b74-4a12-a9f9-ea6a03a8196a), :darwin:[ (OpenJDK 11, Xcode)](https://buildkite.com/bazel/protobuf/builds/4513#018796d9-8b77-4568-b8eb-51541e538582)

CC :  Bazel team @meteorcloudy

**Comment by haberman** [comment] 2023-04-20 13:42
> Protobuf is broken by their own changes.

Could you include more details about what is broken? Are we talking about the Bazel 6.1.2 breakage shown above by @meteorcloudy , or is there something else also?

**Comment by meteorcloudy** [comment] 2023-04-20 13:50
@haberman I think it's a combination of both.
Bazel 6.1.2 + protobuf@a commit after https://github.com/protocolbuffers/protobuf/commit/5d3d9aa372de7a83f3916d8336c75d8a8653255e
Check the build history here: https://buildkite.com/bazel/protobuf/builds?branch=main

**Comment by meteorcloudy** [comment] 2023-04-20 14:37
@haberman BTW, what would be the minimal targets you would recommend we should specify in [protobuf.yml](https://github.com/bazelbuild/continuous-integration/blob/master/pipelines/protobuf.yml) to verify the basic functionalities of protobuf?

**Comment by haberman** [comment] 2023-04-20 14:38
Thanks for the clarifications. Based on what you wrote, it sounds like the title of this bug should be "Build is broken with Bazel 6." Would you agree?

The references to Bazel 4 seem unrelated. We have compatibility tests that exercise Bazel 4, but these are not causing the problem. The problem is just that we aren't compatible with Bazel 6 yet.

**Comment by meteorcloudy** [comment] 2023-04-20 14:42
Agree, /cc @sgowroji can you please update the issue title and description to summarize the issue accurately?

**Comment by haberman** [comment] 2023-04-20 15:29
> @haberman BTW, what would be the minimal targets you would recommend we should specify in [protobuf.yml](https://github.com/bazelbuild/continuous-integration/blob/master/pipelines/protobuf.yml) to verify the basic functionalities of protobuf?

I think it depends on what you count as "basic functionalities." For C++, I would recommend trying to build `:protoc`. But the repo has many languages in it (Java, Python, C#, Ruby, PHP, Objective-C, etc), so any of them could experience unique issues.

**Comment by fowles** [comment] 2023-04-20 15:59
The protobuf 23.0 release is already underway and we fully expect bazel 6 support to not be ready for it.  Once that is out the door, we can visit doing this at a reasonable pace.

**Comment by davido** [comment] 2023-04-23 07:27
@meteorcloudy I'm getting this failure first, when trying to build with bazel 6.1.2 on protobuf@HEAD (763d85293dba5b5f71ef393e70cc54279d75aae4)

```
  $ bazeldev build :protoc
ERROR: Traceback (most recent call last):
	File "/home/davido/projects/protobuf/WORKSPACE", line 65, column 20, in <toplevel>
		kotlin_repositories()
	File "/home/davido/.cache/bazel/_bazel_davido/79cbbbad7f51559e6c3ea804ad112d72/external/io_bazel_rules_kotlin/src/main/starlark/core/repositories/initialize.bzl", line 96, column 21, in kotlin_repositories
		rules_repository(
Error in repository_rule: invalid user-provided repo name '': valid names may contain only A-Z, a-z, 0-9, '-', '_', '.', and must start with a letter
ERROR: Error computing the main repository mapping: at /home/davido/.cache/bazel/_bazel_davido/79cbbbad7f51559e6c3ea804ad112d72/external/io_bazel_rules_kotlin/kotlin/core.bzl:2:5: at /home/davido/.cache/bazel/_bazel_davido/79cbbbad7f51559e6c3ea804ad112d72/external/io_bazel_rules_kotlin/kotlin/internal/opts.bzl:22:5: Encountered error while reading extension file 'jvm/opts.bzl': no such package '@io_bazel_rules_kotlin_configured//jvm': error loading package 'external': Could not load //external package
```

If I bump rule_kotlin to the recent release: v1.7.1 in:

```diff
diff --git a/protobuf_deps.bzl b/protobuf_deps.bzl
index 7e2caa330..c9a18b413 100644
--- a/protobuf_deps.bzl
+++ b/protobuf_deps.bzl
@@ -88,6 +88,6 @@ def protobuf_deps():
     if not native.existing_rule("io_bazel_rules_kotlin"):
         http_archive(
             name = "io_bazel_rules_kotlin",
-            urls = ["https://github.com/bazelbuild/rules_kotlin/releases/download/v1.5.0-beta-4/rules_kotlin_release.tgz"],
-            sha256 = "6cbd4e5768bdfae1598662e40272729ec9ece8b7bded8f0d2c81c8ff96dc139d",
+            urls = ["https://github.com/bazelbuild/rules_kotlin/releases/download/v1.7.1/rules_kotlin_release.tgz"],
+            sha256 = "fd92a98bd8a8f0e1cdcb490b93f5acef1f1727ed992571232d33de42395ca9b3",
         )
```

I am getting another failure:

```
  $ bazeldev build :protoc
ERROR: /home/davido/.cache/bazel/_bazel_davido/79cbbbad7f51559e6c3ea804ad112d72/external/bazel_tools/platforms/BUILD:89:6: in alias rule @bazel_tools//platforms:windows: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.
ERROR: /home/davido/.cache/bazel/_bazel_davido/79cbbbad7f51559e6c3ea804ad112d72/external/bazel_tools/platforms/BUILD:89:6: Analysis of target '@bazel_tools//platforms:windows' failed
ERROR: /home/davido/projects/protobuf/BUILD:513:10: While resolving toolchains for target //:protoc: invalid registered toolchain '@bazel_skylib//toolchains/unittest:cmd_toolchain': 
ERROR: Analysis of target '//:protoc' failed; build aborted: 
INFO: Elapsed time: 0.158s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

that is related to the `--incompatible_use_platforms_repo_for_constraints` option flip: in https://github.com/bazelbuild/bazel/issues/8622

Passing `--incompatible_use_platforms_repo_for_constraints=false` would fix that:

```
 $ bazeldev build --incompatible_use_platforms_repo_for_constraints=false :protoc
INFO: Build option --incompatible_use_platforms_repo_for_constraints has changed, discarding analysis cache.
INFO: Analyzed target //:protoc (7 packages loaded, 623 targets configured).
INFO: Found 1 target...
Target //:protoc up-to-date:
  bazel-bin/protoc
INFO: Elapsed time: 78.239s, Critical Path: 13.30s
INFO: 198 processes: 8 internal, 190 linux-sandbox.
INFO: Build completed successfully, 198 total actions
```

**Comment by meteorcloudy** [comment] 2023-04-24 09:41
> Error: <target @com_google_protobuf//java/core:lite> (rule '_osgi_jar') doesn't contain declared provider 'ProguardSpecProvider'

/cc @comius do you have any suggestion regarding this failure?

**Comment by meteorcloudy** [comment] 2023-05-08 13:25
Not sure what happened, protobuf is green with Bazel 6.1.2 at HEAD: https://buildkite.com/bazel/protobuf/builds/4533

**Comment by keith** [comment] 2023-08-28 23:33
sounds like we can close this one

**Closed** 2023-09-14 09:48 UTC
