### ISSUE TITLE
WriteFloat and WriteDouble  failed for Unity game on Android.

### ISSUE THREAD

**Issue by windyuuy** [protocolbuffers/protobuf#8476] opened 2021-04-12 01:23 UTC
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript

C#

**What operating system (Linux, Windows, ...) and version?**

Android 11 (HONOR PHONE PCT-AL10)

**What runtime / compiler are you using (e.g., python version or gcc version)**

Unity IL2CPP

**What did you do?**
1. When serializing struct, call WriteFloat failed, and cause crash.
2. When deserializing struct, call WriteDouble failed, and cause crash.

**What did you expect to see**

serializing or deserializing struct.

**What did you see instead?**

failed and cause crash.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by fowles** [comment] 2021-04-13 13:19
I have not actually looked into this, but can you test whether you are trying to write a NaN value?

**Comment by Agasper** [comment] 2021-05-14 15:22
It crashes Unity application on some devices when you're trying to read Single or Double value from message in /csharp/src/Google.Protobuf/ParsingPrimitives.cs in ParseDouble and ParseFloat method.
I assume it's due to unsafe pointer conversion *((float*)&tmpBuffer), so i workaround it by using 

  ```
[StructLayout(LayoutKind.Explicit)]
        struct UnionArray
        {
            [FieldOffset(0)]
            public byte[] _bytes;
            [FieldOffset(0)]
            public double[] _double;
        }
```

from https://stackoverflow.com/a/7832260

**Comment by jtattermusch** [comment] 2021-05-17 11:10
WriteFloat used  an unsafe method:
https://github.com/protocolbuffers/protobuf/blob/f0da89d8b6c53654327c43c5fa003276ef73d5fa/csharp/src/Google.Protobuf/WritingPrimitives.cs#L73,

but WriteDouble does not:
https://github.com/protocolbuffers/protobuf/blob/f0da89d8b6c53654327c43c5fa003276ef73d5fa/csharp/src/Google.Protobuf/WritingPrimitives.cs#L65

so I can understand that there might be an issue with WriteFloat, but WriteDouble really doesn't do anything special.


This is what parseFloat and parseDouble do:
https://github.com/protocolbuffers/protobuf/blob/f0da89d8b6c53654327c43c5fa003276ef73d5fa/csharp/src/Google.Protobuf/ParsingPrimitives.cs#L397
https://github.com/protocolbuffers/protobuf/blob/f0da89d8b6c53654327c43c5fa003276ef73d5fa/csharp/src/Google.Protobuf/ParsingPrimitives.cs#L381

**Comment by jtattermusch** [comment] 2021-05-17 11:12
CC @JamesNK

**Comment by Agasper** [comment] 2021-05-17 11:52
@jtattermusch you're right, ReadDouble & WriteDouble is safe but, BitConverter.Int64BitsToDouble & Unsafe.ReadUnaligned<double> is unsafe inside.
For me all the writes go well, but reads got crash on some devices (about 12% of users)

As it's IL2CPP stack trace it isn't helpful

```
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2021-05-13 18:08:06.370 1934-2162/? D/WifiWatchdogStateMachine: iwlanpercheck loss=2.25% / volume8 / imscallstate:0 sum:8.9, perAvg:2.97
2021-05-13 18:08:06.866 20287-20342/? E/CRASH: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2021-05-13 18:08:06.866 20287-20342/? E/CRASH: Version '2019.4.20f1 (6dd1c08eedfa)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'armeabi-v7a'
2021-05-13 18:08:06.866 20287-20342/? E/CRASH: Build fingerprint: 'lge/mh_global_com/mh:8.1.0/OPM1.171019.026/18236164615b9:user/release-keys'
2021-05-13 18:08:06.866 20287-20342/? E/CRASH: Revision: '0'
2021-05-13 18:08:06.866 20287-20342/? E/CRASH: ABI: 'arm'
2021-05-13 18:08:06.866 20287-20342/? E/CRASH: Timestamp: 2021-05-13 18:08:06+0800
2021-05-13 18:08:06.866 20287-20342/? E/CRASH: pid: 20287, tid: 20342, name: UnityMain  >>> ANDROID_PACKAGE_NAME <<<
2021-05-13 18:08:06.866 20287-20342/? E/CRASH: uid: 10427
2021-05-13 18:08:06.866 20287-20342/? E/CRASH: signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x68aef44e
2021-05-13 18:08:06.866 20287-20342/? E/CRASH:     r0  68aef44e  r1  66a2b8c0  r2  88015964  r3  8801da34
2021-05-13 18:08:06.866 20287-20342/? E/CRASH:     r4  88eb81ac  r5  68aef000  r6  00000446  r7  86abe834
2021-05-13 18:08:06.867 20287-20342/? E/CRASH:     r8  00000008  r9  7a68dd94  r10 76d98150  r11 8c3c9420
2021-05-13 18:08:06.867 20287-20342/? E/CRASH:     ip  00000000  sp  8c3c9400  lr  8689caf4  pc  88015964
2021-05-13 18:08:06.867 20287-20342/? E/CRASH: backtrace:
2021-05-13 18:08:06.867 20287-20342/? E/CRASH:       #00 pc 023a1964  /data/app/ANDROID_PACKAGE_NAME-7wxil_MdtwMmJRhgUOj34A==/lib/arm/libil2cpp.so (BuildId: c21ea249c3d208d447083a29690e7634bec9af3f)
2021-05-13 18:08:07.265 20287-20342/? E/CRASH: Tombstone written to: /storage/emulated/0/Android/data/ANDROID_PACKAGE_NAME/files/tombstone_00
    
    --------- beginning of crash
2021-05-13 18:08:07.266 20287-20342/? E/AndroidRuntime: FATAL EXCEPTION: UnityMain
    Process: ANDROID_PACKAGE_NAME, PID: 20287
    java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Version '2019.4.20f1 (6dd1c08eedfa)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'armeabi-v7a'
    Build fingerprint: 'lge/mh_global_com/mh:8.1.0/OPM1.171019.026/18236164615b9:user/release-keys'
    Revision: '0'
    ABI: 'arm'
    Timestamp: 2021-05-13 18:08:06+0800
    pid: 20287, tid: 20342, name: UnityMain  >>> ANDROID_PACKAGE_NAME <<<
    uid: 10427
    signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x68aef44e
        r0  68aef44e  r1  66a2b8c0  r2  88015964  r3  8801da34
        r4  88eb81ac  r5  68aef000  r6  00000446  r7  86abe834
        r8  00000008  r9  7a68dd94  r10 76d98150  r11 8c3c9420
        ip  00000000  sp  8c3c9400  lr  8689caf4  pc  88015964
    
    backtrace:
          #00 pc 023a1964  /data/app/ANDROID_PACKAGE_NAME-7wxil_MdtwMmJRhgUOj34A==/lib/arm/libil2cpp.so (BuildId: c21ea249c3d208d447083a29690e7634bec9af3f)
    
        at libil2cpp.0x23a1964(Native Method)
```

**Comment by jtattermusch** [comment] 2021-06-18 13:54
At this point it's not clear to me whether it's a Unity bug or a problem in Protobuf C# implementation. 
Based on what I saw, we could work around the problems, but it might come at a cost of decreased performance.

My concern is that if the problem is a Unity bug, I don't think it makes sense to sacrifice performance of correctly written code on all platforms just because Unity's .NET runtime (which is kind of special and quite different from other .NET runtimes) has a bug in it.

Is my understanding correct that the crashes only happen on real hardware (armeabi-v7a) with il2cpp (and it only happens on some devices)? Or do they also happen when deployed on an Android emulator?
Is there a simple repro?
It might be useful to check if this is perhaps fixed with newer versions of Unity? (what version did you use to reproduce?)

**Comment by jtattermusch** [comment] 2021-06-18 13:59
Btw, if [`BitConverter.Int64BitsToDouble()`](https://docs.microsoft.com/en-us/dotnet/api/system.bitconverter.int64bitstodouble?view=net-5.0) really can crash on Unity (as mentioned in https://github.com/protocolbuffers/protobuf/issues/8476#issuecomment-842261911), that's a pretty clear indication that this is caused by a bug in Unity, since Int64BitsToDouble is a standard library function (and even has by-value arguments and return value).

**Comment by Agasper** [comment] 2021-06-18 14:01
I'm sure it's Unity IL2CPP bug, and you're right there's no reason to fix anything. But i guess we need to mention this issue somewhere in the documentation with workaround.

> Is my understanding correct that the crashes only happen on real hardware (armeabi-v7a) with il2cpp (and it only happens on some devices)? Or do they also happen when deployed on an Android emulator?

They also happens on Bluestacks emulator

> Is there a simple repro?

Unfortunately, no

> It might be useful to check if this is perhaps fixed with newer versions of Unity? (what version did you use to reproduce?)

2019.4.20f1 LTS

**Comment by jtattermusch** [comment] 2021-06-18 14:05
@Agasper  do you know if the bug's tracked somewhere by Unity? (a link would be super useful)

**Comment by Agasper** [comment] 2021-06-18 14:08
As we discovered it, we fixed it. 
I just found this issue while googling how to resolve it, and just provide our workaround.
I didn't found any reports anywhere else

**Comment by jtattermusch** [comment] 2021-06-18 17:29
> As we discovered it, we fixed it.
> I just found this issue while googling how to resolve it, and just provide our workaround.
> I didn't found any reports anywhere else

Ok, do we at least know what is the first Unity version that has the fix?
Looks like we can close this issue now?

**Closed** 2021-06-20 17:16 UTC
Labels: c#

**Comment by FodderMK** [comment] 2021-07-28 18:27
I seem to have come across this issue as well.  Like op, it's only affecting a small number of our Android users.  This is on Unity 2020.2.1f1

```
Thread 0 (crashed)
  libil2cpp.so    0x00000000bc4c12fc WritingPrimitives_WriteFloat_mAAB132994393FC3251919DADF5F969483E8BFC10 (c:\Project\Library\Il2cppBuildCache\Android\armeabi-v7a\il2cppOutput\Google.Protobuf2.cpp:47506)
  libil2cpp.so    0x00000000bbf7d9b4 WorldModel_pbU3AU3AGoogle_Protobuf_IBufferMessage_InternalWriteTo_m7952048D0A5CBF09C17B725FFAEB8E3DF713F470 (c:\Project\Library\Il2cppBuildCache\Android\armeabi-v7a\il2cppOutput\Assembly-CSharp17.cpp:92828)
  libil2cpp.so    0x00000000bc0afab4 UniverseModel_pbU3AU3AGoogle_Protobuf_IBufferMessage_InternalWriteTo_mFBAF9ADAF1D821D1A66956CF3EAB65F586C36C4E (c:\Project\Library\Il2cppBuildCache\Android\armeabi-v7a\il2cppOutput\Assembly-CSharp15.cpp:44975)
  libil2cpp.so    0x00000000bc544ce4 CodedOutputStream_WriteRawMessage_m0AFAD4CD4BA6AEA5BDB215DCDD26CFAAC3837FEF (c:\Project\Library\Il2cppBuildCache\Android\armeabi-v7a\il2cppOutput\Google.Protobuf.cpp:120)
  libil2cpp.so    0x00000000bc67f9f4 MessageExtensions_ToByteArray_m64D1393AC2493B50D8E8CB7362AC0E302892C0E1 (c:\Project\Library\Il2cppBuildCache\Android\armeabi-v7a\il2cppOutput\Google.Protobuf1.cpp:109)
  libil2cpp.so    0x00000000bbfcc780 SaveService_WriteSave_m925082268DFE2A33936D8D551F691B6E00542195 (c:\Project\Library\Il2cppBuildCache\Android\armeabi-v7a\il2cppOutput\Assembly-CSharp12.cpp:100)
  libil2cpp.so    0x00000000bcb89f98 Action_Invoke_m3FFA5BE3D64F0FF8E1E1CB6F953913FADB5EB89E (c:\Project\Library\Il2cppBuildCache\Android\armeabi-v7a\il2cppOutput\mscorlib.cpp:0)
  libil2cpp.so    0x00000000bc6dd0ac SetupCoroutine_InvokeMoveNext_m036E6EE8C2A4D2DAA957D5702F1A3CA51313F2C7 (c:\Project\Library\Il2cppBuildCache\Android\armeabi-v7a\il2cppOutput\UnityEngine.CoreModule1.cpp:202)
  libil2cpp.so    0x00000000bbe9525c RuntimeInvoker_FalseVoid_t700C6383A2A510C2CF4DD86DABD5CA9FF70ADAC5_RuntimeObject_IntPtr_t(void (*)(), MethodInfo const*, void*, void**) (c:\Project\Library\Il2cppBuildCache\Android\armeabi-v7a\il2cppOutput\Il2CppInvokerTable.cpp:102048)
  libil2cpp.so    0x00000000bbdbfc04 il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) (C:\Program Files\Unity\Hub\Editor\2020.2.1f1\Editor\Data\il2cpp\libil2cpp\vm\Runtime.cpp:568)
  libunity.so     0x00000000be2aab05 scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool) 
  libunity.so     0x00000000be2b3c05 ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool) (ScriptingInvocation.cpp:273)
  libunity.so     0x00000000be2b9ee7 Coroutine::InvokeMoveNext(ScriptingExceptionPtr*) (ScriptingInvocation.h:69)
  libunity.so     0x00000000be2b9c2b Coroutine::Run(bool*) (Coroutine.cpp:271)
  libunity.so     0x00000000be18f7d7 DelayedCallManager::Update(int) (CallDelayed.cpp:185)
  libunity.so     0x00000000be214f19 ExecutePlayerLoop(NativePlayerLoopSystem*) 
  libunity.so     0x00000000be214f35 ExecutePlayerLoop(NativePlayerLoopSystem*) 
  libunity.so     0x00000000be2150d1 PlayerLoop() 
  libunity.so     0x00000000be2fc9bb UnityPlayerLoop() 
  libunity.so     0x00000000be30b58d nativeRender(_JNIEnv*, _jobject*) 
  base.odex       0x00000000c0fb8eeb <system symbols missing> 
```
@Agasper Would you be able to elaborate on what the workaround was?  I read the StackOverflow post but don't have enough of an understanding to apply it.

**Comment by Agasper** [comment] 2021-07-28 20:20
> @Agasper Would you be able to elaborate on what the workaround was? I read the StackOverflow post but don't have enough of an understanding to apply it.

Workaround allows you to get rid of unsafe pointer conversion ((float)&tmpBuffer) by using StructLayout hack

Check out example: https://github.com/Agasper/protobuf-warden-unity/blob/warden/csharp/src/Google.Protobuf/ParsingPrimitives.cs line 381

You can use my fork of protobuf https://github.com/Agasper/protobuf-warden-unity (branch "warden") as well.

**Comment by FodderMK** [comment] 2021-07-28 21:19
I will check it out, thank you for your help!

**Comment by Agasper** [comment] 2021-07-28 21:56
@FodderMK  If you have logs of crash and some free time please report it to Unity team

**Comment by Agasper** [comment] 2021-08-13 11:08
I was wrong, there is no issue with pointer conversion. I just found it crashed on `BinaryPrimitives.ReadUInt64LittleEndian` in 
`ParsingPrimitives.ParseRawLittleEndian64` and `ParsingPrimitives.ParseRawLittleEndian32` on some devices

I assume there's issue with `MemoryMarshal.Read`

**Comment by FodderMK** [comment] 2021-08-15 02:14
I haen't tested this yet, but Unity 2020.3.16 has this fix:  
https://issuetracker.unity3d.com/issues/android-il2cpp-data-misalignment-crash-in-deserializing-google-protobuf-message-field

**Comment by antonbystrov** [comment] 2021-10-02 11:55
> I haen't tested this yet, but Unity 2020.3.16 has this fix: https://issuetracker.unity3d.com/issues/android-il2cpp-data-misalignment-crash-in-deserializing-google-protobuf-message-field

@FodderMK Thanks! 
Upgrade 2020.3.13 project to 2020.3.16 fixed the problem. Checked on Android - works fine now!
