### ISSUE TITLE
Consistently use nullptr instead of NULL

### ISSUE THREAD

**Issue by maguro** [protocolbuffers/protobuf#4593] opened 2018-05-05 14:44 UTC
There are many places where `NULL` is used where `nullptr` can and should be used.  The pointer literal has been around for quite a while and is already in use in the code base.

**Comment by vamsibulusu** [comment] 2018-06-12 09:31
Hey, I am a beginner here and was wondering if changing every NULL assigned to a pointer variable to nullptr will solve the problem. If so, how can i go about doing so. Any help regarding the same is appreciated.

**Comment by acozzette** [comment] 2018-06-20 18:41
@vamsibulusu A good place to start would be in the `src/google/protobuf/stubs` directory. A simple search-and-replace of `NULL` for `nullptr` would probably work well. Other than the `stubs` directory I'm not sure if it would be a good idea to change everything at once, though--the problem is that within Google we have an internal version of the codebase that we sync back and forth with this repo on GitHub, and it might create a lot of merge conflicts. (Our internal version doesn't share the `stubs/` directory, so that part is fine.)

**Comment by batradhruv** [comment] 2018-08-06 15:15
Didnt see any PR for this. I went ahead and created one https://github.com/google/protobuf/pull/5010

**Comment by jorgbrown** [comment] 2022-09-01 18:38
Between PR #5010 and other changes, I believe we no longer use NULL anywhere.

**Closed by jorgbrown** 2022-09-01 18:38 UTC
Labels: c++, cleanup
