### ISSUE TITLE
Add symbols to nuget.org

### ISSUE THREAD

**Issue by PieterjanDeClippel** [protocolbuffers/protobuf#7844] opened 2020-08-25 13:24 UTC
**What language does this apply to?**
C#

**Describe the problem you are trying to solve.**
Debugging the source code

**Describe the solution you'd like**
Add the following two lines to the *.csproj file:

```
<IncludeSymbols>true</IncludeSymbols>
<SymbolPackageFormat>snupkg</SymbolPackageFormat>
```

Example: https://github.com/MintPlayer/MintPlayer.SeasonChecker/blob/master/MintPlayer.SeasonChecker/MintPlayer.SeasonChecker.csproj#L14

Next, you can upload the snupkg to nuget.org (github.com doesn't have a symbol server), so anyone can debug the source as well to see what happens inside the library.

**Comment by deannagarcia** [comment] 2022-07-26 21:50
Closing because this is a duplicate of https://github.com/protocolbuffers/protobuf/issues/6218. I'm looking into adding this and will update there.

**Closed by deannagarcia** 2022-07-26 21:50 UTC
Labels: c#
