### ISSUE TITLE
uint64 in PHP incorrectly truncated to PHP_INT_MAX

### ISSUE THREAD

**Issue by frenchfrywpepper** [protocolbuffers/protobuf#5216] opened 2018-10-02 19:41 UTC
**What version of protobuf and what language are you using?**
Version: v3.6.1
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
All

**What did you do?**
1. Set a value greater than [PHP_INT_MAX](http://php.net/manual/en/reserved.constants.php) and less than the max uint64 value into a uint64 field in proto message compiled to php.
2. Encode and decode the message and read the value.

**What did you expect to see**
The value should be encoded/decoded correctly.

**What did you see instead?**
The value is truncated to PHP_INT_MAX.

If I understand correctly, [PHP doesn't support unsigned integers](http://php.net/manual/en/language.types.integer.php) but according to the [proto language guide](https://developers.google.com/protocol-buffers/docs/proto3), proto decodes uint64 values into integers if the system is 64 bit. I think this will result in a loss of precision.

I couldn't find an issue or a documentation of this behavior (although I might have missed something). If this isn't resolvable, maybe it could be better documented.

**Anything else we should know about your project / environment**

`PHP_INT_SIZE == 8` in the environment (meaning it's a 64 bit system).

**Comment by fowles** [comment] 2022-07-01 21:15
Josh, is this still an issue?

**Comment by deannagarcia** [comment] 2022-09-01 18:08
Duplicate of https://github.com/protocolbuffers/protobuf/issues/10335, progress will be there so closing this.

**Closed by deannagarcia** 2022-09-01 18:08 UTC
Labels: bug, php, P2
