### ISSUE TITLE
'make check' fails ubuntu 18.04

### ISSUE THREAD

**Issue by ecmagalhaes** [protocolbuffers/protobuf#5816] opened 2019-03-04 12:42 UTC
During the 'make check' procedure I got this error mensage:
```
g++ -DHAVE_CONFIG_H -I. -I..    -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wextra
 -Werror -Wno-unused-parameter -Og -g -std=c++11 -DNDEBUG -MT google/protobuf/no_warning_test-map_unittest.pb.o -MD -MP -MF google/protobuf/.deps/no_warning_test-
map_unittest.pb.Tpo -c -o google/protobuf/no_warning_test-map_unittest.pb.o `test -f 'google/protobuf/map_unittest.pb.cc' || echo './'`google/protobuf/map_unittest.pb.cc
g++: internal compiler error: Killed (program cc1plus)
```
```
Makefile:4168: recipe for target 'google/protobuf/no_warning_test-map_unittest.pb.o' failed
make[2]: *** [google/protobuf/no_warning_test-map_unittest.pb.o] Error 4
make[2]: Leaving directory '/protobuf/src'
Makefile:7967: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/protobuf/src'
Makefile:1596: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```

**Comment by acozzette** [comment] 2019-03-04 22:21
@ecmagalhaes This looks like a compiler crash which would suggest a bug in GCC. Does this occur reproducibly on your machine or did it just happen once?

**Comment by ecmagalhaes** [comment] 2019-03-05 10:22
I'm compiling in several VMs.. but I just occur in two or tree (using ubuntu 18.04).
I assumed also that was a bug in GCC... because in all the other using ubuntu 16.04 it didn't occur.

**Comment by acozzette** [comment] 2019-03-05 17:22
OK, let me close the issue for now then. Let us know if it starts coming up reproducibly, though. I wonder if it could also be something like an OOM (out of memory)--it could be that GCC is bumping up against the memory limit assigned to your VMs.

**Closed by acozzette** 2019-03-05 17:22 UTC
Labels: c++
