### ISSUE TITLE
jruby: protobuf fields should be defined as methods

### ISSUE THREAD

**Issue by HoneyryderChuck** [protocolbuffers/protobuf#9202] opened 2021-11-08 15:29 UTC
**What version of protobuf and what language are you using?**
Version: 3.19.1
Language: Ruby (JRuby 9.3)

**What operating system (Linux, Windows, ...) and version?**

Darwin.

**What did you do?**

First, thanks a lot for reenabling jruby support 🙏 

I have code which checks whether a certain field exists.I use the idiomatic `.respond_to?` in CRuby. Things aren't working the same way in JRuby however.

**What did you expect to see**

I'd expect the check to work. To compare, here's how it works in CRuby (v3.0):

```ruby
# given a Google::Protobuf::Duration message
message.respond_to?(:seconds) #=> true
# although the method isn't defined
message.methods - Object.instance_methods #=>  [:to_f, :method_missing, :[], :[]=, :to_h, :to_json, :to_proto]
```

**What did you see instead?**

In Jruby, I don't get the same result for the `respond_to?` call, even if I can call `.seconds`. 

```ruby
message.respond_to?(:seconds) #=> false
message.seconds #=> 123
```

I suspect this happens because `.seconds` gets sent to `method_missing`, which then infers the value of the field; and the respective `.respond_to_missing?` method isn't defined, which makes my example break.

**Comment by JasonLunn** [comment] 2022-02-25 14:43
Thanks for filing this issue, @HoneyryderChuck. Investigating.

**Comment by JasonLunn** [comment] 2022-03-24 00:08
Progress update:

This turns out to be a known issue. There is already a test that covers this issue, and it is disabled on JRuby at the moment (and has been for over 5 years); see https://github.com/protocolbuffers/protobuf/blob/master/ruby/tests/basic.rb#L621

I've attempted to create a fix that would allow me to reenable the test for JRuby, but the issue with JRuby itself seems to still exist. Today I reduced the issue to a reproducible and repeatable failure care and opened https://github.com/protocolbuffers/protobuf/issues/9668 for JRuby.

**Comment by JasonLunn** [comment] 2022-03-24 00:09
Marking this issue `blocked` until https://github.com/protocolbuffers/protobuf/issues/9668 is resolved.

**Comment by JasonLunn** [comment] 2022-03-25 19:00
Workaround implemented in #9677

**Comment by JasonLunn** [comment] 2022-03-28 23:05
Fix merged.

**Closed by JasonLunn** 2022-03-28 23:05 UTC
Labels: bug, ruby, jruby

**Comment by HoneyryderChuck** [comment] 2022-03-29 06:10
Thank you!
