### ISSUE TITLE
C# AddressBook example and/or documentation not adequate to get started with version 3.5.1

### ISSUE THREAD

**Issue by dchennells** [protocolbuffers/protobuf#4119] opened 2017-12-31 22:22 UTC
Steps to repro:
1. Download current version 3.5.1 and open Google.Protobuf.sln in VS2017 v15.x (I used 15.4).
2. Set a breakpoint on line 52 of AddressBook Program.cs.
3. Rebuild all from within the IDE.
4. Run in the IDE (F5)

Results:
A. Builds okay.
B. After F5 run, a brief (<100 ms) screen flash appears of a console window opening and closing.
C. Nothing on the Debug output pane.
D. No errors.
E. Breakpoint not hit.

Expected result:
Hitting the breakpoint if set or alternatively have the console window appear and stay up.

Documentation consulted:
- The CSharp tutorial references the AddressBook project and says that the example is "complete" within the "csharp/src/AddressBook directory of the GitHub repository".
- The ReadMe.md file in the csharp root talks about building the Google.Protobuf.sln but does not refer to any known issues in running (debugging) with the default startup project of AddressBook and configured Startup object.
- The examples ReadMe at https://github.com/google/protobuf/tree/master/examples speaks about using Bazel, but the actual Build and Workspace files in the examples folder does not have a section pertaining to C#

I'm sure I'm missing something obvious.  Is running the csharp example in VS2017 a supported scenario?  I have not yet tried to create a replacement AddressBook2 project using alternative dependencies such as the full framework or NET Core 2.04.

Happy to pitch-in in getting the csharp example up and running or in improving the docs if someone can provide some initial guidance as to any known issues.

UPDATE - FURTHER OBSERVATIONS 1/2/2018:
1. I performed a clean re-installation of VS2017 to 15.5.2 to confirm that the problem persists with the latest version of the tooling.  AddressBook does not run, at least not in the IDE in debug mode.
2. I attempted to migrate the AddressBook project as provided in 3.5.1 to NETCore 2.0 but found that the path of least resistance is to use File-New in VS2017 to create a replacement project in a new solution and then migrate the other existing constituent projects.  Having done that, the AddressBook example runs okay targeting .NET Core 2.0.
3. Alternatively, I note that it is possible within the existing solution to create a full framework version of AddressBook that runs okay.

I would be happy to prepare a pull-request based on number 2 (above) to get the AddressBook project working and simultaneously migrate it to NETCore 2.0, a far more viable framework in any case.  I will be on holiday from mid-January, so please let me know sooner rather than later if this would be useful, (@jskeet).

**Comment by jskeet** [comment] 2018-01-02 14:31
I can't reproduce this, I'm afraid.

I've just downloaded the 3.5.1 zip file, opened the solution file in VS 15.5.1 and run the AddressBook sample and it came up with a prompt as expected.

What happens if you try to run the app from an open command line window instead?

Have you tried setting a break point at the very start of Main instead of on line 52?

**Comment by DavidChennells** [comment] 2018-01-02 18:34
Thanks for your immediate reply, @jskeet.  Your affirmation that it worked in your environment encouraged me to look closely at the tools.  Turns out that post .Net Core 2.0 releases of VS2017 require opting in to support the earlier versions of that framework, and under a somewhat misleadingly narrow label.  There is no backward compatibility support within the IDE by the .NET Core 2.0 bits.  (And perhaps the VS team wishes to turn the page on their 1.x alpha-like tooling support for .Net Core as quickly as possible.)

![vs2017 configuration](https://user-images.githubusercontent.com/19748766/34494347-1ea0e21c-efbe-11e7-8aef-58ccd53a5ea1.png)

It might be worth highlighting this in the ReadMe.md for the c# solution, where you say,

> "Although users of this project are only expected to have Visual Studio 2012 or later, developers of the library are required to have Visual Studio 2017 or later, as the library uses C# 6 features in its implementation, as well as the new Visual Studio 2017 csproj format."

For example, you could add the sentence:

> "In addition, in order to run and debug the AddressBook example in the IDE, you must install the optional component ".Net Core 1.0 - 1.1 development tools for Web" (as it's labelled in current versions of the VS2017 installer), above and beyond the main .NET Core cross-platform development feature."

Incidentally, my offer remains open to assist with the migration of the AddressBook project to .Net Core 2.x once the time comes.  I would also be interested in evaluating/testing the relevance of the new memory buffer-oriented C# 7.2 bits to the core code in the c# version of the Google.Protobuf itself.  Would it make sense to open that as a separate issue or is that ultra low priority at the moment?

**Comment by jskeet** [comment] 2018-01-02 18:42
Re: Span: there's already a feature request for it: #3431 

Your readme suggestion sounds good to me - if you could file a PR for that, it would be good.

"Migrating" the AddressBook project to .NET Core 2.x would be a single character change: in AddressBook.csproj, just change netcoreapp1.0 to netcoreapp2.0. I'd expect that to work with no other changes - from VS2017. However, I believe our CI systems etc are still using the 1.0 SDK. Updating to use the 2.0 SDK would require a non-trivial amount of work in my experience, as we'd still need to also install the 1.0 runtime in order to run 1.0-based tests.

**Comment by DavidChennells** [comment] 2018-01-04 09:55
Thanks for your support with that minor edit to the ReadMe @jskeet, which appears to be on its way.  I'll close this issue as soon as a change is completed.

On the one-character migration (!):  that seems like the reasonable expectation.  Hopefully the VS tools will support that path by the time it makes sense for protobuf to make the upgrade.

Regarding C# 7.2, I've followed up with a brief note on the feature request discussion you linked to see when (and whether) there would be value in moving forward with that.

**Comment by xfxyjwf** [comment] 2018-06-25 21:59
ok to close this issue now? The linked PR was merged.

**Closed** 2019-06-15 19:09 UTC
Labels: c#, documentation, enhancement
