### ISSUE TITLE
Protobuf 3.7.1 for PHP does not work with non-PECL version

### ISSUE THREAD

**Issue by phroggyy** [protocolbuffers/protobuf#5965] opened 2019-03-28 10:23 UTC
**What version of protobuf and what language are you using?**
Version: v3.7.1
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
Not relevant

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc version, 3.7.1

**What did you do?**
1. Write any protobuf structure and compile it to PHP with version 3.7.1
2. instantiate the PHP class in a repository that relies on `"google/protobuf": "3.7.1"` through composer/packagist.
3. Get a segfault.

**What did you expect to see**
No segmentation fault

**What did you see instead?**
Segmentation fault, caused by incorrect syntax.

**Anything else we should know about your project / environment**
This was first introduced in https://github.com/protocolbuffers/protobuf/commit/53a1d49633f1e4396c11d1fe593268793a118fc3. However, when that was added, the separate PHP code was not updated to accept the second argument: https://github.com/protocolbuffers/protobuf/blob/master/php/src/Google/Protobuf/Internal/DescriptorPool.php#L58-L78

**Comment by frickenate** [comment] 2019-04-17 15:18
I don't believe this is only "with non-PECL version" (as the title mentions). I segfault on PHP 7.3.4 with PECL 3.7.1 extension—whether or not the google/protobuf composer dependency is present. For now I'm forced to run without the C extension, using the php package only.

**Comment by TeBoring** [comment] 2019-05-09 02:39
@frickenate Please file another issue.

**Comment by dwsupplee** [comment] 2019-05-20 18:35
I am trying to reproduce this, but so far have not been able to. I generated a simple set of PHP classes using protoc v3.7.1 based off the following proto file:

```
syntax = "proto3";

message TestMessage {
	int32 a=1;
	int32 b=2;
}
```

I'm not seeing a segfault with or without the C extension, running the following:

```php
$message = new TestMessage([
    'a' => 15
]);

var_dump($message->getA()); // 15
```

@phroggyy if it isn't too much trouble, would you be able to share a few more details about how you're encountering this issue?

**Comment by phroggyy** [comment] 2019-05-21 17:01
@dwsupplee PHP 7.3, protobuf compiler 3.7.1, this proto file

```
syntax = "proto3";
option php_namespace = "Jobilla\\Proto\\Pipelines";
option php_metadata_namespace = "Jobilla\\Proto\\Metadata\\Pipelines";

message Job {
  int32 id = 1;
  string name = 2;
}
```

Generating the php class results in this code

```php
public static function initOnce() {
    $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

    if (static::$is_initialized == true) {
      return;
    }
    $pool->internalAddGeneratedFile(hex2bin(
        "..."
    ), true);

    static::$is_initialized = true;
}
```

Note the call to `internalAddGeneratedFile` with *2* arguments. The function, as declared by the php package, only accepts one argument. Normally, this shouldn't cause PHP to segfault, but if I remove the second argument, it works just fine.

**Comment by lhecker** [comment] 2019-05-21 17:09
@phroggyy Sorry to chime in here, but are you _absolutely_ certain you tested this with all non-standard extensions being disabled? I.e. ext-protobuf, xdebug, etc. are all disabled?
I‘ve personally never seen PHP segfault due to an incorrect syntax or invalid number of arguments…
If you’ve got an old version of the native ext-protobuf extension installed on the other hand I could easily imagine a segfault.

**Comment by dwsupplee** [comment] 2019-05-21 18:29
Thanks @phroggyy. I attempted to reproduce this on OSX with PHP v7.3.5 using the proto you provided and protoc installed from [here](https://github.com/protocolbuffers/protobuf/releases/tag/v3.7.1). I'm still not seeing a segfault, and echo @lhecker's thoughts.

**Comment by Conji** [comment] 2019-06-14 19:50
On OSX with PHP 7.1.23 and on CentOS, I'm seeing this issue. The codebase is importing definitions from our Python repo since the definitions are shared, throwing a segfault when `internalAddGeneratedFile` is called. Even with the most up-to-date packages on all sides, between `grpcio-tools`, `protobuf`, and `grpc`, it seems `DescriptorPool.php` isn't using 2 arguments. 

I did notice that a recent PR rewrote the function to use 2 arguments, but I'm not able to see the code reflected in my local packages.

Python:
`grpcio-tools`: 1.21.1
`grpcio`: 1.21.1

PHP:
`grpc/grpc`: 1.19.0
`google/proto-client`: 0.29.0
`google/protobuf`: 3.7.1

If anyone sees anything that makes you go "wtf", I'm by no means a PHP dev, so please point it out.

**Comment by TeBoring** [comment] 2019-11-18 16:40
I think it should have been fixed in master.

**Closed by TeBoring** 2019-11-18 16:40 UTC
Labels: php
