### ISSUE TITLE
C# .NET CustomOptions no longer has a way to test a descriptor for options

### ISSUE THREAD

**Issue by thesoftwarejedi** [protocolbuffers/protobuf#7240] opened 2020-02-21 20:05 UTC
Regarding the recent C# Custom Options

`CustomOptions` on Descriptors is now `Obsolete`.  The replacement `GetOption` throws an exception if the descriptor has no options.  Is there any way to test for this now?

The only workaround I can find is simply using the old way of doing a `TryGet`, which is an `Obsolete` way of doing it.  `CustomOptions` doesn't even provide a way to determine if it is 

```
//if I have to do this, I might as well just get the message when I check, but this is for example purposes
if (messageDescriptor?.CustomOptions.TryGetBytes(SomeExtensions.SomeOption.FieldNumber, out var nothing) ?? false)
{
    //this line will throw if the message has no `CustomOptions`
    SomeOption o = messageDescriptor?.GetOption<SomeOption>(SomeExtensions.SomeOption);
    return o;
}
return null;
```

I'm trying to test messages dynamically for options that they may not have.

CC: @ObsidianMinor

**Comment by ObsidianMinor** [comment] 2020-02-21 20:12
I have a PR open that adds null checks and discusses a "TryGetOption" API that doesn't return the default value here: #7130

**Comment by thesoftwarejedi** [comment] 2020-02-21 21:03
Perfect.  I left a comment there but that looks like exactly what I would want.  Thanks!

**Comment by jtattermusch** [comment] 2020-04-22 10:42
This is dupe of https://github.com/protocolbuffers/protobuf/issues/7127.

**Closed by jtattermusch** 2020-04-22 10:42 UTC
