### ISSUE TITLE
protoc: does not verify that json_name does not conflict

### ISSUE THREAD

**Issue by dsnet** [protocolbuffers/protobuf#5063] opened 2018-08-21 01:37 UTC
Using `protoc v3.6.1`.

Compile this file:
```proto 
syntax = "proto3";
message M {
	string f1 = 1 [json_name = "fooBar"];
	string f2 = 2 [json_name = "fooBar"];
}
```

What I see: compile succeeds.
What I expect: compilation failure since `fooBar` is specified twice.

**Comment by jhump** [comment] 2020-09-18 02:22
Is there appetite for reviewing and accepting a fix for this and for #7192, if I were to open a pull request?

**Comment by acozzette** [comment] 2020-09-18 18:33
@jhump Sure, I can review the pull request if you would like to work on it.

**Closed** 2022-09-22 16:24 UTC
Labels: bug, c++, json

**Comment by jhump** [comment] 2022-09-28 23:20
@mcy, @mkruskal-google, can this be reopened since the fix was reverted in #10657?

**Comment by mkruskal-google** [comment] 2022-09-28 23:52
I think you can roll both of these forward.  Part of the issue is that our full test suite wasn't even run over your initial PR.  The other part of the problem was that downstream code (both internal and external) was broken by it.  That's not necessarily a blocker, but it does mean we need to be more careful about merging it in

**Comment by jhump** [comment] 2022-10-03 17:22
@mkruskal-google, to make sure I understand your comment above: are you suggesting I open a new PR with this same fix, and that it simply needs to be merged more carefully next time (like running more tests and possibly requiring some internal changes before those tests all pass)?

**Comment by mkruskal-google** [comment] 2022-10-03 19:29
Yes exactly!  If you can get some information from [jaysachs](https://github.com/jaysachs) about why that one failed in kythe it would be helpful.  But part of the problem is that our tests weren't even fully run on your PRs, so it's likely they'll show some of the issues.  I can also manually port it into Google to check it internally
