### ISSUE TITLE
PHP version of protobuf has hardcoded total_byte_limit equal to 32MB

### ISSUE THREAD

**Issue by gakowalski** [protocolbuffers/protobuf#9990] opened 2022-05-18 09:17 UTC
Protobuf v3.x, PHP all versions, all systems and evironments.

There is a hardcoded limit which prevents reading ONNX files which are typically very large (hundreds of MBs):
https://github.com/protocolbuffers/protobuf/blob/07303d6f54e4768700925119a003493aacdb70ff/php/src/Google/Protobuf/Internal/CodedInputStream.php#L53

Raeching the limit starts chain of failures that finally throws Exception with misleading name and description:
> Fatal error: Uncaught Google\Protobuf\Internal\GPBDecodeException: Error occurred during parsing: Unexpected EOF inside bytes field.

For other languages this limit is not only much, much higher (like, 2GB for C++ instead of 32MB for PHP):
https://github.com/protocolbuffers/protobuf/blob/07303d6f54e4768700925119a003493aacdb70ff/src/google/protobuf/io/coded_stream.h#L623

...but also there are methods to change it programatically.:
https://github.com/protocolbuffers/protobuf/blob/07303d6f54e4768700925119a003493aacdb70ff/src/google/protobuf/io/coded_stream.h#L367-L384

Either add a method to raise the limit or increase the hardcoded value. And make some better exception message for this.

**Comment by gakowalski** [comment] 2022-05-18 10:02
My pull request with proposed setTotalBytesLimit() method (analogous to C++ one): https://github.com/protocolbuffers/protobuf/pull/9992

**Comment by elharo** [comment] 2022-05-18 10:58
Interesting that it's only 32 MB, though that is still much larger than protobufs were designed for. Data formats that are in the 100+ megabytes really shouldn't be using protobufs.

**Comment by deannagarcia** [comment] 2022-09-01 19:10
Duplicate of https://github.com/protocolbuffers/protobuf/issues/9521, follow along there for progress.

**Closed by deannagarcia** 2022-09-01 19:10 UTC
Labels: php
