### ISSUE TITLE
[python] Add type hints for generated classes

### ISSUE THREAD

**Issue by cbornet** [protocolbuffers/protobuf#2638] opened 2017-01-27 10:32 UTC
It would be great to generate type hints ([PEP484](https://www.python.org/dev/peps/pep-0484/)/[PEP526](https://www.python.org/dev/peps/pep-0526/)) for the python generated class so we have IDE completion and type incompatibility warnings.

Eg for :
```java
message Foo {
  string bar = 1;
}
```
generate
```python
@overload
class Foo:
  bar = None  # type: str

  def __init__(self, bar=None):  # type: (str) -> None
    pass

Foo = _reflection.GeneratedProtocolMessageType('Foo', (_message.Message,), dict(
```

Note: this way of writing types works with both python 2 and 3. With python >= 3.6, the Foo class could be documented more nicely.
The type annotations are well handled at least by pycharm.

**Comment by MelleDijkstra** [comment] 2018-02-04 12:02
This would be the best!

**Comment by liuyang007** [comment] 2018-02-27 10:07
+1

**Comment by selimyoussry** [comment] 2018-03-01 20:39
+1, check [mypy-protobuf](https://github.com/dropbox/mypy-protobuf) by Dropbox in the meantime

**Comment by AKuzmanoski** [comment] 2018-03-13 18:08
+1

**Comment by anandolee** [comment] 2019-05-22 22:52
As this future is not critical (not a bug or wrong behavior or relate to performance), protobuf team may not have time for it right now. If anyone is interested and willing to contribute on it, feel free to create a PR and assign to me for review.

Note: some field accept other types, for example bool field accept bool and numbers.Integral

**Comment by lexrj** [comment] 2019-06-07 02:24
In response to the note: Python's type hinting allows for nuanced typing to support the indicated case

**Comment by hanabi1224** [comment] 2019-10-14 19:57
+1

**Comment by robin-xl** [comment] 2019-10-17 01:43
+1

**Comment by henribru** [comment] 2019-10-18 15:17
The mypy-protobuf team is open to integration of their plugin: https://github.com/dropbox/mypy-protobuf/issues/95

Their plugin is written in Python though, so it couldn't integrate directly in the C++-based Python compiler plugin. Would a solution where the Python compiler plugin calls out to the mypy-protobuf plugin be a possibility? Perhaps with a C++ wrapper if calling it as a separate process isn't acceptable? Or would it have to be completely reimplemented in C++?

**Comment by danielgtaylor** [comment] 2019-10-31 04:53
First off, `mypy-protobuf` is great. Getting it integrated into the main project here would be awesome.

That said, if you are using a recent Python version (3.7+) and willing to try another plugin I've built https://github.com/danielgtaylor/python-betterproto which generates dataclasses with proper types among other improvements. For example, given this input:

```protobuf
syntax = "proto3";

package repeatedmessage;

message Test {
  repeated Sub greetings = 1;
}

message Sub {
  string greeting = 1;
}
```

You would get this generated output:

```python
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: repeatedmessage.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class Test(betterproto.Message):
    greetings: List["Sub"] = betterproto.message_field(1)


@dataclass
class Sub(betterproto.Message):
    greeting: str = betterproto.string_field(1)
```

This then provides proper type hints in your IDE:

<img width="573" alt="Screen Shot 2019-10-30 at 9 48 41 PM" src="https://user-images.githubusercontent.com/106826/67919817-24d64d80-fb5f-11e9-92b8-6a8434eac8da.png">

**Comment by hozn** [comment] 2020-04-22 17:50
@danielgtaylor, I think I cried a little bit when I saw this comment.  This is beautiful. The standard protoc python-generated code has been absolutely the worst thing about protobuf.  We currently end up with a marshalling system to turn these into plain python objects, which defeats many of the values of protobuf (e.g. single message description), but allows the messages and grpc methods to actually be usable with python typehinting, etc.  Anyway, I'll be adopting your work ASAP.  Thank you!

**Comment by cbows** [comment] 2020-05-25 11:26
@danielgtaylor, are you aware of [pydantic](https://pydantic-docs.helpmanual.io/). You could use pydantics BaseModel as a substitute of dataclasses and get some more benefits like runtime validation etc in addition type support in IDEs and so on.
pydantic even has it's own variant of dataclasses, which might also be interesting here.

**Comment by nipunn1313** [comment] 2020-11-23 01:58
Hey friends! Maintainer of dropbox/mypy-protobuf here! As mentioned earlier by @henribru - we're happy to move toward integrating mypy-protobuf into a feature of protobuf in python.

Not actively looking into it, but if someone wants to take a crack at it, I imagine it would look something like this.

- Start by adding a dependency on mypy-protobuf
- Add a --mypy-out default implementation - using mypy-protobuf's codegen.py
- Add documentation around this - perhaps marking it as unstable feature until maintainers choose to stabilize

If this takes hold successfully, then eventually, we can look into moving the mypy-protobuf repository under `protocolbuffers` project on github

Also, perhaps eventually, we could integrate entirely - using https://www.python.org/dev/peps/pep-0561/ - to do the mypy typing inline. This would unlock benefits - like better base types on enum values - with the NewType available in the *_pb2.py itself (ugh - https://github.com/dropbox/mypy-protobuf/blob/master/generated/testproto/test3_pb2.pyi.expected#L45). However, it seems like a larger project.

Happy to do reviews on the mypy-protobuf side - if there are changes required there

Also - big shoutout to @danielgtaylor's solution `python-betterproto` - which looks amazing as well - if you're willing to use totally different generated output.

**Comment by rfan-debug** [comment] 2021-04-07 20:19
+1

**Comment by caowenbin08** [comment] 2021-04-12 07:56
+1

**Comment by mingwugmail** [comment] 2021-05-19 23:18
Has this been done? is python/typeshed#4785 above solved the problem?

Or do we have an ETA when this will be done?

So using dropbox/mypy-protobuf still the best thing to do as of today?

**Comment by nipunn1313** [comment] 2021-06-10 03:01
> Has this been done? is [python/typeshed#4785](https://github.com/python/typeshed/pull/4785) above solved the problem?

This adds stubs for only the `_pb2.py` generated from the corresponding `.proto` files that ship with protobuf

> Or do we have an ETA when this will be done?

Nobody is working on it from my side. AFAICT nobody is working on it from protobuf side either. You're welcome to take a crack at it.

> So using dropbox/mypy-protobuf still the best thing to do as of today?

As maintainer/author of mypy-protobuf - I'm a biased party, but personally I think it's pretty good!

**Comment by intenvy** [comment] 2022-01-11 19:21
+1

**Comment by haberman** [comment] 2022-02-10 04:06
We have open-sourced our `.pyi` generator here: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/python/python_pyi_generator.cc

It is not yet present in a release, but you can start playing with it now. Please let us know if you have feedback.

If you build `protoc` from master, you can use `--pyi_out=<DIR>` to generate `.pyi` files for the generated code.

**Comment by danieleades** [comment] 2022-02-10 15:19
> We have open-sourced our `.pyi` generator here: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/python/python_pyi_generator.cc
> 
> It is not yet present in a release, but you can start playing with it now. Please let us know if you have feedback.
> 
> If you build `protoc` from master, you can use `--pyi_out=<DIR>` to generate `.pyi` files for the generated code.

just tested this out. works a treat. any idea when that'll be released?

**Comment by haberman** [comment] 2022-02-10 17:54
> just tested this out. works a treat. any idea when that'll be released?

Glad it works for you! It should be released by March, or April at the latest.

**Comment by haberman** [comment] 2022-02-10 23:54
Anything for gRPC would be released through the gRPC project. I don't know about their plans.

**Comment by artificial-aidan** [comment] 2022-02-10 23:55
That's what I assumed. Thanks

**Comment by loterchang** [comment] 2022-02-25 07:39
> We have open-sourced our `.pyi` generator here: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/python/python_pyi_generator.cc
> 
> It is not yet present in a release, but you can start playing with it now. Please let us know if you have feedback.
> 
> If you build `protoc` from master, you can use `--pyi_out=<DIR>` to generate `.pyi` files for the generated code.

@haberman Thank you so much for the information about `.pyi generator`. I've tested and it works great!

One feedback on this: The support for enum - 
Seems like the autocomplete still doesn't work well for enum case (for example on VS code).

For example a enum like
```
enum FruitType {
   APPLE = 0;
   BANANA = 1;
   ORANGE = 2;
}
```
autocomplete doesn't work when using `FruitType.` ...

Any thoughts or solutions to make it work? Thanks a lot!

**Comment by furkan-guvenc** [comment] 2022-04-16 14:02
> We have open-sourced our `.pyi` generator here: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/python/python_pyi_generator.cc
> 
> It is not yet present in a release, but you can start playing with it now. Please let us know if you have feedback.
> 
> If you build `protoc` from master, you can use `--pyi_out=<DIR>` to generate `.pyi` files for the generated code.

Link is gone

**Comment by miselico** [comment] 2022-04-22 17:39
It seems the `--pyi_out=` option is now available on 3.20.0 and works nicely.

**Comment by perezd** [comment] 2022-04-22 18:02
Sounds good, please feel free to open additional issues.

**Closed by perezd** 2022-04-22 18:02 UTC
Labels: enhancement, python, P3

**Comment by eggachecat** [comment] 2022-05-21 11:31
Hi guys, a question from newbee: Hasn't the tool been included into `grpc_tools`? Besides my latest install grpc __verison__ is '1.46.3' why is the version number so different from the '3.20.0 ' mentioned above?

**Comment by troyswanson** [comment] 2022-09-21 21:54
@eggachecat As of this writing, the `grpcio-tools` _Python package_ is at `1.48.1`. However, it seems like the `protoc` binary that comes with it is still at `3.19.4`. The following is using a fresh Docker container from the `python:3-alpine` image:

```
/ # pip install -q grpcio-tools

/ # pip show grpcio-tools
Name: grpcio-tools
Version: 1.48.1
Summary: Protobuf code generator for gRPC
Home-page: https://grpc.io
Author: The gRPC Authors
Author-email: grpc-io@googlegroups.com
License: Apache License 2.0
Location: /usr/local/lib/python3.10/site-packages
Requires: grpcio, protobuf, setuptools
Required-by: 

/ # python -m grpc_tools.protoc --version
libprotoc 3.19.4
```

When can we expect the grpcio-tools package to be bumped to >=3.20?

**Comment by troyswanson** [comment] 2022-09-21 22:04
> We have open-sourced our `.pyi` generator here: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/python/python_pyi_generator.cc

I believe a new link for this file is here:
https://github.com/protocolbuffers/protobuf/blob/2dcd3e4a01b9ab83eab79b6df2ca39e4cf64c15e/src/google/protobuf/compiler/python/pyi_generator.cc

**Comment by mahyarmirrashed** [comment] 2023-01-25 01:51
> > We have open-sourced our `.pyi` generator here: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/python/python_pyi_generator.cc
> > It is not yet present in a release, but you can start playing with it now. Please let us know if you have feedback.
> > If you build `protoc` from master, you can use `--pyi_out=<DIR>` to generate `.pyi` files for the generated code.
> 
> @haberman Thank you so much for the information about `.pyi generator`. I've tested and it works great!
> 
> One feedback on this: The support for enum - Seems like the autocomplete still doesn't work well for enum case (for example on VS code).
> 
> For example a enum like
> 
> ```
> enum FruitType {
>    APPLE = 0;
>    BANANA = 1;
>    ORANGE = 2;
> }
> ```
> 
> autocomplete doesn't work when using `FruitType.` ...
> 
> Any thoughts or solutions to make it work? Thanks a lot!

I have this same issue.

**Comment by loterchang** [comment] 2023-01-25 05:14
> > > We have open-sourced our `.pyi` generator here: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/python/python_pyi_generator.cc
> > > It is not yet present in a release, but you can start playing with it now. Please let us know if you have feedback.
> > > If you build `protoc` from master, you can use `--pyi_out=<DIR>` to generate `.pyi` files for the generated code.
> > 
> > 
> > @haberman Thank you so much for the information about `.pyi generator`. I've tested and it works great!
> > One feedback on this: The support for enum - Seems like the autocomplete still doesn't work well for enum case (for example on VS code).
> > For example a enum like
> > ```
> > enum FruitType {
> >    APPLE = 0;
> >    BANANA = 1;
> >    ORANGE = 2;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > autocomplete doesn't work when using `FruitType.` ...
> > Any thoughts or solutions to make it work? Thanks a lot!
> 
> I have this same issue. Looking at the generated Python interface file, it just seems as if it is not generated.

@mahyarmirrashed The generated enum values are under the file. If you have the generated proto file as `items_py_pb2`, the enum value can be accessed by `items_py_pb2.APPLE` instead of `items_py_pb2.FruitType.APPLE`.

**Comment by mahyarmirrashed** [comment] 2023-01-25 06:17
@loterchang  Thank you, you are right. I guess they should probably update their documentation on the website.
