### ISSUE TITLE
Add ability to get FileDescriptorSet serialization in C#

### ISSUE THREAD

**Issue by mcon-gr** [protocolbuffers/protobuf#5441] opened 2018-12-10 09:42 UTC
**What language does this apply to?**
This issue relates to the C# `Google.Protobuf` package.

**Describe the problem you are trying to solve.**
Currently there is no way to obtain a `ByteString` from generated code, which represents either a message/proto-file with its dependencies which can be used with `protoc`. The appropriate data structure for this is `FileDescriptorSet`.

In particular I'd like to be able to generate protobuf code for another language given the generated C# protobuf code. We can already get an `IList<FileDescriptor>` of dependencies through the `Dependencies` property on `FileDescriptor`, all that needs to be done is bundling that with the instance of the `FileDescrpitor` and putting that into a `FileDescriptorSet` data structure and serializing.

**Describe the solution you'd like**
I'd like to add facility to get the serialized representation of `FileDescriptorSet`, containing all dependencies from either a `FileDescriptor` or a `MessageDescriptor`. This is code I'd be happy to write/test myself.

**Describe alternatives you've considered**
Ultimately the 2 formats for specifying protobuf messages are:
- .proto files
- `FileDescriptorSet`s
Given the necessary information is already stored in generated code to obtain the `FileDescriptorSet`, and this mechanism allows for easy bundling of dependencies, that seemed like the best way forward.

**Additional context**
The reason I'm looking to generate code for other languages, given the generated code for one (in this case C#), is to facilitate adding Protobuf support to the Pact contract testing framework. I can provide additional context if required.

**Comment by acozzette** [comment] 2018-12-10 21:43
You can call `protoc` and pass `--descriptor_set_out` to have it write the `FileDescriptorSet` out to a file. Does that help with what you're trying to do?

**Comment by mcon-gr** [comment] 2018-12-10 22:15
Hi @acozzette, sure so I completely get that if I have the appropriate `.proto` files, then I'm able to get the `FileDescriptorSet`, however that's something I need to be able to do from the generated files.
Java and other languages implement the `SelfDescribingMessage` which includes the `FileDescriptorSet`, so there's precedent for adding functionality of this kind.

The reason that doing things from the `.proto` is not sufficient is that I'm trying to add functionality to the Pact testing framework: we're trying to test against the functionality of the application, as opposed to the `.proto`, which in general may live in another repository to the application.

**Comment by nagytech** [comment] 2019-10-25 06:13
@mcon-gr 

If I understand your issue correctly, it should be resolved by 69cb61c61 which exists now in master.  However, this change does not appear to have been applied to any release.  I'm in the middle of creating a PR to help get this into 3.10.x and will link it when done.

**Comment by ObsidianMinor** [comment] 2019-10-25 06:38
> this change does not appear to have been applied to any release

That's because it's meant to go with the rest of the changes from #5936 in the 3.11 release which should be in the next month if [this comment](https://github.com/protocolbuffers/protobuf/pull/5936#issuecomment-528976253) is still accurate. So I'd just wait a little bit.

**Comment by nagytech** [comment] 2019-10-25 07:45
I didn’t notice the 3.11 plan at all.  Thanks for the explanation.

**Comment by jtattermusch** [comment] 2019-11-04 12:15
@nagytech   it this a regression with respect to some of the older releases (= e.g. something we broke in the last release) or this never worked, so you're basically filing a feature request?

**Comment by nagytech** [comment] 2019-11-04 22:33
@jtattermusch 

I'm not the author of this issue.  However, from what I can tell they are requesting a new feature.

However, I would argue that it's some level of debt to the C# implementation of Protobuf given that these same fields are not internal to the other frameworks.

**Comment by elharo** [comment] 2021-09-20 12:51
resolved

**Closed by elharo** 2021-09-20 12:51 UTC
Labels: c#
