### ISSUE TITLE
[msvc]Protobuf 22.3 build fail on tests with many errors like C2794, C2938, C2955

### ISSUE THREAD

**Issue by wtof1996** [protocolbuffers/protobuf#12538] opened 2023-04-24 06:48 UTC
**What version of protobuf and what language are you using?**
Version: 22.3
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 10 22H2 19045.2846
**What runtime / compiler are you using (e.g., python version or gcc version)**
Visual Studio 2022 17.5.4 with msvc 19.35.32217.1 and  cmake 3.25.1-msvc1
**What did you do?**

1.  git clone -b v22.3 https://github.com/protocolbuffers/protobuf.git
2.  cd protobuf
3.  git submodule update --init --recursive
4.  mkdir cmake_build
5. Open x64 Native Tools Command Prompt for VS2022, then cd to the directory created in step 4
6. cmake -G "Visual Studio 17 2022" -DCMAKE_INSTALL_PREFIX="E:\Lib\protobuf-22.3\install" -Dprotobuf_WITH_ZLIB=ON  -DZLIB_ROOT="E:\Lib\zlib-1.2.13" -Dprotobuf_BUILD_TESTS=ON -DCMAKE_CXX_STANDARD=17  -DABSL_PROPAGATE_CXX_
STD=ON -DCMAKE_POLICY_DEFAULT_CMP0074=NEW -DCMAKE_POLICY_DEFAULT_CMP0067=NEW  -Dprotobuf_MSVC_STATIC_RUNTIME=OFF  ..

Note: Here, I must set CMP0067 to NEW because if not, the abseil test ABSL_INTERNAL_AT_LEAST_CXX17 will fail even when I set CMAKE_CXX_STANDARD to 17.

7.  Open the protobuf.sln generated in step 6, then rebuild the ALL_BUILD project

**What did you expect to see**
Build success with no errors
**What did you see instead?**
All projects build successfully except "tests", and I get errors:

> 72>E:\Lib\protobuf-22.3\protobuf\third_party\abseil-cpp\absl/meta/type_traits.h(683,66): error C2794: 'type': is not a member of any direct or indirect base class of 'absl::lts_20230125::type_traits_internal::result_of<const Compare (const Key &,const Key &)>'
72>E:\Lib\protobuf-22.3\protobuf\third_party\abseil-cpp\absl/container/internal/btree.h(90,26): error C2938: 'absl::lts_20230125::result_of_t' : Failed to specialize alias template (compiling source file E:\Lib\protobuf-22.3\protobuf\src\google\protobuf\map_test.cc)
72>E:\Lib\protobuf-22.3\protobuf\third_party\abseil-cpp\absl/container/internal/btree.h(335,51): error C2955: 'std::is_same': use of class template requires template argument list (compiling source file E:\Lib\protobuf-22.3\protobuf\src\google\protobuf\map_test.cc)
72>E:\Lib\protobuf-22.3\protobuf\third_party\abseil-cpp\absl/container/internal/btree.h(335,51): error C2039: 'value': is not a member of 'std::is_same<_Ty1,_Ty2>' (compiling source file E:\Lib\protobuf-22.3\protobuf\src\google\protobuf\map_test.cc)
72>E:\Lib\protobuf-22.3\protobuf\third_party\abseil-cpp\absl/container/internal/btree.h(335,1): error C2065: 'value': undeclared identifier (compiling source file E:\Lib\protobuf-22.3\protobuf\src\google\protobuf\map_test.cc)
72>E:\Lib\protobuf-22.3\protobuf\third_party\abseil-cpp\absl/container/internal/btree.h(336,73): error C2955: 'std::is_convertible': use of class template requires template argument list (compiling source file E:\Lib\protobuf-22.3\protobuf\src\google\protobuf\map_test.cc)
72>E:\Lib\protobuf-22.3\protobuf\third_party\abseil-cpp\absl/container/internal/btree.h(336,73): error C2039: 'value': is not a member of 'std::is_convertible<_From,_To>' (compiling source file E:\Lib\protobuf-22.3\protobuf\src\google\protobuf\map_test.cc)
72>E:\Lib\protobuf-22.3\protobuf\third_party\abseil-cpp\absl/container/internal/btree.h(336,1): error C2065: 'value': undeclared identifier (compiling source file E:\Lib\protobuf-22.3\protobuf\src\google\protobuf\map_test.cc)
72>E:\Lib\protobuf-22.3\protobuf\third_party\abseil-cpp\absl/container/internal/btree.h(372,27): error C2975: 'B': invalid template argument for 'absl::lts_20230125::conditional_t', expected compile-time constant expression (compiling source file E:\Lib\protobuf-22.3\protobuf\src\google\protobuf\map_test.cc)
72>E:\Lib\protobuf-22.3\protobuf\third_party\abseil-cpp\absl/meta/type_traits.h(683,66): error C2794: 'type': is not a member of any direct or indirect base class of 'absl::lts_20230125::type_traits_internal::result_of<const absl::lts_20230125::container_internal::key_compare_adapter<Compare,Key>::checked_compare (const Key &,const Key &)>'
72>    4 Warning(s)
72>    10 Error(s)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
The cmake output in step 6:
[cmake_output.txt](https://github.com/protocolbuffers/protobuf/files/11307381/cmake_output.txt)
The "tests" project build output:
[tests.log](https://github.com/protocolbuffers/protobuf/files/11307474/tests.log)

**Anything else we should know about your project / environment**
This error seems similar to issue #12289.
However, I'm specifying C++17, and I checked the compiler settings, the /std:c++17 switch is used.

**Comment by mkruskal-google** [comment] 2023-04-24 17:33
Duplicate of #12289, which also appears to be C++17.  Will follow up on that thread

**Closed by mkruskal-google** 2023-04-24 17:33 UTC
Labels: c++, cmake, untriaged, 22.x
