### ISSUE TITLE
Unhelpful error message - PHP

### ISSUE THREAD

**Issue by tbillington** [protocolbuffers/protobuf#2742] opened 2017-02-21 04:10 UTC
When giving a value of the wrong type to a protobuf message php gives the following error

```
PHP Fatal error:  Expect repeated field. in /Users/trent/src/github.com/myproject/phptest/vendor/google/protobuf/php/src/Google/Protobuf/Internal/GPBUtil.php on line 137
```

This doesn't give me any information about where the error occurred in my code.

**Comment by TeBoring** [comment] 2017-02-21 05:28
Isn't there a stack trace?

**Comment by tbillington** [comment] 2017-02-21 05:44
Nope, that's part of the issue. I make an exception at the error site in `Google\Protobuf\Internal\GPBUtil` and print the trace so I can debug the issue, but I don't get any more info by default other than what I posted initially.

Maybe for this issue it could print something like `expected array of type X, got element of type Y` ?

**Comment by TeBoring** [comment] 2017-02-21 05:46
Will add more info in future release.

**Comment by lord2800** [comment] 2019-10-31 23:09
Any update on this? It's still frustrating.

**Comment by deannagarcia** [comment] 2022-09-01 17:37
I'm going to close this bug since it's so old. If you are still having this issue with new versions of protobuf, please reopen with reproduction instructions.

**Closed by deannagarcia** 2022-09-01 17:37 UTC
Labels: enhancement, php, P3
