### ISSUE TITLE
Inconsistent defaulting to `python` implementation, and errors when using `cpp`

### ISSUE THREAD

**Issue by BenRKarl** [protocolbuffers/protobuf#9180] opened 2021-11-02 19:51 UTC
**What version of protobuf and what language are you using?**
Versions: `3.17.3`, `3.18.0`, `3.18.1`, and `3.19.0`

Language: Python (versions `3.7.2`, `3.8.6`, `3.9.0`, and `3.10.0`

**What operating system (Linux, Windows, ...) and version?** gLinux

**What runtime / compiler are you using (e.g., python version or gcc version)** python and/or cpp

**What did you do?**

Run this bash script. Note that it require `pyenv` to be installed, along with Python versions `3.7.2`.

```
#!/bin/bash
 
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
pyenv global 3.7.2
python -mvenv /tmp/venv
. /tmp/venv/bin/activate
python -m pip install protobuf==3.19.0
python -c "from google.protobuf import descriptor_pb2"
```

**What did you expect to see**

I expect this script to run without error.

**What did you see instead?**

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/venv/lib/python3.7/site-packages/google/protobuf/descriptor_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/tmp/venv/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: cannot import name '_message' from 'google.protobuf.pyext' (/tmp/venv/lib/python3.7/site-packages/google/protobuf/pyext/__init__.py)
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

This was first detected as a performance issue, as our benchmarks began showing large regressions due to the library unknowingly running the `python` implementation. For more context on the history see [this Issue](https://github.com/protocolbuffers/protobuf/issues/9014).

**Anything else we should know about your project / environment**

There are issues with a number of combinations of Python versions and `protobuf` library versions. Here are the combinations I found that have problems when running the above reproduction script:

Python version | Protobuf version | Env var status | Result
-- | -- | -- | --
3.7.2 | 3.19.0 | unset | defaults to `python` implementation incorrectly
3.7.2 | 3.19.0 | `cpp` | results in above error
3.7.2 | 3.18.1 | unset | defaults to `python` implementation incorrectly
3.10.0 | 3.18.1 | unset | defaults to `python` implementation incorrectly
3.7.2 | 3.18.1 | `cpp` | results in above error
3.10.0 | 3.18.1 | `cpp` | results in above error
3.7.2 | 3.18.0 | unset | defaults to `python` implementation incorrectly
3.10.0 | 3.18.0 | unset | defaults to `python` implementation incorrectly
3.7.2 | 3.18.0 | `cpp` | results in above error
3.10.0 | 3.18.0 | `cpp` | results in above error
3.10.0 | 3.17.3 | unset | defaults to `python` implementation incorrectly
3.10.0 | 3.17.3 | `cpp` | results in above error

**Comment by acozzette** [comment] 2021-11-02 20:25
I ran into a variation of this error recently and managed to fix it by adding the flag `--install-option="--cpp_implementation"` to `pip install`. I'm not very knowledgeable about Python and have no idea if this is a good fix, but maybe this workaround will help.

**Comment by BenRKarl** [comment] 2021-11-08 18:09
@efroemling I assume you intend to use the `python` implementation, right? The lack of `.so` files would make using the `cpp` implementation impossible I believe.

**Comment by haberman** [comment] 2021-11-10 03:02
I was able to reproduce this, thanks.

I think the root cause here is that 3.18.0 moved us from "manylinux1" to "manylinux2014" as our platform tag. Earlier versions of Python appear to still require older platform tags such as manylinux1.

This change was caused by https://github.com/protocolbuffers/protobuf/pull/8280 (cc @jtattermusch)

I think perhaps the solution here is to revert to manylinux1 for x86-64 and only use manylinux2014 for aarch64.

More detail follows:

---

For Python 3.7.2 with Protobuf 3.17.1, it is installing the wheel `protobuf-3.17.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl`:

```
$ python -m pip install protobuf==3.17.3
Collecting protobuf==3.17.3
  Downloading https://files.pythonhosted.org/packages/4c/53/ddcef00219f2a3c863b24288e24a20c3070bd086a1e77706f22994a7f6db/protobuf-3.17.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0MB)
    100% |████████████████████████████████| 1.0MB 25.4MB/s 
Collecting six>=1.9 (from protobuf==3.17.3)
  Downloading https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
Installing collected packages: six, protobuf
  Found existing installation: protobuf 3.19.1
    Uninstalling protobuf-3.19.1:
      Successfully uninstalled protobuf-3.19.1
Successfully installed protobuf-3.17.3 six-1.16.0
```

For Protobuf 3.19.1, it doesn't appear we are building a `cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64` package. Here is the list of packages build for 3.19.1:

```
protobuf-3.19.1-cp310-cp310-macosx_10_9_universal2.whl 
protobuf-3.19.1-cp310-cp310-manylinux2014_aarch64.whl 
protobuf-3.19.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl 
protobuf-3.19.1-cp36-cp36m-macosx_10_9_x86_64.whl 
protobuf-3.19.1-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl 
protobuf-3.19.1-cp36-cp36m-win32.whl 
protobuf-3.19.1-cp36-cp36m-win_amd64.whl 
protobuf-3.19.1-cp37-cp37m-macosx_10_9_x86_64.whl 
protobuf-3.19.1-cp37-cp37m-manylinux2014_aarch64.whl 
protobuf-3.19.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl 
protobuf-3.19.1-cp37-cp37m-win32.whl 
protobuf-3.19.1-cp37-cp37m-win_amd64.whl 
protobuf-3.19.1-cp38-cp38-macosx_10_9_x86_64.whl 
protobuf-3.19.1-cp38-cp38-manylinux2014_aarch64.whl 
protobuf-3.19.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl 
protobuf-3.19.1-cp38-cp38-win32.whl 
protobuf-3.19.1-cp38-cp38-win_amd64.whl 
protobuf-3.19.1-cp39-cp39-macosx_10_9_x86_64.whl 
protobuf-3.19.1-cp39-cp39-manylinux2014_aarch64.whl 
protobuf-3.19.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl 
protobuf-3.19.1-cp39-cp39-win32.whl 
protobuf-3.19.1-cp39-cp39-win_amd64.whl 
protobuf-3.19.1-py2.py3-none-any.whl 
protobuf-3.19.1.tar.gz
```

Whereas for 3.17.3 we released:

```
protobuf-3.17.3-cp27-cp27m-macosx_10_9_x86_64.whl
protobuf-3.17.3-cp27-cp27mu-manylinux_2_5_x86_64.manylinux1_x86_64.whl
protobuf-3.17.3-cp35-cp35m-macosx_10_9_intel.whl
protobuf-3.17.3-cp35-cp35m-manylinux_2_5_x86_64.manylinux1_x86_64.whl
protobuf-3.17.3-cp35-cp35m-win32.whl
protobuf-3.17.3-cp35-cp35m-win_amd64.whl
protobuf-3.17.3-cp36-cp36m-macosx_10_9_x86_64.whl
protobuf-3.17.3-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl
protobuf-3.17.3-cp36-cp36m-win32.whl
protobuf-3.17.3-cp36-cp36m-win_amd64.whl
protobuf-3.17.3-cp37-cp37m-macosx_10_9_x86_64.whl
protobuf-3.17.3-cp37-cp37m-manylinux2014_aarch64.whl
protobuf-3.17.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl
protobuf-3.17.3-cp37-cp37m-win32.whl
protobuf-3.17.3-cp37-cp37m-win_amd64.whl
protobuf-3.17.3-cp38-cp38-macosx_10_9_x86_64.whl
protobuf-3.17.3-cp38-cp38-manylinux2014_aarch64.whl
protobuf-3.17.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl
protobuf-3.17.3-cp38-cp38-win32.whl
protobuf-3.17.3-cp38-cp38-win_amd64.whl
protobuf-3.17.3-cp39-cp39-macosx_10_9_x86_64.whl
protobuf-3.17.3-cp39-cp39-manylinux2014_aarch64.whl
protobuf-3.17.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl
protobuf-3.17.3-cp39-cp39-win32.whl
protobuf-3.17.3-cp39-cp39-win_amd64.whl
protobuf-3.17.3-py2.py3-none-any.whl
protobuf-3.17.3.tar.gz
```

Diffing these two lists we get:

```diff
-cp27-cp27m-macosx_10_9_x86_64.whl
-cp27-cp27mu-manylinux_2_5_x86_64.manylinux1_x86_64.whl
-cp35-cp35m-macosx_10_9_intel.whl
-cp35-cp35m-manylinux_2_5_x86_64.manylinux1_x86_64.whl
-cp35-cp35m-win32.whl
-cp35-cp35m-win_amd64.whl
+cp310-cp310-macosx_10_9_universal2.whl
+cp310-cp310-manylinux2014_aarch64.whl
+cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
 cp36-cp36m-macosx_10_9_x86_64.whl
-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl
+cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
 cp36-cp36m-win32.whl
 cp36-cp36m-win_amd64.whl
 cp37-cp37m-macosx_10_9_x86_64.whl
 cp37-cp37m-manylinux2014_aarch64.whl
-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl
+cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
 cp37-cp37m-win32.whl
 cp37-cp37m-win_amd64.whl
 cp38-cp38-macosx_10_9_x86_64.whl
 cp38-cp38-manylinux2014_aarch64.whl
-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl
+cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
 cp38-cp38-win32.whl
 cp38-cp38-win_amd64.whl
 cp39-cp39-macosx_10_9_x86_64.whl
 cp39-cp39-manylinux2014_aarch64.whl
-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl
+cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
 cp39-cp39-win32.whl
 cp39-cp39-win_amd64.whl
 py2.py3-none-any.whl
```

The two main changes I observe here are:
1. We've dropped Python 2.7 and 3.5, and added Python 3.10.
2. We've moved from `manylinux1` to `manylinux2014` as our ABI target.

**Comment by haberman** [comment] 2021-11-10 19:35
cc @jtattermusch 

Any idea how to revert the manylinux2014 to manylinux1 for Linux?

**Comment by jtattermusch** [comment] 2021-11-12 09:19
I looked into this and found that the problem most likely has nothing to do with my PR https://github.com/protocolbuffers/protobuf/pull/8280 (which only affects the build or aarch64 wheels and it doesn't change anything for the x86_64 wheels).

@haberman  is correct that there was a sudden switch from `manylinux1` to `manylinux2014` for x86_64 (so for systems older than what manylinux2014 supports, only the pure python version of protobuf python will be available - thus no cpp support, which explains the behavior reported in this issue).

It seems that the unintended switch from manylinux1 to manylinux2014 wasn't actually caused by a change in this repository, but by a change in https://github.com/matthew-brett/multibuild.
To build python wheels, we are using the multibuild scripts and we always clone the HEAD of that repository so any changes in that repository will be automatically picked up in the protobuf wheel build.
https://github.com/protocolbuffers/protobuf/blob/47e05427e3341c9b18fff047e7d9f79af0dafe9b/kokoro/release/python/linux/build_artifacts.sh#L28

On Aug 21, matthew-brett/multibuild has switched the default manylinux image from `1` to `2014` (see PR https://github.com/multi-build/multibuild/pull/423/files).

Some extra evidence:
- the 3.18.0-rc1 release (from Aug 20) still has the manylinux1 wheels: https://pypi.org/project/protobuf/3.18.0rc1/#files
- the 3.18.0-rc2 release (from Aug 31) only has manylinux2014 wheels for x86_64: https://pypi.org/project/protobuf/3.18.0rc2/#files  (and so the change from Aug 21 has almost certainly caused the regression).

The solution is relatively simple:
- make sure we explicitly set `MB_ML_VER=1` for the x86_64 wheels
- pin the clone of  matthew-brett/multibuild to a specific version to avoid unexpected changes like this in the future.
- it should also be possible to retroactively generate the missing manylinux1 wheels for older releases if needed.

**Comment by BenRKarl** [comment] 2021-11-15 18:18
Thanks @jtattermusch - do you have a rough idea of when this fix might make it into a release?

**Comment by jtattermusch** [comment] 2021-11-16 13:42
> Thanks @jtattermusch - do you have a rough idea of when this fix might make it into a release?

That is up to the protobuf team to decide. Also, they'll need to decide about possibly backporting into the existing releases.

**Comment by BenRKarl** [comment] 2021-11-29 17:08
Thanks @jtattermusch very much appreciated. Seems like the updates on the PR have stopped, is there anything we can do to revive that thread?

**Comment by andrea-cassioli-maersk** [comment] 2021-12-15 21:35
Same issue here. Any timeline update for the fix release?

**Comment by lambdamusic** [comment] 2022-02-06 18:13
I was able to get rid of the 

```
```

**Comment by jtattermusch** [comment] 2022-02-07 11:11
It doesn't seem that the fix https://github.com/protocolbuffers/protobuf/pull/9216 has made it into the 3.19.x branch for the 3.19 release.

Unless it gets backported, to 3.19.x, it will be in the next release 3.20.x.

@anandolee please consider backporting to 3.19.x

**Comment by martinxsliu** [comment] 2022-02-08 22:26
Hi, I'm curious to know if there's a timeline for the 3.20.x release? Or if it's been announced / tracked somewhere?

**Comment by anandolee** [comment] 2022-03-28 23:31
3.20.0 which includes the fix has already been pre released. Office release will happen in these two weeks

**Comment by BenRKarl** [comment] 2022-03-29 15:14
@anandolee thanks for the heads up. Do you know if this fix will get back ported to already released versions? If not we'll need to exclude versions `>= 3.18.0, < 3.20.0`

**Comment by anandolee** [comment] 2022-03-30 09:22
We do not have plan to back ported

**Comment by taliastocks** [comment] 2022-04-12 18:27
Hey, we were hit by this issue too. Was this fix released in `3.20.0`?

**Comment by BenRKarl** [comment] 2022-04-12 18:31
@taliastocks if it helps, we're currently using `3.20.0` without issues. We exclude 3.18.* and 3.19.*, see [here](https://github.com/googleads/google-ads-python/blob/main/setup.py#L37)

**Comment by haberman** [comment] 2022-05-10 23:19
We are about to release version 4.21.0, which builds wheels using an entirely new Bazel-based workflow. It should address the issues raised in this bug, and it uses `manylinux2014` as the platform on Linux.

More information here: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Closed by haberman** 2022-05-10 23:19 UTC
Labels: python
