### ISSUE TITLE
Descriptors.java:1763: warning: [removal] Integer(int) in Integer has been deprecated and marked for removal

### ISSUE THREAD

**Issue by davido** [protocolbuffers/protobuf#8462] opened 2021-04-07 19:25 UTC
After migration of Gerrit Code Review: [1] to build with Java 16 with Bazel, I'm seeing this deprecation warning on this code:

https://github.com/protocolbuffers/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/Descriptors.java#L1761-L1763

```
  $ bazel build --config=java16 java/com/google/gerrit/common:server
  [...]
  external/com_google_protobuf/java/core/src/main/java/com/google/protobuf/Descriptors.java:1763: warning: [removal] Integer(int) in Integer has been deprecated and marked for removal
        Integer key = new Integer(number);
                      ^
Target //java/com/google/gerrit/common:server up-to-date:
  bazel-bin/java/com/google/gerrit/common/libserver.jar
INFO: Elapsed time: 37.186s, Critical Path: 32.41s
INFO: 43 processes: 19 remote cache hit, 1 internal, 13 linux-sandbox, 10 worker.
INFO: Build completed successfully, 43 total actions
```

[1] https://gerrit-review.googlesource.com/c/gerrit/+/301362

**Comment by haberman** [comment] 2021-04-08 17:55
Closing as duplicate of https://github.com/protocolbuffers/protobuf/issues/8449.

**Closed by haberman** 2021-04-08 17:55 UTC
Labels: java

**Comment by Vismay88** [comment] 2021-10-01 02:48
How to solve this error of warning: [removal] Integer(int) in Integer has been deprecated and marked for removal
        Integer key = new Integer(number); in java

**Comment by Vismay88** [comment] 2021-10-01 02:50
import java.util.Scanner;

abstract class GenericMatrix{
    Object[][] matrix;
    GenericMatrix(Object[][] matrix){
        this.matrix=matrix;
    }
    public Object[][] addMatrix(Object[][] matrix){
        Object[][] result=new Object[matrix.length][matrix[0].length];
        if((this.matrix.length!=matrix.length) ||(this.matrix[0].length!=matrix[0].length)){
            System.out.println("Error: matrices do not have the same size");
            System.exit(0);
        }//perform addition
        for(int i=0;i<result.length;i++)
        for(int j=0;j<result[i].length;j++){
            result[i][j]=add(this.matrix[i][j],matrix[i][j]);
        }

        return result;
    }
    public Object[][] multiplyMatrix(Object[][] matrix){
        Object[][] result=new
        Object[this.matrix.length][matrix[0].length];
        //check sizes
        if(this.matrix[0].length!=matrix.length){
            System.out.println("Error: matrices do not have valid size");
            System.exit(0);
        }
        //perform multiplication
        for(int i=0;i<result.length;i++)
        for(int j=0;j<result[i].length;j++){
            result[i][j]=zero();
            for(int k=0;k<this.matrix[0].length;k++){
                result[i][j]=add(result[i][j],multiply(this.matrix[i][k],matrix[k][j]));
            }
        }

        return result;
    }
    abstract public Object add(Object o1, Object o2);
    abstract public Object multiply(Object o1, Object o2);
    abstract public Object zero();
    public static void displayMatrix(Object[][] m){
        for(int i=0;i<m.length;i++){
            for(int j=0;j<m[0].length;j++)
            System.out.print(m[i][j].toString()+" ");
            System.out.println();
        }
    }
}

class IntegerMatrix extends GenericMatrix{
    IntegerMatrix(Integer[][] matrix){
        super(matrix);
    }
    public Object add(Object o1,Object o2){
        Integer i1=(Integer)o1;
        Integer i2=(Integer)o2;
        return new Integer(i1.intValue()+i2.intValue());
    }
    public Object multiply(Object o1,Object o2){
        Integer i1=(Integer)o1;
        Integer i2=(Integer)o2;
        return new Integer(i1.intValue()*i2.intValue());
    }
    public Object zero(){
        return new Integer(0);
    }
}

public class GenMat{
    public static void main(String[] arg){
        Integer[][] m1=new Integer[3][3];
        Integer[][] m2=new Integer[3][3];
        //initialize two matrices
        Scanner sc=new Scanner(System.in);
        System.out.println("Enter value of matrix m1:");
        for(int i=0;i<m1.length;i++)
        {
            for(int j=0;j<m1[0].length;j++)
            {
                m1[i][j]=sc.nextInt();
            }
        }
        System.out.println();
        System.out.println("Enter value of matrix m2:");
        for(int i=0;i<m1.length;i++)
        {
            for(int j=0;j<m1[0].length;j++)
            {
                m2[i][j]=sc.nextInt();
            }
        }
        System.out.println();
        //create an instance of IntegerMatrix
        IntegerMatrix im=new IntegerMatrix(m1);
        //perform integer matrix addition and multiplication
        Object[][] addResult=im.addMatrix(m2);
        Object[][] mulResult=im.multiplyMatrix(m2);
        //display m1, m2, addResult, and mulResult

        System.out.println("Addition of given matrices:");
        IntegerMatrix.displayMatrix(addResult);
        System.out.println();
        
        System.out.println("Mutiplication of given matrices:");
        IntegerMatrix.displayMatrix(mulResult);
    }

}
 This code give me error of Integer(int) in Integer has been deprecated and marked for removal
Integer key = new Integer(number);
  in 59,69&72th  line any body please help me.
