### ISSUE TITLE
Custom options in dlang

### ISSUE THREAD

**Issue by deviator** [protocolbuffers/protobuf#5700] opened 2019-02-08 13:08 UTC
I try to improve D language plugin https://github.com/dcarp/protobuf-d/issues/14.
I have simple file for testing:
```proto3
syntax = "proto3";
package msg;

import "google/protobuf/descriptor.proto";

enum DMessageType {
    CLASS = 0;
    STRUCT = 1;
}

extend google.protobuf.MessageOptions {
    DMessageType d_message_type = 2022;
}

message OneData {
    option (d_message_type) = STRUCT;
    bool input = 1;
}
```
In plugin source code I add output for study and get this output:
```
{
    "dependencies": [
        "google\/protobuf\/descriptor.proto"
    ],
    "enumTypes": [
        {
            "name": "DMessageType",
            "values": [
                {
                    "name": "CLASS"
                },
                {
                    "name": "STRUCT",
                    "number": 1
                }
            ]
        }
    ],
    "extensions": [
        {
            "extendee": ".google.protobuf.MessageOptions",
            "jsonName": "dMessageType",
            "label": 1,
            "name": "d_message_type",
            "number": 2022,
            "oneofIndex": -1,
            "type": 14,
            "typeName": ".msg.DMessageType"
        }
    ],
    "messageTypes": [
        {
            "fields": [
                {
                    "jsonName": "input",
                    "label": 1,
                    "name": "input",
                    "number": 1,
                    "oneofIndex": -1,
                    "type": 8
                }
            ],
            "name": "OneData",
            "options": null // < here no custom options
        }
    ],
    "name": "msg\/one.proto",
    "package_": "msg",
    "syntax": "proto3"
}
```
Extension is parsed by `protoc` (check type too) but don't send information about it to plugin input (`options` field never contains custom options, only standard if added). Why?

This problem repeats for `FileOptions` too: array of options contains only standard options like `javaPackage` and other, but no custom options. What I do wrong?

**Comment by BSBandme** [comment] 2019-02-20 13:50
I'm not sure about the reason but I think protoc didn't link with the generated code that has your custom option. 

I think one way for resolving the problem is rebuilding protoc linked with your generated code that generated by old protoc.

**Closed by BSBandme** 2019-02-20 13:50 UTC
Labels: question
