### ISSUE TITLE
[C#] Google.Protobuf.JsonFormatter: Keep decimal point in all doubles

### ISSUE THREAD

**Issue by ConiJB** [protocolbuffers/protobuf#7825] opened 2020-08-18 09:10 UTC
**What language does this apply to?**
C# / proto3 

**Describe the problem you are trying to solve.**
The Google.Protobuf.JsonFormatter removes the decimal point when serializing double values that do not have digits after the decimal point. So this:

```
[TestMethod]
public void TestSerializeGoogle()
{
     var message = new LargeDoubleTestMessage()
     {
         LargeDouble = 210000000000
     };
     string jsonOutput = Google.Protobuf.JsonFormatter.Default.Format(message);
}
```

produces this json string:

`{ "largeDouble": 210000000000 }`

Unfortunately other serializers might use the decimal point to detect this as a double. So when this json string is exchanged, it might prevent deserialization (too large for an Int32) or it changes the type to Int64, which prevents the JsonFormatter from parsing it back into the original IMessage as a double is expected.

**Describe the solution you'd like**
A solution would be a similar formatting as Newtonsoft Json is using: This:

```
[TestMethod]
public void TestSerializeNewton()
{
    var cls = new LargeDoubleTestClass()
    {
        LargeDouble = 210000000000
    };
    string jsonOutput = Newtonsoft.Json.JsonConvert.SerializeObject(cls);
}
```

produces this json string:

`{"LargeDouble":210000000000.0}`

which makes it exchangeable.

**Describe alternatives you've considered**
I tried to find settings / flags with which I could influence the formatting behavior of the JsonFormatter, but could not find any. I believe this:

```
else if (value is float || value is double)
{
       string text = ((IFormattable) value).ToString("r", CultureInfo.InvariantCulture);
```

in JsonFormatter.cs is where a double is written and there is no way for me to change that.

**Comment by jskeet** [comment] 2022-08-02 14:09
I would suggest this is fundamentally a problem of "the other serializers". Lots of JSON serializers have their own little variations on what's actually specified - I don't want to go down that route with Google.Protobuf.

(I definitely wouldn't want to do this by default; while we *could* add it as yet another option in `JsonFormatter.Settings`, I'd really prefer not to do so.)

Closing for now - the issue is nearly two years old and hasn't generated any other community enthusiasm. @ConiJB if you feel really strongly about this, please add another comment and I can talk with the main protobuf team about it.

**Closed by jskeet** 2022-08-02 14:09 UTC
Labels: help wanted, c#, json
