### ISSUE TITLE
Add Ruby 3.3.0 compatibility

### ISSUE THREAD

**Issue by zameo94** [protocolbuffers/protobuf#15336] opened 2024-01-08 16:17 UTC
[Ruby 3.3.0 was released](https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/) on Christmas day as per tradition.

Updating my RoR app today I had this compatibility issue with `google-protobuf`:

`google-protobuf-3.25.1-x86_64-darwin requires ruby version < 3.3.dev, >= 2.7, which is incompatible with the current version, ruby 3.3.0p0`

I know today is the first day after the vacation break, I created this issue also to be updated on the status of the compatibility fix

Thanks

**Comment by acozzette** [comment] 2024-01-09 01:01
Thank you for the reminder. We are working on it and plan to include Ruby 3.3 support in the upcoming 26.x release this month.

**Comment by xfalcox** [comment] 2024-01-09 15:12
This is blocking @discourse Ruby upgrade, as protobuf is a dependency of the SASS gem we use.

**Comment by chadlwilson** [comment] 2024-01-09 16:53
Oddly this was already raised in #15182 however was closed with a commit/PR which only seemed to test against 3.3, but not actually ensure native gems were built declaring 3.3 compatibility.

**Comment by chadlwilson** [comment] 2024-01-10 03:07
To link together the other dependencies for people to follow, seems this also needs at least https://github.com/googleapis/ruby-common-tools/pull/286 and https://github.com/googleapis/ruby-common-tools/pull/293 - which the team seem to be aware of and working on.

**Comment by dazuma** [comment] 2024-01-17 21:38
/cc @zhangskz
The release infrastructure (in https://github.com/googleapis/ruby-common-tools) is updated. Note that the internal kokoro job configs might also need to be updated, as they can override the defaults set in ruby-common-tools.

**Comment by zhangskz** [comment] 2024-01-17 21:59
Thank you! I checked that we don't override GAS_RUBY_VERSIONS in our internal kokoro configs so we should be good. 

Closing this, as Ruby 3.3 should thus be supported in our upcoming 26.x release.

**Closed by zhangskz** 2024-01-17 21:59 UTC

**Comment by chadlwilson** [comment] 2024-02-08 03:06
Hello @zhangskz @dazuma - is it possible to consider backporting the relevant changes to support Ruby 3.3 to a `3.25.x` release?

I note from https://github.com/protocolbuffers/protobuf/releases/tag/v26.0-rc1 that v26 has breaking changes and will result in the released Ruby version becoming `4.26.0`. This means almost all dependent projects ([including grpc, notably](https://github.com/grpc/grpc/blob/239399212a33b3abe5e0762e2a4923d4334d2ebc/grpc.gemspec#L33)) will need to subsequently update dependency constraints, fix any issues and release new versions for users to be able to get prebuilt Ruby 3.3 compatibility, further delaying propagation of Ruby 3.3 support among the ecosystem. Since grpc recently released `1.61.0` with its own Ruby 3.3 compatibility, that'd mean having to wait until at least a `1.61.1` (assuming it's a minor upgrade from grpc perspective).

It seems unfortunate to end up with these changes coupled since I don't think any changes were actually needed to be made to support Ruby 3.3 other than actually building/testing the native gems?

**Comment by zhangskz** [comment] 2024-02-08 03:46
I believe based on how our ruby gems release infra is set up, any future patch to 25.x would already publish gems supporting Ruby 3.3. @dazuma does that sound right to you? 

I don't think we needed any changes in protobuf for Ruby 3.3 -- just added test coverage and updated ruby-common-tools.

**Comment by dazuma** [comment] 2024-02-08 06:20
@chadlwilson That's a very good point. We absolutely should release a 3.25.x version that supports Ruby 3.3.

@zhangskz The one thing I don't know is how the gemspec for the binary gems is constructed. It might need to be updated to allow Ruby 3.3 on the 25.x branch. Otherwise, yes, the cross compiler and release scripts now support 3.3 so we should be good on that front.

**Comment by chadlwilson** [comment] 2024-02-08 06:43
If I recall correctly (from playing on grpc side) rake-compiler-dock does some magic there to set the ruby ranges for the native gems, but I guess it also depends on whether the versions of the build tooling are specifically locked in source code or always use latest. (grpc locks them in source via Bazel but not sure about protobuf)

**Comment by dazuma** [comment] 2024-02-08 06:55
Hmm. I'll do some quick testing and see what it currently does.

**Comment by dazuma** [comment] 2024-02-09 02:28
Yeah confirmed, rake-compiler is updating the gemspec automatically based on which Ruby versions it actually compiles against. So, modulo having some tests set up, I think we're set for just doing a protobuf release. @zhangskz Can you get that onto the agenda for the protobuf team?

**Comment by chadlwilson** [comment] 2024-02-09 04:28
Thanks @dazuma - happy to help with anything an external contributor can do.

**Comment by chadlwilson** [comment] 2024-02-15 07:05
Any chance of a `25.3` release soon? I see @zhangskz has kindly cherry picked the testing across to `25.x` in https://github.com/protocolbuffers/protobuf/pull/15814 so seems we are close :D

**Comment by zhangskz** [comment] 2024-02-15 15:51
We have a `v25.3` release in the works this week.

**Comment by chadlwilson** [comment] 2024-02-16 13:26
Thanks, all seems working fine for us with 25.3 on Ruby 3.3 with and without grpc.

**Comment by dazuma** [comment] 2024-02-16 17:59
> Thanks, all seems working fine for us with 25.3 on Ruby 3.3 with and without grpc.

Great to hear, @chadlwilson! Thanks for the nudge on 25.x.
