### ISSUE TITLE
PHP better @returns type phpdoc comments

### ISSUE THREAD

**Issue by mc0** [protocolbuffers/protobuf#5071] opened 2018-08-23 01:21 UTC
**What language does this apply to?**
When generating code for fields in PHP that are repeated, the type gets set to `\Google\Protobuf\Internal\RepeatedField` rather than `\Google\Protobuf\Internal\RepeatedField|<actual field class>[]`

**Describe the problem you are trying to solve.**
Better hinting at PHP types for return values of repeated fields.

**Describe the solution you'd like**
Add the `<actual field class>[]` as a possible return

**Describe alternatives you've considered**
Hinting in every spot that something is returned

**Additional context**
```
    /**
     * Generated from protobuf field <code>repeated .mail.MailboxInfo mailboxes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMailboxes()
    {
        return $this->mailboxes;
    }
```

**Comment by haberman** [comment] 2022-03-08 17:44
Dupe of https://github.com/protocolbuffers/protobuf/issues/6145

**Closed by haberman** 2022-03-08 17:44 UTC
Labels: enhancement, php, P3
