### ISSUE TITLE
FieldDescriptor.default_value raises NotImplementedError on repeated field.

### ISSUE THREAD

**Issue by drush211** [protocolbuffers/protobuf#4896] opened 2018-07-11 15:30 UTC
**What version of protobuf and what language are you using?**
Version: v3.6.0
Language: Python

**What operating system (Linux, Windows, ...) and version?**

MacOSx 10.13.5

**What runtime / compiler are you using (e.g., python version or gcc version)**

python 3.6.5

**What did you do?**

1. Create Protobuf of

```
message StartRequest {
    Context matter_context          = 1; // Matter Context for the request.
    string search_string                                          = 2; // Search String used to find documents. Should NOT be combined with operations.
    OperationMetadata operation           = 3; // Operation to perform for the documents returned from the given search. Should NOT be combined with operations.
    repeated DocumentOperation operations = 4; // Document operations we need to perform. Should NOT be combined with search_string and operation.
}
```

2. Compile Protobuf into python using

```Makefile
protobuf:
	@python -m grpc_tools.protoc \
		--python_out=`pwd`/src/main/python \
		--grpc_python_out=`pwd`/src/main/python \
		--proto_path `pwd`/src/main/protobuf \
			`pwd`/src/main/protobuf/*.proto
```

3. 

```python
from start_request_pb2 import StartRequest

for field_name, field in StartRequest.DESCRIPTOR.fields_by_name.items():
    if field_name == "operations":
        # This should raise a NotImplementedError. It will also show that operations doesn't have
        # a default_value (per the boolean), but if you look at the actual descriptor it has a default_value
        # of [].
        print(f"Has default value: {field.has_default_value}, Default value: {field.default_value}")
```

**What did you expect to see**

has_default_value should be True, and default_value should return an empty list.

**What did you see instead?**

NotImplementedError, and has_default_value is False.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by xfxyjwf** [comment] 2018-07-12 00:54
Looks like you cannot do field.default_value if field.has_default_value == False. Seems reasonable behavior to me.

**Comment by drush211** [comment] 2018-07-12 02:06
at best it's confusing to have an object that looks like

```python
    _descriptor.FieldDescriptor(
      name='document_operations', full_name='document_operations', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
```

and not be able to get the default_value when requesting the property. If it doesn't have a default value, then why is a `default_value=[]` given instead of `default_value=None`? It seems like 2 options would be valid

```
# If decided "repeated" defaults to null
has_default_value=False, default_value=None
```

or

```python
# If decided "repeated" defaults to an empty list
has_default_value=True, default_value=[]
```

**Comment by anandolee** [comment] 2018-07-20 01:20
Can you try if the behavior is the same without using GRPC? (Just want to make clear if it is a grpc issue or protobuf issue)

The descriptor.py seems provided default_value if set to []:
https://github.com/google/protobuf/blob/master/python/google/protobuf/descriptor.py#L565

**Comment by anandolee** [comment] 2018-07-30 20:41
ping @drush211

**Comment by drush211** [comment] 2018-07-31 01:08
tried without grpc and the same issue occurred.

**Comment by anandolee** [comment] 2018-08-07 21:57
Thanks for reporting this. I can reproduce the error in pyext. The default value works well in pure python.
Just created a fix in our internal code.  It is being testing and waiting for review.

**Comment by anandolee** [comment] 2018-08-08 22:02
Update: the fix is approved and submitted in internal code base. Expect to see in 3.7.0 release.

**Comment by stackJolin** [comment] 2018-10-23 13:33
Currently,is there a workable deal?

**Comment by anandolee** [comment] 2019-03-14 23:53
Closing it as 3.7.0 is already released

**Closed by anandolee** 2019-03-14 23:53 UTC
Labels: bug, python, question, wait for 3.7.0 release
