### ISSUE TITLE
MergeFrom is implemented as Swap in Any

### ISSUE THREAD

**Issue by 1zg12** [protocolbuffers/protobuf#10021] opened 2022-05-21 10:54 UTC
**What version of protobuf and what language are you using?**
Version: main/v3.6.0/v3.5.0 etc.
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
For a sample protobuf message like 
```
message PositionGroup {
   repeated Position payloads = 1;
}
message Position {
  .....
}
```
With the `Any` class come from protobuf, if I want to merge two Messages of PositionGroup, like 
```
Any a1;//which is a pack for postiongroup1

Any a2;//which is a pack for postiongroup2

Any combined = a1.toBuilder(),mergeFrom(a2).build();
```

**What did you expect to see**
I would expect `combined` would contain the data from both positiongroup1 and positiongroup2.

**What did you see instead?**
while instead, `combined ` really becomes `a2`;

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
Looking at the source code, is this a prank ?

![image](https://user-images.githubusercontent.com/52658745/169648367-1a8a900f-e211-4314-b614-8aeb5c7b27ce.png)

**Anything else we should know about your project / environment**

**Comment by elharo** [comment] 2022-05-21 12:17
Per spec, "mergeFrom(Message other): (builder only) merges the contents of other into this message, overwriting singular scalar fields, merging composite fields, and concatenating repeated fields" so it does seem that the repeated payloads fields should be concatenated instead of replaced. 

I'm not sure what to do about this, or if it's possible to change this. We might decide to bless the current behavior.

**Comment by 1zg12** [comment] 2022-05-21 13:47
> 

I think it probably make better sense to even just throw a `"Not Implemented"` than providing a `random` implementation. 

For my case, I have several messages each with around 1 million repeated fields (the `payload`). While the front tier (a graphql) return the combined result (expecting several million of records back), however, always return 1 million fields. It took me quite a while to troubleshoot till surprisingly found out the protobuf implementation is totally different from what the API (`mergeFrom`) sounds like, make me almost feel like it's a prank.

**Comment by elharo** [comment] 2022-05-22 11:47
I think this is working as intended. In your example PositionGroup is not a subtype of Any or vice versa. Thus mergeFrom has the behavior expected of Any, not the mergeFrom behavior of PositionGroup. Thus there are no repeated fields to merge. any.proto only has two fields:

```
 string type_url = 1 [ctype = STRING_PIECE];
  bytes value = 2 [ctype = CORD];
 ```

Neither is repeated and both are merged here as expected. That is, Any is not java.lang.Object. When you store a proto message in an Any you lose all the type information and expected behavior of the original type. Protos are not self-describing.

**Closed by elharo** 2022-05-22 11:47 UTC
Labels: bug, java

**Comment by elharo** [comment] 2022-05-22 13:14
To get the behavior you want you'd need to take the bytes out of value, deserialize it as a PositionGroup, and then merge.

**Comment by 1zg12** [comment] 2022-05-23 13:42
> 



> To get the behavior you want you'd need to take the bytes out of value, deserialize it as a PositionGroup, and then merge.

Yes, that's how I did as a workaround as well. 
However, I think the `mergeFrom` in `Any` could be fixed. I guess instead of swapping the value/bytes, it should have for example trim the ending bytes of PositionGroup1, and trim the beginning bytes of PositionGroup2, and concatenate them.

Ideally, as the spec says, `Any` should operate generically, without worrying about whether it has wrapped is a `PositionGroup` or `OrderGroup`. And a `swapValue` implementation should either not be there for a `mergeFrom` or at least warn the developers.

**Comment by 1zg12** [comment] 2022-05-24 01:43
> 



> I'm not sure how that would work. An Any proto does not know what's inside of it.
> 
> Semantically an Any proto is just a URL and a BLOB. It knows nothing about the contents of the BLOB.

Alternatively, I think the type URL should be fixed. At the moment, the URL only contains the Simple name, something like `com.googleapi/PositionGroup`, this could provide the fully qualified name instead. With such, then `Any` could call out the right class for the actions for example `mergeFrom`.

Either way, `Any` could be more helpful in acting towards as a generic type.

**Comment by elharo** [comment] 2022-05-24 11:09
That would be a backwards incompatible change in Any and in mergeFrom.
