### ISSUE TITLE
More descriptive exception messaging in GPBUtil

### ISSUE THREAD

**Issue by dwsupplee** [protocolbuffers/protobuf#6437] opened 2019-07-24 17:46 UTC
Related issue: https://github.com/googleapis/google-cloud-php/issues/2127

**What language does this apply to?**
PHP

**Describe the problem you are trying to solve.**
More descriptive exception messages will help make debugging easier for our users.

**Describe the solution you'd like**
Currently, exception messages in [GPBUtil](https://github.com/protocolbuffers/protobuf/blob/43307d4da09e1a27b132cd3a2c29824efaafef25/php/src/Google/Protobuf/Internal/GPBUtil.php) inform you that your data didn't match the expected type. While this is helpful, it would be great if we could add a little more debug information to the message as well.

For example, in [GPBUtil::checkString](https://github.com/protocolbuffers/protobuf/blob/43307d4da09e1a27b132cd3a2c29824efaafef25/php/src/Google/Protobuf/Internal/GPBUtil.php#L96):
```diff
- throw new \InvalidArgumentException("Expect string.");
+ throw new \InvalidArgumentException(sprintf("Expect string. Instead received type '%s'", get_type($var));
```

**Comment by haberman** [comment] 2022-03-08 17:59
This appears to be a dupe of https://github.com/protocolbuffers/protobuf/issues/6437.

**Comment by haberman** [comment] 2022-03-08 18:00
Sorry, I meant it's a dupe of https://github.com/protocolbuffers/protobuf/issues/4473

**Closed by haberman** 2022-03-08 17:59 UTC
Labels: php
