### ISSUE TITLE
C#: .proto package name that starts with an underscore followed by a number generates C# code that doesn't compile

### ISSUE THREAD

**Issue by gauravsaxenais** [protocolbuffers/protobuf#8101] opened 2020-11-30 12:29 UTC
Currently I have a package name like this:

`package _9003aaa09a0c47fc8e24e738499835ef;`

This generates a namespace in C# like `9003aaa09a0c47fc8e24e738499835ef;`

which creates a compile time error. I believe the correct namespace should be `_9003aaa09a0c47fc8e24e738499835ef;`

**Comment by akjain2052** [comment] 2020-12-14 06:05
Hi, I am not able to reproduce this issue using v3.14.0 and v3.6.0 protoc compilers , checked with java and C# code. Please let me know how to reproduce this issue.

**Comment by akjain2052** [comment] 2020-12-22 07:30
I have tried this issue with v3.14.0, v3.6.0, v3.5.0 protoc compiler in windows and linux environment. 
I have not observed the issue. Please write the steps to reproduce the issue, and environment details.

**xyz.proto file** 
option csharp_namespace = "_9003aaa09a0c47fc8e24e738499835ef";

**Xyz.cs generated file in C#**
namespace _9003aaa09a0c47fc8e24e738499835ef {

**Comment by haberman** [comment] 2021-01-27 23:08
I can reproduce this if I use a `package` directive instead of `option csharp_namespace=`.

A workaround would be to use `option csharp_namespace=`.

@jtattermusch any ideas?

**Comment by jtattermusch** [comment] 2021-01-29 10:02
I haven't tried to reproduce, but this is how the "namespace" is generated in C# codegen:
https://github.com/protocolbuffers/protobuf/blob/de5d1b98c27428450b9a38ab5c2de479f59025af/src/google/protobuf/compiler/csharp/csharp_helpers.cc#L118

The source code also confirms the workaround to set `option csharp_namespace=`. This is probably a bug, but it seems to be quite an odd case (package name starting with and underscore followed by a number) so not a high priority to fix.

Note that the GetFileNamespace function also gets used by gRPC C# codegen:
https://github.com/grpc/grpc/blob/86f93801e5d452cff40d6958d21a8eb211da0654/src/compiler/csharp_generator.cc#L808

**Comment by fowles** [comment] 2022-07-01 21:20
Jan, is this still an open issue?

**Comment by tonydnewell** [comment] 2022-07-07 13:03
@jtattermusch I'll add it to my list to look at

**Comment by tonydnewell** [comment] 2022-07-15 11:15
I have a fix in csharp_helpers.cc _UnderscoresToCamelCase()_ that preserves the leading underscore if not doing so would produce an invalid C# identifier.  Out of caution I decided not to always preserve leading underscores for other valid identifiers in case anything is expecting the existing behaviour.

I'm still trying to work out how/if I can add unit tests.

**Comment by jskeet** [comment] 2022-07-15 12:08
Tony: shout if you'd like a hand with the unit tests.

**Comment by tonydnewell** [comment] 2022-07-19 12:21
Pull request created: https://github.com/protocolbuffers/protobuf/pull/10268

**Comment by jskeet** [comment] 2022-08-03 09:06
Closing as the PR is now merged.

**Closed by jskeet** 2022-08-03 09:06 UTC
Labels: bug, c#, P3
