### ISSUE TITLE
Support for DynamicMessage in C#

### ISSUE THREAD

**Issue by himkak** [protocolbuffers/protobuf#10422] opened 2022-08-17 09:10 UTC
**What language does this apply to?**
C#, proto3

**Describe the problem you are trying to solve.**
I have a requirement, where the schema is different for every customer. So I want to create descriptor dynamically.
The client sends json request according to its respective schema. This json request has to be converted to protobuf format. So for this I am looking for DynamicMessage support in google.protobuf's C# library. 
Though support for Descriptor (MessageDescriptor) is present, but for DynamicMessage its not present.

Is there any support for DynamicMessage in the google.protobuf's C# library, if not, is there any plans for this feature to be released in future?

This DynamicMessage is similar to the one present in google.protobuf's java library.

**Comment by jskeet** [comment] 2022-08-22 07:28
This is a duplicate of #658. I'll close this issue, but update that one.

**Closed by jskeet** 2022-08-22 07:28 UTC
Labels: c#
