### ISSUE TITLE
Building tensorflow 2.2 on macOS Catalina 10.15.4 protobuf 3.11.3 too many errors emitted, 

### ISSUE THREAD

**Issue by ghost** [protocolbuffers/protobuf#7519] opened 2020-05-16 13:05 UTC
I'm trying to build tensorflow from source on macOS , within less than a few minutes, I get a sequence of c++ errors and the build fails

**What version of protobuf and what language are you using?**
Version: 3.11.3
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript

**What operating system (Linux, Windows, ...) and version?**
macOS Catalina v 10.15.4

**What runtime / compiler are you using (e.g., python version or gcc version)**
Apple clang version 11.0.3 (clang-1103.0.32.29)

**What did you do?**
Check https://github.com/tensorflow/tensorflow/issues/39468

**What did you expect to see**
Building tensorflow successfully

**What did you see instead?**

```
ERROR: /private/var/tmp/_bazel_emadboctor/e4710f39cfc38993e5fe8f0eb15a51f2/external/com_google_p
rotobuf/BUILD:148:1: C++ compilation of rule '@com_google_protobuf//:protobuf' failed (Exit 1)
external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:68:91: error: cannot initialize a member subobject of type 'int' with an lvalue of type 'void ()'
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsscc_info_BoolValue_google_2fprotobuf_2fwrappers_2eproto}, {}};
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:82:91: error: cannot initialize a member subobject of type 'int' with an lvalue of type 'void ()'
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsscc_info_BytesValue_google_2fprotobuf_2fwrappers_2eproto}, {}};
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:96:91: error: cannot initialize a member subobject of type 'int' with an lvalue of type 'void ()'
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsscc_info_DoubleValue_google_2fprotobuf_2fwrappers_2eproto}, {}};
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:110:91: error: cannot initialize a member subobject of type 'int' with an lvalue of type 'void ()'
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsscc_info_FloatValue_google_2fprotobuf_2fwrappers_2eproto}, {}};
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:124:91: error: cannot initialize a member subobject of type 'int' with an lvalue of type 'void ()'
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsscc_info_Int32Value_google_2fprotobuf_2fwrappers_2eproto}, {}};
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:138:91: error: cannot initialize a member subobject of type 'int' with an lvalue of type 'void ()'
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsscc_info_Int64Value_google_2fprotobuf_2fwrappers_2eproto}, {}};
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:152:91: error: cannot initialize a member subobject of type 'int' with an lvalue of type 'void ()'
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsscc_info_StringValue_google_2fprotobuf_2fwrappers_2eproto}, {}};
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:166:91: error: cannot initialize a member subobject of type 'int' with an lvalue of type 'void ()'
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsscc_info_UInt32Value_google_2fprotobuf_2fwrappers_2eproto}, {}};
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:180:91: error: cannot initialize a member subobject of type 'int' with an lvalue of type 'void ()'
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsscc_info_UInt64Value_google_2fprotobuf_2fwrappers_2eproto}, {}};
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:310:20: error: no class named 'HasBitSetters' in 'google::protobuf::DoubleValue'
class DoubleValue::HasBitSetters {
      ~~~~~~~~~~~~~^
external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:315:24: error: redefinition of 'kValueFieldNumber' as different kind of symbol
const int DoubleValue::kValueFieldNumber;
                       ^
/usr/local/include/google/protobuf/wrappers.pb.h:227:5: note: previous definition is here
    kValueFieldNumber = 1,
    ^
external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:412:19: error: out-of-line definition of 'MergePartialFromCodedStream' does not match any declaration in 'google::protobuf::DoubleValue'
bool DoubleValue::MergePartialFromCodedStream(
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:456:19: error: out-of-line definition of 'SerializeWithCachedSizes' does not match any declaration in 'google::protobuf::DoubleValue'
void DoubleValue::SerializeWithCachedSizes(
                  ^~~~~~~~~~~~~~~~~~~~~~~~
external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:474:46: error: out-of-line definition of 'InternalSerializeWithCachedSizesToArray' does not match any declaration in 'google::protobuf::DoubleValue'
::PROTOBUF_NAMESPACE_ID::uint8* DoubleValue::InternalSerializeWithCachedSizesToArray(
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:561:19: error: redefinition of 'Swap'
void DoubleValue::Swap(DoubleValue* other) {
                  ^
/usr/local/include/google/protobuf/wrappers.pb.h:154:15: note: previous definition is here
  inline void Swap(DoubleValue* other) {
              ^
external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:575:19: error: redefinition of 'UnsafeArenaSwap'
void DoubleValue::UnsafeArenaSwap(DoubleValue* other) {
                  ^
/usr/local/include/google/protobuf/wrappers.pb.h:162:8: note: previous definition is here
  void UnsafeArenaSwap(DoubleValue* other) {
       ^
external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:595:19: error: no class named 'HasBitSetters' in 'google::protobuf::FloatValue'
class FloatValue::HasBitSetters {
      ~~~~~~~~~~~~^
external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:600:23: error: redefinition of 'kValueFieldNumber' as different kind of symbol
const int FloatValue::kValueFieldNumber;
                      ^
/usr/local/include/google/protobuf/wrappers.pb.h:378:5: note: previous definition is here
    kValueFieldNumber = 1,
    ^
external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:697:18: error: out-of-line definition of 'MergePartialFromCodedStream' does not match any declaration in 'google::protobuf::FloatValue'
bool FloatValue::MergePartialFromCodedStream(
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: /Users/emadboctor/Desktop/tensorflow/tensorflow/core/framework/BUILD:1084:1 C++ compilation of rule '@com_google_protobuf//:protobuf' failed (Exit 1)
INFO: Elapsed time: 58.678s, Critical Path: 7.64s
INFO: 213 processes: 213 local.
FAILED: Build did NOT complete successfully
(tfb) emadboctor@MacBook-Pro tensorflow %
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by lakshayg** [comment] 2020-10-16 21:22
I see the same error when trying to build tensorflow 2.3.1 on macOS Catalina 10.15.7

```
$ python3 --version
Python 3.9.0

$ clang --version
Apple clang version 12.0.0 (clang-1200.0.26.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by emadboctorx** [comment] 2020-10-17 04:35
@lakshayg I think it's tf version independent, there is a problem with the official documentation, it's awful, I faced lots of problems to get to install bazel and figure out which things work and which don't ex: mkl support. What I think the reason of the problem is c++ version is being some version while it should be another or maybe a list of problems, I don't know. I was able to build tensorflow 2.2 on ubuntu + conda and a few tweaks but it's useless for macOS, if you need it to be compatible then it should be built in the macOS evironment. I haven't retried for a while since I'm not using tensorflow these days, but when I will start needing tensorflow again I'll retry and update here with anything I find useful.

**Comment by lakshayg** [comment] 2020-10-17 05:53
Yes, I have been able to build it for ubuntu but no luck with macOS.

**Comment by dlj-NaN** [comment] 2020-10-22 20:45
This is a conflict between system-installed protobuf headers and the external dependency in TF. Here is an example of the difference:

```
external/com_google_protobuf/src/google/protobuf/wrappers.pb.cc:561:19: error: redefinition of 'Swap'
```

versus:

```
/usr/local/include/google/protobuf/wrappers.pb.h:154:15: note: previous definition is here
```

Unfortunately, this probably falls down to how your C++ toolchain is configured by Bazel.

The quickest workaround would be to remove the system-installed protobuf (or whatever thing put the headers in `/usr/local/include/google/protobuf`), and that should fix the flag ordering issue when running the compiler.

**Comment by lakshayg** [comment] 2020-10-23 02:29
Thanks, removing the system installed `protobuf` resolved this error. I had `mosh` installed which installed `protobuf` as a dependency (I still haven't been able to compile TF v2.3.1 though because of a different compilation issue)

**Comment by emadboctorx** [comment] 2020-10-23 06:23
@lakshayg what new issue?

**Comment by lakshayg** [comment] 2020-10-23 09:13
I did  not record the new issue and just switched to TF 2.2.1 which builds fine now. The binary I build is available here if you want to use it: https://github.com/lakshayg/tensorflow-build

When I searched for the errors I was seeing when building 2.3.1, I found a github issue which indicated that this had something to do with some sort of incompatibility between numpy 1.19.x and TF 2.3.1

**Comment by deannagarcia** [comment] 2022-07-26 21:39
Closing as I think this was resolved by changing protobuf versions.

**Closed by deannagarcia** 2022-07-26 21:39 UTC
Labels: c++, mac, bazel
