### ISSUE TITLE
Broken linebreaks in Protobuf-net generated XML comments

### ISSUE THREAD

**Issue by tweiss80** [protocolbuffers/protobuf#7891] opened 2020-09-17 13:22 UTC
**What version of protobuf and what language are you using?**
Version: master/v3.11.4
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Win10

**What runtime / compiler are you using (e.g., python version or gcc version)**
VS 2019

**What did you do?**
Add a comment to a proto field
message reply { 
	// This should cause a line break in VS 2019 (without spaces): < br/ > 
	// This should be the next line 
        int32 SomeField = 1;  
}

**What did you expect to see**
Comment in generated file looks like this: /// This should cause a line break in VS 2019:  < br/ > 
(Remove the spaces - caused github to insert a line break...)

**What did you see instead?**
Comment in generated file looks like this: /// This should cause a line break in VS 2019: &lt ;br/> 
(Remove the spaces - caused github to insert a line break...)

**Here is the reason:**
Line 58 causes this behaviour:
https://github.com/protocolbuffers/protobuf/pull/845/commits/67dd42c50d2b6d9c208bb1a4c63ee879781a9ac1#diff-2aeac396543d7beb1aafa7d047aef3d9

@jskeet I don't see the reason why you did the replacement: 
comments = StringReplace(comments, "<", "&lt ;", true);

**Comment by jskeet** [comment] 2020-09-17 13:44
This is working as intended. There's no fixed format for protobuf comments - so there's no guarantee whatsoever that a `<` will be part of a valid XML element, or that the XML element is intended to actually be a C# XML doc comment.

Instead, we escape the `<` so that the *text* node of the XML doc comment is the *text* of the original protobuf comment.

I wouldn't expect this to change.

**Comment by tweiss80** [comment] 2020-09-17 14:28
Thanks for the quick answer and I see the problem now.
I didn't find a workaround up to know to get VS multiline doc comments somehow working.

What might be an option:
If every line comment in proto files would be wrapped in a dedicated <summery> tag. Then VS would show it as multiline.

Proto comment:
// Line 1
// Line 2

would result in a visual studio doc comment
///<summary>Line 1</summary>
///<summary>Line 2</summary>

But I'm not sure about other side effects...

**Comment by jskeet** [comment] 2020-09-17 14:46
No, I don't think that's a good idea - I'd expect that to wreak havoc with Intellisense, for example, which would probably only show the first summary tag. Fundamentally just because a comment is on several lines doesn't mean it's several separate ideas, which is what having multiple summary tags would imply.

Basically, we're treating the comment as a blob of opaque text, and reproducing that in the summary tag. I don't think there's much more that protoc can do, without knowing more about the expected format of the comment.

**Closed** 2020-10-22 20:25 UTC

**Comment by juwens** [comment] 2021-06-22 21:18
I second the feature-request of the author.

Problem here is, that comments are rendered very much like xhtml, therefore if you have no `<br />` all lines are concatenated with no linebreake, which is very inconveniente.

So converting every comment linebreak from proto files to `<br />` for C# would be very reasonable.

There could be an option to enable analog to existing ones like `option csharp_namespace = "Foo.Bar.Project";` or `option java_multiple_files = true;`

for example example:
```
csharp_convert_comment_linebreak_to_break_tag = true;
```

**Comment by juwens** [comment] 2021-06-22 21:28
A very primitive approach would be this:

https://github.com/juwens/protobuf/commit/58937ba25a09d77db0aca804d6197b043c0ed08f
