### ISSUE TITLE
No duration.proto bundled with protobuf-lite

### ISSUE THREAD

**Issue by dimentiyinfo** [protocolbuffers/protobuf#7226] opened 2020-02-18 18:00 UTC
Problem is: several last builds (for example, protobuf-javalite-3.11.4.jar) contains compiled Duration class, but not bundled with duration.proto.

So it's not possible to use 
_import "google/protobuf/duration.proto";_

in our proto files.

Using old lite protobuf (3.0.0), workaround was possible - we can just place google's wellknown protos in our source tree.
With 3.11.4, this solution triggers DuplicateClass errors

**Comment by ejona86** [comment] 2020-06-01 18:33
This looks like a duplicate of #7094. Let's keep discussion on that other issue.

**Closed by ejona86** 2020-06-01 18:33 UTC
