### ISSUE TITLE
proto-javalite broken on Android API 19

### ISSUE THREAD

**Issue by kurtisnelson** [protocolbuffers/protobuf#6305] opened 2019-06-26 19:21 UTC
Both proto 3.8.0 and 3.9.0-rc-1 fail on write when running on Android 4.4 due to `sun.misc.Unsafe` usage.

```
System.err  W  java.lang.NoSuchMethodError: sun.misc.Unsafe.getFloat
                         W      at com.google.protobuf.UnsafeUtil$JvmMemoryAccessor.getFloat(UnsafeUtil.java:625)
                         W      at com.google.protobuf.UnsafeUtil.getFloat(UnsafeUtil.java:147)
                         W      at com.google.protobuf.MessageSchema.floatAt(MessageSchema.java:5709)
                         W      at com.google.protobuf.MessageSchema.writeFieldsInAscendingOrderProto2(MessageSchema.java:2589)
                         W      at com.google.protobuf.MessageSchema.writeTo(MessageSchema.java:2537)
                         W      at com.google.protobuf.AbstractMessageLite.writeToInternal(AbstractMessageLite.java:132)
                         W      at com.google.protobuf.GeneratedMessageLite.writeTo(GeneratedMessageLite.java:265)
                         W      at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeMessageNoTag(CodedOutputStream.java:1306)
                         W      at com.google.protobuf.FieldSet.writeElementNoTag(FieldSet.java:670)
                         W      at com.google.protobuf.FieldSet.writeElement(FieldSet.java:626)
                         W      at com.google.protobuf.MapEntryLite.writeTo(MapEntryLite.java:110)
                         W      at com.google.protobuf.CodedOutputStreamWriter.writeMap(CodedOutputStreamWriter.java:589)
                         W      at com.google.protobuf.MessageSchema.writeMapHelper(MessageSchema.java:3828)
                         W      at com.google.protobuf.MessageSchema.writeFieldsInAscendingOrderProto2(MessageSchema.java:2812)
                         W      at com.google.protobuf.MessageSchema.writeTo(MessageSchema.java:2537)
                         W      at com.google.protobuf.AbstractMessageLite.writeToInternal(AbstractMessageLite.java:132)
                         W      at com.google.protobuf.GeneratedMessageLite.writeTo(GeneratedMessageLite.java:265)
                         W      at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:70)
```

**Comment by haon4** [comment] 2019-06-28 17:40
@BSBandme do you know how we should work around this?

**Comment by kurtisnelson** [comment] 2019-06-28 17:45
adamkoski@ did a very careful experiment based rollout of Unsafe in maps about two years ago, I'm not sure what changed.

**Comment by haon4** [comment] 2019-06-28 17:47
ah, I think we might have missed something when we export JavaLite to open source. There are some alternative implementation that doesn't use `sun.misc.Unsafe`

**Comment by kurtisnelson** [comment] 2019-06-28 18:50
We have reproduced this reliably in a toy gradle app on a Galaxy S6 running 6.0.1 MMB29K with proto 3.8.0

**Comment by pixnbit** [comment] 2019-07-01 20:55
Hey @haon4, is this issue being worked on actively? Do you have a timeline? We're blocked from bumping protobuf-lite to 3.8.0 because of this.

**Comment by haon4** [comment] 2019-07-04 14:14
I am out of office this week. Will try to address this when I get back next week.

**Comment by BSBandme** [comment] 2019-07-08 17:01
Working on opensource more code. Hope it can be fixed by next down integration.

**Comment by pixnbit** [comment] 2019-07-08 17:02
Thanks @BSBandme , any ETA for it?

**Comment by BSBandme** [comment] 2019-07-08 17:17
it should can be done this week but not guaranteed.

**Comment by BSBandme** [comment] 2019-07-16 00:26
Sorry that the fix may be a little late for deciding which way to opensource the internal features.

**Comment by DanFTRX** [comment] 2019-07-23 19:06
@BSBandme Any ETA on this?  Is it in the range of Days? Weeks? months?

**Comment by MatFl** [comment] 2019-08-05 08:40
Just ran into the same with Unsafe.getBoolean on an API 23 device. On API 24+ it seems to work.

**Comment by BSBandme** [comment] 2019-08-09 18:29
It should be fixed in next down integration, which is expected to happen in the next one or two weeks.

**Comment by DysaniazzZ** [comment] 2019-08-26 10:02
same thing happened when use the latest  integration https://github.com/protocolbuffers/protobuf/issues/6565

**Comment by DanFTRX** [comment] 2019-08-26 13:26
@DysaniazzZ I don't think they have made a release since their last down integration.  https://github.com/protocolbuffers/protobuf/commit/4f02f056b5cea99052bfdfb6698afe47a3cf2964

**Comment by Dimezis** [comment] 2019-09-23 12:50
Just ran into the same issue, but with `Unsafe.getBoolean` on API 21 emulator.

**Comment by DanFTRX** [comment] 2019-09-23 13:13
@Dimezis I believe this will be fixed by 3.10.0 but perhaps @BSBandme can confirm

**Comment by kurtisnelson** [comment] 2019-09-24 08:38
Verified that 3.10.0-rc-1 fixes this on an API 19 emulator.

**Comment by kurtisnelson** [comment] 2019-09-24 14:04
We also need to get gRPC to adopt the new runtime for their plugin.

**Comment by rafi-kamal** [comment] 2019-10-01 21:57
Closing this issue since this is a duplicate of https://github.com/protocolbuffers/protobuf/issues/6551. Let me know if you still see similar issues in com.google.protobuf:protobuf-javalite:3.10.0.

**Closed by rafi-kamal** 2019-10-01 21:57 UTC
Labels: bug, java-lite

**Comment by DanFTRX** [comment] 2019-10-02 13:51
@rafi-kamal Is there going to be a full release of 3.10 soon or was the release candidate upgraded to a full release?

**Comment by rafi-kamal** [comment] 2019-10-03 01:30
We've officially done the [3.10.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.10.0) release today, although the maven artifacts for 3.10.0 stable were released a few days early since some users were needing them urgently.

**Comment by DanFTRX** [comment] 2019-10-03 14:11
@rafi-kamal Am I understanding correctly that the 3.10 release fixed this issue but also introduced a new issue which makes it impossible to use on phones older than API 26? (Java 7 compatability lost)

**Comment by rafi-kamal** [comment] 2019-10-03 20:01
Correct, but you should be fine if you are using javalite. The problem is in `GeneratedMessageV3.java` which javalite doesn't use. I'll update the release notes to clarify it.

**Comment by DanFTRX** [comment] 2019-10-03 20:05
@rafi-kamal Ah so its just an issue in protobuf-java but not protobuf-javalite.  Thankyou
