### ISSUE TITLE
Enum value support json_name option.

### ISSUE THREAD

**Issue by alirezaxfx** [protocolbuffers/protobuf#9607] opened 2022-03-09 10:11 UTC
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
proto3
If it's about generated code change, what programming language?
C++

**Describe the problem you are trying to solve.**
In some enum value, we have a value that name started with Number linked 3GPPXXX so we can't define it, we should add some prefix such as Underscore( _ ). so the problem when happened that convert message to JSON string and in JSON string enum value set exact value for example (_3GPPXXX).

**Describe the solution you'd like**
if we can support json_name option like the Protobuf field that changes Enum value _3GPPXXX to 3GPPXXX in converting to JSON string.

**Describe alternatives you've considered**

**Additional context**
For example we have this Enum.
![image](https://user-images.githubusercontent.com/6224570/157420295-a5bc3414-4ae4-4477-99f5-4f5b55579b10.png)

I want to support something like this.

![image](https://user-images.githubusercontent.com/6224570/157420563-99e9c73c-d37e-4a74-9060-ab36a85d4619.png)

**Comment by dlj-NaN** [comment] 2022-05-04 23:12
This is an interesting idea. Unfortunately, we probably won't have time to look at it any time soon, so I'm going to remove myself as assignee.

We could consider patches, but since this is a change to the JSON spec, it would need to be applied to all languages (and not just C++... that label seems to have been applied by mistake).

**Comment by jhump** [comment] 2022-08-16 16:03
This is a duplicate of #4328

**Closed** 2023-05-30 08:25 UTC
Labels: json
