### ISSUE TITLE
v26.1 and other versions for Cmake compilation error

### ISSUE THREAD

**Issue by 0xC4m3l-jiang** [protocolbuffers/protobuf#16931] opened 2024-05-23 09:21 UTC
I want to compile protobuf with cmake using v26.1. Finding compilation failure
![image](https://github.com/protocolbuffers/protobuf/assets/54069944/8bbe64fe-c0b0-47e1-96d3-1a07d6a28775)

We need to modify CMakeLists.txt
```
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```

**Comment by deannagarcia** [comment] 2024-06-04 21:09
Does this properly compile for you once you use C++ 14 or above?

It's intended behavior that it won't compile for older C++ versions and that you need to set the C++ version for cmake as documented [here](https://github.com/protocolbuffers/protobuf/blob/4d0081b352e1c457671ad5f84df8e7ecc704df2e/cmake/README.md?plain=1#L13). We don't want to automatically default to C++ 14 as some users might want a newer version.

**Comment by zhangskz** [comment] 2024-07-01 15:47
Closing since it looks like this works as intended -- please reopen if you have issues with c++14 or above.

**Closed by zhangskz** 2024-07-01 15:47 UTC
Labels: untriaged
