### ISSUE TITLE
Need specification for how to parse unrecognized enums in JSON

### ISSUE THREAD

**Issue by srcreigh** [protocolbuffers/protobuf#7392] opened 2020-04-16 22:28 UTC
I was forwarded to here by @tbkka over in the Swift protobuf library from this issue: https://github.com/apple/swift-protobuf/issues/972

As it stands the JSON serialization option in the swift-protobuf library is unusable because when it sees an unrecognized enum value that has been serialized to a JSON string, it throws an exception. There is no option to ignore the unrecognized string enum value, the only behaviour that swift-protobuf offers is to throw an exception.

To me it is abundantly obvious that any protobuf library has to ignore information that was generated using a newer schema.

For example, if a new enum field is shipped on a proto with v12.5 of an iOS app but is totally ignored (maybe it's a new feature under a shared schema that is implemented on a web app and is not implemented on the mobile app for a while). Then when this field, which is totally ignored, gets a new enum value, the v12.5 version of the app breaks because the only thing this that swift-protobuf can do is throw an exception when it sees the unrecognized enum value.

Of course this scenario is the core problem that protocol buffers as a whole set out to solve.

> Protocol buffers were designed to solve many of these problems:
> - New fields could be easily introduced, and intermediate servers that didn't need to inspect the data could simply parse it and pass through the data without needing to know about all the fields.
> https://developers.google.com/protocol-buffers/docs/overview#a-bit-of-history

(Of course an iOS app is not a server but it's the same thing as far as this is concerned because it participates in a distributed protocol.)

**Could someone please provide a specification for what a protobuf library should do when it sees an unrecognized Enum value serialized in a JSON string?**

I can't imagine that every other protobuf client that supports JSON serialized string enum values here crashes when it sees something unrecognized. Can someone point me to the behaviour of some of the other client libraries so that the folks over at swift-protobuf can have some precedence for how to handle this situation?

Thank you.

**Comment by acozzette** [comment] 2020-04-16 23:05
I'm not sure about other languages, but at least for C++ you can set an option to ignore unknown fields during JSON parsing, and this includes known fields with unknown enum values. The documentation [here](https://developers.google.com/protocol-buffers/docs/proto3#json) says: "Proto3 JSON parser should reject unknown fields by default but may provide an option to ignore unknown fields in parsing."

**Comment by tbkka** [comment] 2020-04-16 23:09
Could you please update the spec to explicitly call out enums as falling into this case?  It would also help if you could clarify expectations here for repeated enum fields.

And of course, expanding the conformance tester to verify these cases would be a nice treat!

**Comment by thomasvl** [comment] 2020-04-17 13:48
Also please document (add conformance tests) for what this means when enums are integer (vs. strings), and the value isn't a known value.

**Comment by thomasvl** [comment] 2020-04-17 13:59
@acozzette the only place I can find code for the C++ side seems to be within `JsonToBinaryStream` in `json_utils.cc` -

https://github.com/protocolbuffers/protobuf/blob/7bff8393cab939bfbb9b5c69b3fe76b4d83c41ee/src/google/protobuf/util/json_util.cc#L186-L187

Does that come into play in normal parsing (as opposed to transcoding which is what that api sorta looks like)?

Tracing the code a little further, there is a listener to get some feedback for that, but a normal parse of json to an object doesn't have a listener, so it is a silent data loss?

**Comment by thomasvl** [comment] 2020-04-17 15:13
Oh, and an enum field within a oneof also needs a spec.  In all these cases, does the value get ignored or does it get the default value?

**Comment by loganchang** [comment] 2020-06-12 16:56
Hello all! Does anyone have any updates for the questions asked by @thomasvl? I've currently encountered the same error as detailed in [apple/swift-protobuf#972](https://github.com/apple/swift-protobuf/issues/972) and would love to see how we can move this forward to get it merged in?

**Comment by doom-goober** [comment] 2020-10-16 23:14
> Oops, and for map<> usage, how does that end up working?
Enums are not allowed to be keys for a map. From https://developers.google.com/protocol-buffers/docs/proto3#maps:
>Note that enum is not a valid key_type

**Comment by thomasvl** [comment] 2020-10-19 13:36
Enums are only allowed as map values, not keys.

**Comment by kristianmo** [comment] 2021-02-04 08:03
The same issue exists in C#.

**Comment by wesmoncrief** [comment] 2022-01-10 20:14
Hi,
Thanks @srcreigh for reporting the issue, and everyone else for discussing and desiring to improve things! My team has also encountered this problem with both swift and python.

We would like to contribute here, but would appreciate it if the protobuf team could give some initial feedback on our approach before we begin.

1. Make a pull request adding conformance tests as the proposed specification. We’ll base the spec off of the current [Java implementation](https://github.com/protocolbuffers/protobuf/pull/4825/files)
This would mean ignoring unknown enum labels if the "ignoreUnknown" flag is set while parsing a JSON message. Both Java and C++ implementations are already aligned with this.

2. If that’s accepted, create a pull request implementing the fix for python. The change should be similar to the Java PR linked above.

**Comment by antongrbin** [comment] 2022-02-23 10:28
@acozzette I saw your recent comment on https://github.com/protocolbuffers/protobuf/pull/7974#issuecomment-1028257362 -- glad to hear that this is being discussed, thank you! Is it possible to share more details with us here?

My current thinking is that if we limit the scope to only enum **string** values, the decision might be easier. Concrete proposal here https://github.com/protocolbuffers/protobuf/pull/9534.

**Comment by acozzette** [comment] 2022-02-23 16:31
I believe @jonskeet is working on a proposal to allow optionally ignoring unknown enum string values, but the proposal has not been fully approved yet.

**Comment by antongrbin** [comment] 2022-03-31 10:06
@jskeet, thank you for working on the proposal for optionally ignoring unknown enum string values!

Is it possible to speak about the timeline here? Delaying this decision creates a bit of a mess, since different implementations are implementing different behaviours.

Offering specs initially only for `proto2` (since the situation might be simpler there) would also be helpful.

**Comment by jskeet** [comment] 2022-03-31 11:17
@antongrbin: We're still involved in internal discussions around this. I'm afraid I can't talk to timelines without those discussions being complete.

Our priority is proto3 rather than proto2, but if you have a use case you could share, that could be very helpful.

**Comment by antongrbin** [comment] 2022-03-31 12:21
Thank you for your response!

My use case is a bit selfish: my team currently uses only `proto2` and JSON. We use it to persist structured data blobs in databases, for message passing in event queues and for APIs. Since serialized message size was not an issue for us, we went with JSON to get human readability of messages and incremental protobuf adoption for consumers.

--

Going back to our topic, the decision making for `proto2` might be simpler. In fact, the [official language guide](https://developers.google.com/protocol-buffers/docs/proto#enum) already gives us the spec:

> a field with an enum type can only have one of a specified set of constants as its value (if you try to provide a different value, the parser will treat it like an **unknown field**).

Specifically, the `proto2` JSON parser should treat an unknown enum value as an unknown field. If ignore unknown fields is set, it should ignore it.

@jskeet, am I reading this correctly? What did I miss? Would it be possible to move forward only for `proto2`?

**Comment by jskeet** [comment] 2022-03-31 13:25
@antongrbin: The language guide was written before the JSON format was even designed.

I don't intend to start dividing the internal discussion into "just proto2 bits" and "proto3 bits" - that's likely to just make everything take even longer.

**Comment by fowles** [comment] 2022-07-16 18:17
We have a group working on doing an audit and formal definition for the correct answer for this right now.

**Comment by acozzette** [comment] 2022-09-01 17:54
I'm going to close this as a duplicate of #224.

**Closed by acozzette** 2022-09-01 17:54 UTC
Labels: documentation

**Comment by cassianomonteiro** [comment] 2022-10-22 03:03
> We have a group working on doing an audit and formal definition for the correct answer for this right now.

Hi @fowles, did we have any outcome from the audit? Any formal definition? I see that #224 is pretty stale at this point. And #9534 is depending on this.

**Comment by connoranderson** [comment] 2024-01-08 22:27
What ended up being the conclusion of this work? We're using the python library and are running into the same issues as OP.

**Comment by jskeet** [comment] 2024-01-09 06:39
@connoranderson: Unresolved as yet, I'm afraid. Sorry - as ever, there are huge numbers of things being done, with staffing that changes over time too. I'm not giving up on this completely, but I don't expect a resolution soon.

**Comment by antongrbin** [comment] 2024-01-10 10:59
Correct me if I am wrong, but for a subset of this problem we did align and added conformance tests.

Specifically when enums are encoded as strings and ignore unknown fields flag is set, the JSON parser should ignore the unknown enum value:
https://github.com/protocolbuffers/protobuf/blob/8c1f63571668338172148a1bea4575a33736a8c2/conformance/binary_json_conformance_suite.cc#L1738

According to the code search, all languages but Python are aligned with this:
https://github.com/search?q=repo%3Aprotocolbuffers%2Fprotobuf%20IgnoreUnknownEnumStringValueInOptionalField&type=code

**Comment by jskeet** [comment] 2024-01-10 11:04
@antongrbin: It's been a long time since I've looked at the ins and outs of the conformance tests, but that's definitely not the current C# behavior, and I was pretty sure this has caused a problem in languages other than Python and C# too.

**Comment by jskeet** [comment] 2024-01-10 11:11
@antongrbin #9534 added that conformance test, and at the time you wrote:

> Different clients yield different results when JSON parsing unknown enum string values:
>
> - java, cpp will ignore the unknown enum string value when ignoreUnknown is set
> - python, swift, c# will fail although ignoreUnknown is set

Was the Swift behavior changed? There are multiple other languages to consider too, some of which aren't covered in this repo - the ones I care most about being Ruby, PHP, Go and TypeScript.

**Comment by antongrbin** [comment] 2024-01-10 11:21
Swift behavior was changed in https://github.com/apple/swift-protobuf/pull/1345.

I definitely agree that there are other languages than what is covered with conformance tests in this repo.

I am confused about C# though -- it has conformance tests here, and the failure list doesn't surface the tests that #9534  added: https://github.com/protocolbuffers/protobuf/blob/main/conformance/failure_list_csharp.txt

**Comment by jskeet** [comment] 2024-01-10 11:26
@antongrbin: Yup, it confuses me too - but unfortunately I don't have time to delve into what's going on right now. I do hope we don't have other conformance test failures that we're missing :(
