### ISSUE TITLE
repeated primitives in Java TextFormat

### ISSUE THREAD

**Issue by wangdf** [protocolbuffers/protobuf#4907] opened 2018-07-13 02:37 UTC
Dear all,

The Java TextFormat implementation doesn't seem to support the 'short form' in the c++ version for repeated primitives. 

It not only creates long-winded results in some cases, but this mismatch between languages also causes headache when try to parse messages authorized in one with another.

Any suggestions are welcome.

Best Regards,
Difu
  
For example,
data: [0, 1] in c++
vesus 
data: 0
data: 1
in java.

**Comment by xfxyjwf** [comment] 2018-07-16 21:05
We can probably add an option to Java TextFormat to do the same.

**Comment by elharo** [comment] 2022-01-27 19:30
sounds like this should simply be done unconditionally (though that risks breaking poorly written golden tests) or not done at all. I don't think an option is needed.

go/textformat-spec

**Comment by shaod2** [comment] 2022-09-06 16:27
This seems to be already [supported](https://github.com/protocolbuffers/protobuf/blob/a3c8e2deb05186334b7ee8c1174f44802e38b43d/java/core/src/test/java/com/google/protobuf/TextFormatTest.java#L1502-L1508).
Closing the issue as it's not reproducible.

**Closed by shaod2** 2022-09-06 16:27 UTC
Labels: enhancement, help wanted, java
