### ISSUE TITLE
java.lang.IllegalAccessError: Field 'com.google.protobuf.Internal.ISO_8859_1' is inaccessible to class 'com.google.protobuf.Descriptors$FileDescriptor' (declaration of 'com.google.protobuf.Descriptors$FileDescriptor' appears in base.apk)

### ISSUE THREAD

**Issue by wanwan12** [protocolbuffers/protobuf#5745] opened 2019-02-18 08:41 UTC
Version: master/v3.0.0+.
Language: Java
system：Android

1. GeneratedMessageV3 msg = GeneratedMessageV3.newBuilder().setDomain(domain).build();
    msg.toString();

02-15 16:07:59.470 E/AndroidRuntime( 2629): java.lang.IllegalAccessError: Field 'com.google.protobuf.Internal.ISO_8859_1' is inaccessible to class 'com.google.protobuf.Descriptors$FileDescriptor' (declaration of 'com.google.protobuf.Descriptors$FileDescriptor' appears in base.apk)
02-15 16:07:59.470 E/AndroidRuntime( 2629): 	at com.google.protobuf.Descriptors$FileDescriptor.internalBuildGeneratedFileFrom(Descriptors.java:334)

**Comment by BSBandme** [comment] 2019-02-20 14:34
Would you please provide more information? E.g did you use your java lite or java? How did you use protobuf? Any example proto or any steps to repro the bug?

**Comment by GankLun** [comment] 2019-06-12 05:37
I also met this issue,with protobuf-java-3.7.1 version,on Android P devices,but then I change the code,not invoke Internal.ISO_8859_1,but invoke Charset.forName("ISO-8859-1") directly,it is resolved,but another similar problem happened.
ava.lang.IllegalAccessError: Illegal class access ('com.google.protobuf.GeneratedMessageV3' attempting to access 'com.google.protobuf.IntArrayList') in attempt to invoke static method com.google.protobuf.IntArrayList com.google.protobuf.IntArrayList.emptyList() (declaration of 'com.google.protobuf.GeneratedMessageV3' appears in /system/app/lbsservice.apk)
        at com.google.protobuf.GeneratedMessageV3.emptyIntList(GeneratedMessageV3.java:373)
        at com.google.protobuf.DescriptorProtos$FileDescriptorProto.<init>(DescriptorProtos.java:1175)
        at com.google.protobuf.DescriptorProtos$FileDescriptorProto.<clinit>(DescriptorProtos.java:4696)
        at com.google.protobuf.DescriptorProtos$FileDescriptorProto.parseFrom(DescriptorProtos.java:2187)
        at com.google.protobuf.Descriptors$FileDescriptor.internalBuildGeneratedFileFrom(Descriptors.java:343)
        at com.ecarx.pro.ProHeader.<clinit>(ProHeader.java:1314)
        at com.ecarx.pro.ProHeader.access$200(ProHeader.java:6)
        at com.ecarx.pro.ProHeader$Header$ParametersDefaultEntryHolder.<clinit>(ProHeader.java:332)
        at com.ecarx.pro.ProHeader$Header$Builder.internalGetParameters(ProHeader.java:1080)
        at com.ecarx.pro.ProHeader$Header$Builder.buildPartial(ProHeader.java:758)
        at com.ecarx.pro.ProHeader$Header$Builder.build(ProHeader.java:740)
        at com.ecarx.lbsservice.c.b.c(LbsManager.java:268)
        at com.ecarx.lbsservice.service.AlarmService.onHandleIntent(AlarmService.java:49)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)

**Comment by BeyondSpace609520** [comment] 2020-07-12 02:39
I have also faced same trouble. How can we fix it?

**Comment by deannagarcia** [comment] 2022-09-02 18:49
Closing this due to no reproduction instructions. If you're still seeing this error please reopen with the information required by our template (version, environment, build conditions).

**Closed by deannagarcia** 2022-09-02 18:49 UTC
Labels: java-lite, customer issue, wait for user action
