### ISSUE TITLE
Broken protoc command line on windows

### ISSUE THREAD

**Issue by xfxyjwf** [protocolbuffers/protobuf#4993] opened 2018-08-02 18:40 UTC
See: https://github.com/google/protobuf/issues/3028

The following commands should have worked:
```
>protoc a:\proto_dir\CNTK.proto --csharp_out "A:\Output directory\" --proto_path a:\proto_dir\
a:\proto_dir\CNTK.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).

>protoc CNTK.proto --csharp_out "A:\Output directory\" --proto_path a:\proto_dir\
CNTK.proto: No such file or directory

>protoc a:\proto_dir\CNTK.proto --csharp_out "A:\Output directory\" --proto_path a:\proto_dir
a:\proto_dir\CNTK.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).

>protoc --csharp_out "A:\Output directory\" --proto_path a:\proto_dir\ a:\proto_dir\CNTK.proto
Missing input file.

>protoc --csharp_out "A:\Output directory\" --proto_path a:\proto_dir\ CNTK.proto
Missing input file.

>protoc --csharp_out "A:\Output directory\CNTK.proto.cs" --proto_path=a:\proto_dir\ a:\proto_dir\CNTK.proto
A:\Output directory\CNTK.proto.cs/: No such file or directory

>protoc --csharp_out "A:\Output directory\" --proto_path=a:\proto_dir\ a:\proto_dir\CNTK.proto
Missing input file.

>protoc --csharp_out="A:\Output directory\" --proto_path="a:\proto_dir\" a:\proto_dir\CNTK.proto
a:\proto_dir\CNTK.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).

>protoc --csharp_out="A:\Output directory\" --proto_path="a:\proto_dir\" "a:\proto_dir\CNTK.proto"
a:\proto_dir\CNTK.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).

A:\proto_dir>protoc.exe --csharp_out="A:\Output directory\" --proto_path=. CNTK.proto
Missing input file.

A:\proto_dir>protoc.exe --csharp_out="A:\Output directory\" --proto_path=./ CNTK.proto
Missing input file.

A:\proto_dir>protoc.exe --csharp_out="A:\Output directory\" CNTK.proto
Missing input file.

A:\proto_dir>protoc.exe --csharp_out="A:\" CNTK.proto
Missing input file.
```

**Comment by rainersigwald** [comment] 2018-08-17 21:40
My educated guess is that this is due to the command-line argument parser handling the trailing slash in `--csharp_out="A:\Output directory\"` as "escape the next character" instead of "directory separator". I bet the arguments are being split as

```
a:\proto_dir\CNTK.proto
--csharp_out
A:\Output directory" --proto_path a:\proto_dir\
```

instead of the expected

```
a:\proto_dir\CNTK.proto
--csharp_out
A:\Output directory\
--proto_path
a:\proto_dir\
```

(This is a common problem on Windows.)

**Comment by Science-and-Motion-Sports** [comment] 2019-09-10 15:00
@rainersigwald Can you please give one example of a command line tool included in Windows that has the same behavior as protoc, in that it parses `\"` as `"` ?

**Comment by mkruskal-google** [comment] 2022-09-01 18:34
This is a duplicate of [#3028](https://github.com/protocolbuffers/protobuf/issues/3028).  I'm not dismissing the underlying problem, but this isn't a bug in our protoc CLI

**Closed by mkruskal-google** 2022-09-01 18:34 UTC
Labels: bug, c++, windows, protoc
