### ISSUE TITLE
Failure to add file descriptor on OSX

### ISSUE THREAD

**Issue by JonathanMcDevitt** [protocolbuffers/protobuf#6244] opened 2019-06-11 22:57 UTC
**What version of protobuf and what language are you using?**
Version: 3.7.0
Language: C++

**What operating system (Linux, Windows, ...) and version?**

OSX

**What runtime / compiler are you using (e.g., python version or gcc version)**

XCode 5.1

**What did you do?**

For our data driver to connect to and read data from Google BigQuery, we are building gRPC and the BigQuery Storage API into a library which serves as an entry-point for the driver. When we load the driver into iodbctest, the driver loads the library, which throws the below error.

![OSX_Fail](https://user-images.githubusercontent.com/50157372/59312049-7b022d00-8c60-11e9-835c-73b9a766e995.png)

1. Statically link gRPC (v1.20.1) and the BigQuery Storage API (GitHub, googleapis/master) against a library Wrapper
2. Build Wrapper to be dynamically linked against another library on OSX (i.e. build into a dylib and link against another dylib)
3. Load the library, which will load Wrapper.
4. See failure.

**What did you expect to see**

Library loads without a problem.

**What did you see instead?**

![OSX_Fail](https://user-images.githubusercontent.com/50157372/59312049-7b022d00-8c60-11e9-835c-73b9a766e995.png)

**Anything else we should know about your project / environment**

**Comment by thomasvl** [comment] 2019-06-12 19:05
Drive by - Xcode 5.1 was ~ 2014.  If you are trying to use that and mixing it with things built with newer toolchains, there may be Apple ABI issues coming into play here.

**Comment by JonathanMcDevitt** [comment] 2019-06-13 20:28
Hi @thomasvl,

Both the data driver and the Storage API wrapper library are compiled and linked with XCode 5.1, and prior to this were running fine with iODBC Test 3.52.8. Is there a known issue with using 5.1 for building gRPC?

Thanks,
~Jon

**Comment by thomasvl** [comment] 2019-06-13 20:38
No clue.  I don't work on the C++ side of protos, as far as grpc specific parts, you likely need to check with them also.  I was just commenting that using a toolchain that old is sorta surprising.  Why do you need to use such an old version?

**Comment by JonathanMcDevitt** [comment] 2019-06-13 20:43
Part of the requirements for our drivers is that we support older toolchains like this, so we are locked into supporting 5.1 as a minimum version.

**Comment by JonathanMcDevitt** [comment] 2019-06-14 20:52
To clarify, this issue is not encountered in our Windows or Linux builds; this problem is only encountered during our OSX workflow.

**Comment by yang-g** [comment] 2019-06-28 21:58
It looks like the proto might be in https://github.com/googleapis/googleapis/blob/6a2f0244d6a07f2683e4a8cec514425bb27cfa03/google/cloud/bigquery/storage/v1beta1/storage.proto

**Comment by yang-g** [comment] 2019-06-28 22:08
@JonathanMcDevitt do you know whether it is that proto that triggers the problem? Or do you happen to know which proto caused the problem? Thanks.

**Comment by yang-g** [comment] 2019-06-28 22:13
@acozzette

**Comment by acozzette** [comment] 2019-06-28 23:25
It looks like there is a failure to parse the serialized descriptors because of invalid UTF-8 data in the `HttpRule.get` field, which must be a custom option somewhere. It would be good to figure out where that custom option is coming from. The simplest explanation is that the `.proto` file might just contain invalid UTF-8 in a custom option.

**Comment by JonathanMcDevitt** [comment] 2019-07-03 15:28
Hi all,

Apologies for the delay in response; Monday was a holiday.

Would this then be an issue with the BigQuery Storage API part of Google APIs? We aren't using protoc to generate the files in an unusual fashion, we're just using the Makefile included in https://github.com/googleapis/googleapis to generate the files, and then including the relevant BigQuery .h/.cc files in the build for the aforementioned wrapper library. We most recently pulled the repository on May 23rd, from which we generated the files.

Something that's still unclear is why this would be triggered before we actively call any of the Storage API code. Would we be able to pull anybody from the Storage API dev team in on this?

Thanks,
~Jon

**Comment by acozzette** [comment] 2019-07-03 17:05
I suspect it's not an issue with the Storage API per se but likely a problem with how the storage API protos are getting built or linked.  Generated protobuf messages ordinarily do some pre-main initialization to register themselves in the process-wide descriptor pool, though in this case I assume it's not all happening pre-main because if you're dynamically loading a dylib then it will happen at that time of dynamic loading. That would explain why the crash is occurring before you even call any Storage API code.

The error message is complaining about invalid UTF-8 data but I now suspect that this is a red herring. It seems unlikely that the storage API protos would contain any custom string options with invalid UTF-8, and if they did then that would also affect the Linux and Windows builds.

Instead I would guess that the problem has to do with the dynamic loading.  Within Google we don't really do any dynamic loading of protobuf generated code, so that is an area we don't have much experience with. Is it possible that you have some of the same proto messages represented in multiple dylibs, or the protobuf runtime linked into multiple dylibs? That could cause ODR violations which could potentially explain the crash. If it's at all possible to avoid the dynamic loading then that would also likely simplify things and solve the problem.

**Comment by JonathanMcDevitt** [comment] 2019-07-03 17:18
On the subject of the necessity of dynamic loading, I'm afraid it is required to dynamically link the wrapper library to the driver. There are conflicts between the gRPC BoringSSL and the OpenSSL we use in the driver, and the only way we were able to get around it was to build the driver and the library separately and link them dynamically. The protobuf runtime is statically linked to the wrapper dylib, and that's the only dylib that has the protobuf runtime linked to it.

**Comment by acozzette** [comment] 2019-07-03 17:24
OK, I see. Just to make sure I understand, is it correct that the driver dynamically loads the wrapper and the wrapper is a dylib consisting of gRPC + storage API + libprotobuf?

**Comment by JonathanMcDevitt** [comment] 2019-07-03 17:29
Yes, the wrapper links all of the grpc runtimes and libprotobuf, and the driver loads the wrapper dylib. just as a point of clarity, the Storage API code is compiled into the wrapper dylib, not linked.

**Comment by acozzette** [comment] 2019-07-03 17:37
Have you tried building gRPC without BoringSSL? I came across this [issue](https://github.com/grpc/grpc/issues/11655#issuecomment-312075733) which seems to say that gRPC can build against OpenSSL. I'm not sure if this is the problem but it's possible that using both BoringSSL and OpenSSL together would cause ODR violations even if BoringSSL is in a separate dylib.

**Comment by JonathanMcDevitt** [comment] 2019-07-03 18:07
I'll admit that OSX development is similarly not something I've done in any great capacity, so I'm not sure what would make it violate ODR on OSX and not on other platforms. The idea behind the dynamic linking we've been doing was to isolate the symbols and make them accessible from their relevant libraries. The OpenSSL symbols linked to and defined in the driver should not be overridden by those in the wrapper dylib, since the BoringSSL symbols are linked to and defined in the wrapper and not the driver. Why would the BoringSSL symbols linked to an external library conflict with OpenSSL on OSX, but be just fine on Linux?

I think the crux of my confusion here is whether xcode treats ODR differently than gcc when linking. It seems odd that it would differ that severely.

**Comment by acozzette** [comment] 2019-07-03 18:19
The thing with ODR violations is that they are undefined behavior but aren't guaranteed to cause an observable problem. It could be that the ODR violations exist for all three platforms but only result in a noticeable issue for the OSX build. In principle I believe the dynamic loading could be used to prevent ODR violations but I think you would have to set things up carefully with a linker script so that all the BoringSSL symbols are hidden.

Still I think I would it be worthwhile to try using just OpenSSL and skipping the dynamic loading if that's at all possible because that would simplify everything. Since we almost never do dynamic loading of protobuf code within Google, that use case is not well tested and no one on the protobuf team is very familiar with how to do it properly.

**Comment by JonathanMcDevitt** [comment] 2019-07-03 18:24
Yes, I think I'll do that. I need to investigate how to specify a location for OpenSSL when building gRPC (we don't use the ones native to the system), and then I'll give it a rebuild on OSX and update this ticket with the results.

**Comment by acozzette** [comment] 2019-07-03 18:27
Sounds good, let me know if that works. @nicolasnoble Do you have any advice on building gRPC against a specific OpenSSL (not the system-installed one)?

**Comment by JonathanMcDevitt** [comment] 2019-07-03 18:44
For reference, we are using OpenSSL 1.1.0. I did some digging around and came across https://github.com/grpc/grpc/issues/10589. @nicolasnoble is OpenSSL 1.1.x supported? I was reading https://github.com/grpc/grpc/pull/11495 and I just want to be sure that the end result means that 1.1.x can be used in place of BoringSSL.

**Comment by JonathanMcDevitt** [comment] 2019-07-10 15:20
Hi all,

I've been trying to find a way to build gRPC with a specified version of OpenSSL (perhaps similar to how libcURL does?), but I can't seem to find anything. @nicolasnoble, do you or any of your cohorts know of a way to do so? Is there an option I can specify when building gRPC? The closest I've come is the CMakeLists for the helloworld cpp example, there there is a mention of an OPENSSL_ROOT_DIR, but this doesn't seem to be present in any of the other makefiles or CMakeLists.

Thanks,
~Jon

**Comment by acozzette** [comment] 2019-07-16 01:19
@yang-g Do you know how to build gRPC with a specified version of OpenSSL?

**Comment by acozzette** [comment] 2019-08-05 17:50
@JonathanMcDevitt Were you able to sort out the problem?

**Comment by JonathanMcDevitt** [comment] 2019-08-08 14:44
Hi @acozzette, I have not. There doesn't seem to be a way for me to build gRPC with an OpenSSL that is not the system OpenSSL. I'm waiting on hearing back from gRPC on this issue.

**Comment by yang-g** [comment] 2019-08-08 15:53
The only thing I can find is a feature request in https://github.com/grpc/grpc/issues/15591.
@nicolasnoble can give the authoritative answer here.

**Comment by JonathanMcDevitt** [comment] 2019-08-19 17:56
Is there any way to get @nicolasnoble's input on this as well, if he's the one with the knowledge?

**Comment by JonathanMcDevitt** [comment] 2019-08-30 22:19
Hi all,

Is there any way we can raise the priority on this and get it more visibility? Our production for OSX has been down for nearly three months now due to this issue.

WRT @nicolasnoble's response, we have been building gRPC via CMake. @jtattermusch can you verify the solution for issue https://github.com/grpc/grpc/issues/15591? I was looking through the CMakeLists but I can't see any such handling for the OPENSSL_ROOT_DIR option outside of one of the example projects (grpc/examples/cpp/helloworld/cmake_externalproject/CMakeLists.txt). If that would indeed let us build with a custom OpenSSL, can we have that handling moved up to the CMakeLists.txt in the main gRPC? I'm also unclear on exactly how that functions. We have OpenSSL pre-compiled with the .a archives and header files available; would we need to make the source files available, or would it be possible to compile with the headers + archives?

For my part, I'll experiment with the CMakeLists.txt in the main project locally and try to build it with the library linked statically to verify, but for the purposes of releasing the product we should have a Google-verified change made to the gRPC project.

Thanks,
~Jon

**Comment by jtattermusch** [comment] 2019-09-05 13:56
Building against OpenSSL using cmake should work. 
we are actually building against OpenSSL in one of our distribtests for window (yes, it's windows, but there's shouldn't be any conceptual difference because it's cmake).
See 
https://github.com/grpc/grpc/blob/a1ad4800da2bb02c843bdaea8fb06518916b6fba/test/distrib/cpp/run_distrib_test_cmake.bat#L57 (after installing OpenSSL into a local directory, which on linux should be possible to do using cmake, you can use that version of OpenSSL by setting `-DOPENSSL_ROOT_DIR=` and `-DgRPC_SSL_PROVIDER=package`.)

**Comment by jtattermusch** [comment] 2019-09-05 14:02
@JonathanMcDevitt  I also commented in https://github.com/grpc/grpc/issues/15591. Please try using the instructions I provided and let us know if that works for you - to my best knowledge it should.

**Comment by JonathanMcDevitt** [comment] 2019-09-05 16:17
Hi Jan,

Thanks, I'm currrently looking into that. I'll update this with results and/or questions as soon as I'm able.

Thanks,
~Jon

**Comment by JonathanMcDevitt** [comment] 2019-09-30 17:26
Hi Jan,

We've been trying to build gRPC with a custom OpenSSL and ZLib, but have been running into snags on Linux and OSX thus far. I'll elaborate below, but the summary is that we can't build some of the libraries on Linux 32-bit (specifically libgrpcpp_channelz, libgrpc++_reflection, and libgrpc++_error_details), and when building on OSX the -DZLIB_ROOT isn't being respected.

## Linux 32-bit Issues

When building, we have the below command:

```
cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-m32" -DCMAKE_CXX_FLAGS="-m32" -DCMAKE_EXE_LINKER_FLAGS="-m32" -DCMAKE_MODULE_LINKER_FLAGS="-m32" -DCMAKE_SHARED_LINKER_FLAGS="-m32" -DCMAKE_CROSSCOMPILING=1 -DRUN_
HAVE_STD_REGEX=0 -DRUN_HAVE_POSIX_REGEX=0 -DOPENSSL_ROOT_DIR=/home/jmcdevitt/Perforce/jmcdevitt_Dev_Ubuntu/ThirdParty/openssl/1.1.0/centos7/gcc5_5/release32 -DgRPC_SSL_PROVIDER=package -DZLIB_ROOT=/home/jmcdevitt/Perforce/jmcdevitt_Dev_Ubuntu/ThirdParty/zlib/1.2.11/cento
s7/gcc5_5/release32 -DgRPC_ZLIB_PROVIDER=package

cmake --build .
```

According to the output of the initial CMake command all of the values we input (-Ds) are used, but we receive errors when trying to use the compiled executables.

```
[1515/1531] Running gRPC C++ protocol buffer compiler on src/proto/grpc/status/status.proto
FAILED: gens/src/proto/grpc/status/status.grpc.pb.cc gens/src/proto/grpc/status/status.grpc.pb.h gens/src/proto/grpc/status/status_mock.grpc.pb.h gens/src/proto/grpc/status/status.pb.cc gens/src/proto/grpc/status/status.pb.h
cd /home/jmcdevitt/dev/Scratch/grpc && /home/jmcdevitt/dev/Scratch/grpc/debug32/third_party/protobuf/protoc-3.10.0.0 --grpc_out=generate_mock_code=true:/home/jmcdevitt/dev/Scratch/grpc/debug32/gens --cpp_out=/home/jmcdevitt/dev/Scratch/grpc/debug32/gens --plugin=protoc-gen-grpc=/home/jmcdevitt/dev/Scratch/grpc/debug32/grpc_cpp_plugin -I . -I /home/jmcdevitt/dev/Scratch/grpc/third_party/protobuf/src src/proto/grpc/status/status.proto

[1516/1531] Running gRPC C++ protocol buffer compiler on src/proto/grpc/reflection/v1alpha/reflection.proto
FAILED: gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h gens/src/proto/grpc/reflection/v1alpha/reflection_mock.grpc.pb.h gens/src/proto/grpc/reflection/v1alpha/reflection.pb.cc gens/src/proto/grpc/reflection/v1alpha/reflection.pb.h
cd /home/jmcdevitt/dev/Scratch/grpc && /home/jmcdevitt/dev/Scratch/grpc/debug32/third_party/protobuf/protoc-3.10.0.0 --grpc_out=generate_mock_code=true:/home/jmcdevitt/dev/Scratch/grpc/debug32/gens --cpp_out=/home/jmcdevitt/dev/Scratch/grpc/debug32/gens --plugin=protoc-gen-grpc=/home/jmcdevitt/dev/Scratch/grpc/debug32/grpc_cpp_plugin -I . -I /home/jmcdevitt/dev/Scratch/grpc/third_party/protobuf/src src/proto/grpc/reflection/v1alpha/reflection.proto
/bin/sh: 1: /home/jmcdevitt/dev/Scratch/grpc/debug32/third_party/protobuf/protoc-3.10.0.0: Exec format error

[1517/1531] Running gRPC C++ protocol buffer compiler on src/proto/grpc/channelz/channelz.proto
FAILED: gens/src/proto/grpc/channelz/channelz.grpc.pb.cc gens/src/proto/grpc/channelz/channelz.grpc.pb.h gens/src/proto/grpc/channelz/channelz_mock.grpc.pb.h gens/src/proto/grpc/channelz/channelz.pb.cc gens/src/proto/grpc/channelz/channelz.pb.h
cd /home/jmcdevitt/dev/Scratch/grpc && /home/jmcdevitt/dev/Scratch/grpc/debug32/third_party/protobuf/protoc-3.10.0.0 --grpc_out=generate_mock_code=true:/home/jmcdevitt/dev/Scratch/grpc/debug32/gens --cpp_out=/home/jmcdevitt/dev/Scratch/grpc/debug32/gens --plugin=protoc-gen-grpc=/home/jmcdevitt/dev/Scratch/grpc/debug32/grpc_cpp_plugin -I . -I /home/jmcdevitt/dev/Scratch/grpc/third_party/protobuf/src src/proto/grpc/channelz/channelz.proto
/bin/sh: 1: /home/jmcdevitt/dev/Scratch/grpc/debug32/third_party/protobuf/protoc-3.10.0.0: Exec format error
```

I'm unsure what's wrong. The `file` output for grpc_cpp_plugin and protoc-3.10.0.0 is

```
ELF 32-bit LSB shared object, Intel 80386, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-, for GNU/Linux 3.2.0, BuildID[sha1]=43805e1ce65cebe3f56299f785cefda08e2b547f, not stripped
```

Are there any other things which I may have neglected to add into the CMake command(s)?

## OSX

On OSX we have a different issue. I haven't gotten to the build step yet, but have been trying to generate the correct makefile. My command is:

```
LIBTOOL=glibtool LIBTOOLIZE=glibtoolize cmake .. -DCC=clang -DCXX=clang++ -DARCH_FLAGS="-arch i386" -DPROTOBUF_CPPFLAGS_EXTRA="-arch i386" -DPROTOBUF_LDFLAGS_EXTRA="-arch i386" -DOPENSSL_ROOT_DIR=/Users/jmcdevitt/Desktop/JWM/Scratch/OpenSSL/1.1.0 -DgRPC_SSL_PROVIDER=package -DZLIB_ROOT=/Users/jmcdevitt/Desktop/JWM/Scratch/ZLib/1.2.11 -DgRPC_ZLIB_PROVIDER=package
```

The output seems to indicate that OpenSSL is fine, but not ZLib. We get:

```
-- Found OpenSSL: /Users/jmcdevitt/Desktop/JWM/Scratch/OpenSSL/1.1.0/lib/libcrypto.dylib (found version "1.1.0j")
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.8")
```

Which is quite strange, given that I specified ZLIB_ROOT to be a completely different location. Do you have any input?

Thanks,
~Jon

(Apologies for the double-post, I posted this question on the wrong issue)

**Comment by jtattermusch** [comment] 2019-10-17 12:05
@JonathanMcDevitt   the best what we have in terms of guidance how to build with cmake with gRPC_*_PROVIDER=package are these scripts (the are being continously tested, so we know they work):
installing gRPC on Linux
https://github.com/grpc/grpc/blob/master/test/distrib/cpp/run_distrib_test_cmake.sh

installing gRPC on Windows (this also shows how to use ZLIB_ROOT and OPENSSL_ROOT_DIR to set the location of zlib and openssl, which is something you're trying to do)
https://github.com/grpc/grpc/blob/master/test/distrib/cpp/run_distrib_test_cmake.bat

**Comment by jtattermusch** [comment] 2019-10-17 12:17
@JonathanMcDevitt  could you provide a minimal repro for your issue (e.g a code repository and a script that runs something that fails)? It seems like your setup is pretty complex so it's really hard to guess what could be wrong without knowing the details.

**Comment by jtattermusch** [comment] 2019-10-17 12:19
Just to understand: what is the descriptor it tries to load? Is it one that's part of the protobuf library / is it local in your code  or is it received remote over the wire?

**Comment by acozzette** [comment] 2019-10-17 16:13
@jtattermusch It was failing to parse a protobuf descriptor embedded in the binary via protobuf generated code. My hypothesis is that the root cause might be ODR violations between OpenSSL and BoringSSL, so that is why I suggested trying to get everything using a single SSL library. Using protobuf with dynamically loaded libraries also gets dicey quickly so I think it will help to consolidate the code into a single dylib (which wasn't done before due to the SSL conflicts).

**Comment by JonathanMcDevitt** [comment] 2019-10-18 16:24
Hi @jtattermusch and @acozzette,

Apologies for the wait, I was OOO. Right now we're trying to substitute the OpenSSL and ZLib we build in-house for the BoringSSL and ZLib packages provided by gRPC. We're currently blocked on Linux 32-bit from the above issues, and are exploring possible solutions to the aforementioned Windows issue.

Thanks,
~Jon

**Comment by jtattermusch** [comment] 2019-10-22 06:35
@JonathanMcDevitt  I'm not sure what's wrong with your 32-bit linux build, but I think it's unrelated to grpc itself, you might have missed some cmake options.
We actually do build 32-bit artifacts, but we build them inside a 32bit docker container:
https://github.com/grpc/grpc/blob/master/tools/dockerfile/grpc_artifact_linux_x86/Dockerfile

https://github.com/grpc/grpc/blob/334c826e8c1a7283c822cd3f11cda1dddde734d7/tools/run_tests/artifacts/artifact_targets.py#L367 (for c# native libraries we build using cmake and for protobuf/protoc using cmake as well).

**Comment by jtattermusch** [comment] 2019-10-22 06:44
@JonathanMcDevitt  ok I think I see what's wrong with your 32-bit linux build.
Looks like you're building everything correctly (as far as I can tell), but part of our build is to use the `protoc` and run it to generate .cc files from .proto defintions. Because your build is 32-bit, you've also built your `protoc` as a 32-bit application and of course that fails to run when you try to execute it to generate code as part of the build.
(`protoc-3.10.0.0: Exec format error` = trying to run 32bit binary on x64 linux).

Slightly related thread about using local protoc when crosscompiling (to avoid the same kind of error) https://github.com/grpc/grpc/pull/11795/files

**Comment by acozzette** [comment] 2019-11-21 22:47
@JonathanMcDevitt Have you had any luck getting the build working?

**Comment by kenhsb** [comment] 2019-11-21 23:49
Hey @acozzette,

I'm a colleague of @JonathanMcDevitt's and I have been working on building a statically linked version of the wrapper.

Yes, we recently got it to build on Mac with all the libraries statically linked and the error no longer occurs.

Thanks for your help.

**Comment by jtattermusch** [comment] 2019-12-02 15:10
@kenhsb  thanks for the update. Does that mean that this issue can be closed or there is still soem problem remaining?

**Comment by kevinyokutran** [comment] 2020-02-07 00:22
Hi @jtattermusch, I work with Jon and Ken.  Apologies for the delay, yes you can close this ticket. Thank you for the help.

**Closed** 2020-02-07 07:18 UTC
Labels: c++, customer issue

**Comment by ajay-sabat** [comment] 2021-10-11 13:59
> Building against OpenSSL using cmake should work. we are actually building against OpenSSL in one of our distribtests for window (yes, it's windows, but there's shouldn't be any conceptual difference because it's cmake). See https://github.com/grpc/grpc/blob/a1ad4800da2bb02c843bdaea8fb06518916b6fba/test/distrib/cpp/run_distrib_test_cmake.bat#L57 (after installing OpenSSL into a local directory, which on linux should be possible to do using cmake, you can use that version of OpenSSL by setting `-DOPENSSL_ROOT_DIR=` and `-DgRPC_SSL_PROVIDER=package`.)

We had a slightly different issue, where the application (Freeswitch) used to crash due to two different types of SSL libraries on the system (Freeswitch uses OpenSSL and gRPC uses boringSSL by default). After some research we were able to resolve the issue by disabling boringSSL and use OpenSSL instead through the `-DgRPC_SSL_PROVIDER=package` flag as below.

`cmake -DgRPC_SSL_PROVIDER=OpenSSL . && make && make install`
