### ISSUE TITLE
google-protobuf-3.21.12-x86_64-linux is incompatible with Ruby 3.2.0

### ISSUE THREAD

**Issue by smaboshe** [protocolbuffers/protobuf#11578] opened 2023-01-18 08:55 UTC
**What version of protobuf and what language are you using?**
Version: `google-protobuf-3.21.12-x86_64-linux`
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
Linux (`ubuntu-latest` in a GitHub Action)

**What runtime / compiler are you using (e.g., python version or gcc version)**
I do not know at the moment

**What did you do?**
1. Run a GitHub action that includes installation of the latest `google-protobuf` gem
2. See error

**What did you expect to see**
```
Fetching google-protobuf 3.21.12
Installing google-protobuf 3.21.12 with native extensions
```

**What did you see instead?**
```
google-protobuf-3.21.12-x86_64-linux requires ruby version < 3.2.dev, >= 2.5,
which is incompatible with the current version, 3.2.0
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by casperisfine** [comment] 2023-01-18 10:43
You can fallback to the source version by running `bundle install` with Ruby 3.2. Bundler will notice this incompatibility and remove the precompiled version from the Gemfile.lock.

If you use `dependabot`, you'll need to add `ruby ">= 3.2"` in your `Gemfile` so that it knows to not include incompatible gems either.

**Comment by casperisfine** [comment] 2023-01-18 10:43
A new ruby release would be nice though.

**Comment by mrmason** [comment] 2023-01-18 10:59
Think this is a duplicate of this - https://github.com/protocolbuffers/protobuf/issues/11538

**Comment by smaboshe** [comment] 2023-01-18 19:30
> You can fallback to the source version by running `bundle install` with Ruby 3.2. Bundler will notice this incompatibility and remove the precompiled version from the Gemfile.lock.
> 
> If you use `dependabot`, you'll need to add `ruby ">= 3.2"` in your `Gemfile` so that it knows to not include incompatible gems either.

The fallback suggestion fixes our problem. Happy for you to close this issue.


> Think this is a duplicate of this - #11538

Yes, I believe it is. I did not notice this when searching the issue history.


Thank you all for the help!

**Comment by zhangskz** [comment] 2023-01-19 01:14
Thanks for the community contribution here. Closing this thread as resolved. Note that as pointed out in #11538, this is mitigated in future releases which will only release source gems.

**Closed by zhangskz** 2023-01-19 01:14 UTC
Labels: untriaged

**Comment by johnnyshields** [comment] 2023-01-19 06:06
PR raised for supporting fat binaries on Ruby 3.2: https://github.com/protocolbuffers/protobuf/pull/11592
