### ISSUE TITLE
Google Speech Recognition

### ISSUE THREAD

**Issue by drkorobov** [protocolbuffers/protobuf#6389] opened 2019-07-16 05:37 UTC
After update 3.8.0 to 3.9.0 get error
**Google.Protobuf.FieldCodec`1<Int32> Google.Protobuf.FieldCodec.ForInt32(UInt32)**
 on code
```
Dim streamingCall = speech.StreamingRecognize()
                Await streamingCall.WriteAsync(New StreamingRecognizeRequest() ......
```

**Comment by ObsidianMinor** [comment] 2019-07-16 07:25
Duplicate of #6379

**Closed** 2019-07-17 17:07 UTC
