### ISSUE TITLE
protobuf-lite Java runtime sources?

### ISSUE THREAD

**Issue by ramsestom** [protocolbuffers/protobuf#5937] opened 2019-03-22 03:48 UTC
Hello
I am looking for the sources of the lite version of protobuf java but in the repository I can only see a unique java sources folder that seems to be for the standard protobuf java runtime. So are sources for the lite and standard version merged into the same folder? (I can see class names with the term 'Lite' in their name. Is the lite version built from these?) 
I am asking this because I would like to port the lite version of java protobuf to [codenameone ](https://www.codenameone.com/) (that unfortunatelly do not support the full java API and do not support java reflexion (so the lite version of protobuf would be a good starting point and should be easily adapted with some minor changes I guess) )
Thanks

**Comment by haon4** [comment] 2019-04-03 23:18
Duplicate of #5961

We have a very outdated javalite branch (https://github.com/protocolbuffers/protobuf/tree/javalite) that we would like to get rid of. I am working on releasing a new javalite jar that contains the new runtime without the full Java API, and update documentations on how to use it. To simplify tracking, I will use #5961 to track that progress. Please follow that issue instead. Thanks.

**Closed by haon4** 2019-04-03 23:18 UTC
Labels: java
