### ISSUE TITLE
TextFormat prints out info log which takes lot of CPU

### ISSUE THREAD

**Issue by lavkesh** [protocolbuffers/protobuf#9478] opened 2022-02-08 07:55 UTC
**What version of protobuf and what language are you using?**
Version: 3.17.3
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Running it on GKE. 

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
1. Have a proto with a repeated field of Struct. Struct can have optional fields. 
2. Try to parse bytes into proto.

Example:
```
message  message1{
    google.protobuf.Timestamp event_timestamp = 1;
    repeated message2 list_field = 2; 
}
message message2 {
  string field1 = 1;
  string field2 =2; // Can be empty
}
```

**What did you expect to see**
less cpu utilisation. 

**What did you see instead?**
https://github.com/protocolbuffers/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/TextFormat.java#L502
this line prints out info log, if a struct field is empty. This is take a lot of cpu and the process where a lot of messages needs to parsed is slower than expected. 

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
```
com.google.protobuf.TextFormat$Printer$MapEntryAdapter compareTo
INFO: Invalid key for map field.
```

**Anything else we should know about your project / environment**

**Comment by elharo** [comment] 2022-02-08 18:28
Do you have a reproducible test case?

**Comment by elharo** [comment] 2022-02-08 18:29
I'm particularly interested in whether this branch can be taken without something being very wonky in the data.

**Comment by lavkesh** [comment] 2022-02-09 08:53
> Do you have a reproducible test case?

Do you mean a unit test? I can try creating one.

**Comment by elharo** [comment] 2022-02-09 12:49
A unit test would be good. We need actual code that exercises this code path and causes the log message to be emitted.

**Comment by deannagarcia** [comment] 2022-07-12 19:04
Closing due to no reproduction instructions. Feel free to reopen with more specific reproduction instructions!

**Closed by deannagarcia** 2022-07-12 19:04 UTC
Labels: java, performance, wait for user action
