### ISSUE TITLE
JsonFormatter omits null when Message type

### ISSUE THREAD

**Issue by bjorkstromm** [protocolbuffers/protobuf#9223] opened 2021-11-16 11:40 UTC
**What version of protobuf and what language are you using?**
Version: v3.19.1
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
.NET 6

**What did you do?**
I updated some code that were previously referencing Google.Protobuf 3.9.1 and noticed some changes with regards to formatting JSON. 

Steps to reproduce:

Use following proto:
```proto
syntax = "proto3";

message Foo
{
  message Bar {
    string baz = 1;
  }

  string baz = 1;
  Bar bar = 2;
}
```

Serialize to JSON and print (add `formatDefaultValues: true`):
```csharp
using Google.Protobuf;

var json = new JsonFormatter(
                new JsonFormatter.Settings(formatDefaultValues: true))
                .Format(new Foo());

Console.WriteLine(json);
```

**What did you expect to see**

```
{ "baz": "", "bar": null }
```

as with Google.Protobuf 3.9.1

**What did you see instead?**

```
{ "baz": "" }
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

I'm pretty sure this change changed the behavior.
https://github.com/protocolbuffers/protobuf/pull/7487

Not sure if it was intentional or not. But I'd think when explicitly adding `formatDefaultValues: true`, then message type fields with default value should be serialized as `null`.

**Comment by jskeet** [comment] 2022-07-15 07:53
Firstly, apologies that it's taken so long to respond to this.

Yes, I believe you're right that that PR changed the behavior - and yes, it was a breaking change, which we should have spotted as such. (I noted that it would be a breaking change in a comment, but I suspect there was an internal discussion which isn't included in that comment.) However:

- This is now conformant with an internal specification, which states that the "format default values" switch should only affect fields which don't support presence. That's actually the documented behavior as well (now): "This option only affects fields which don't support "presence" (e.g. singular non-optional proto3 primitive fields).". Message fields *always* support presence as you can tell the difference between `null` and a non-null reference.
- Changing it back now would be *another* breaking change. If we'd only just released the breaking change, it might be worth doing, but even when this issue was first raised, the new behavior had been out for over a year.

I'm going to close this as it's working as intended (and should be consistent with other languages), even though I completely agree it was a breaking change when it was first made.

**Closed by jskeet** 2022-07-15 07:53 UTC
Labels: c#, json

**Comment by MarTeezy** [comment] 2022-10-25 22:29
@jskeet Have you considered adding a new option on the printer to include null values. I do understand your argument of presence, but our customers don't...

**Comment by jskeet** [comment] 2022-10-26 04:18
@MarTeezy: I really don't want to add more options unless they're absolutely necessary, and can be implemented consistently. It would be quite odd to say that it's vital for C# code to be able to produce a value of null, but in other languages it doesn't matter - so this should be argued for *all* languages if at all.
We're working on coming up with a more precise standard for JSON representations, and it's possible that that will include "a consistent set of optional features for formatting/parsing". I definitely wouldn't want to do anything before that is published, but we can at least consider it as *part* of that work.

cc @mcy

**Comment by jamiewinder** [comment] 2025-03-03 13:15
I've just encountered this myself. It's been a while since the last comment, has there been any movement towards correcting this / making it consistent or at least optional.
