### ISSUE TITLE
Link Error since 3.20

### ISSUE THREAD

**Issue by thierryba** [protocolbuffers/protobuf#9975] opened 2022-05-16 10:27 UTC
**What version of protobuf and what language are you using?**
Version: 3.20.1
Language: C++

**What operating system (Linux, Windows, ...) and version?**
MacOS 12

**What runtime / compiler are you using (e.g., python version or gcc version)**
Apple clang version 13.1.6

**What did you do?**
1. build protobuf
2. make a simple example with protobuf
3. link

**What did you expect to see**
I'm expecting the binary to link flawlessly. It does with any version of protibuf up to (and including) 3.19.4.

**What did you see instead?**
Undefined symbols for architecture x86_64:
  "google::protobuf::internal::InternalMetadata::~InternalMetadata()", referenced from:
      google::protobuf::MessageLite::~MessageLite() in libFWProtobuf.a(foo.pb.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by thierryba** [comment] 2022-05-16 10:40
Now that I dug a bit deeper into protobuf code, the problem is quite simple.
google::protobuf::internal::InternalMetadata::~InternalMetadata() is defined depending on the NDEBUG macro.
So if you build the lib for Release (like I did) and build your app for debug (default), it fails.

**Comment by elharo** [comment] 2022-05-16 11:25
Dupe of #9947 though thanks for filing. I'll see what we can do about this.

**Closed by elharo** 2022-05-16 11:25 UTC
Labels: duplicate

**Comment by tusharb86** [comment] 2022-05-25 19:29
Thinking about it more... this may be due to our team/project's toolchain and a missing definition of NDEBUG. I'll dig deeper to ensure that is setup properly. Sorry for the noise!
