### ISSUE TITLE
Support Apple Silicon

### ISSUE THREAD

**Issue by nohe427** [protocolbuffers/protobuf#8550] opened 2021-05-01 18:24 UTC
**What language does this apply to?** All

**Describe the problem you are trying to solve.**
I want to install protoc on Apple Silicon.

**Describe the solution you'd like**
A protoc that is installable on Apple Silicon

**Describe alternatives you've considered**
Running under Rosetta 2

**Additional context**
None at this time.

**Comment by fowles** [comment] 2021-05-03 21:48
Duplicate of #8428

**Closed by fowles** 2021-05-03 21:48 UTC
Labels: duplicate
