### ISSUE TITLE
[protobuf-go] An option to marshal proto3 int64/uint64/fixed64/sfixed64 to JSON number, not to JSON string

### ISSUE THREAD

**Issue by ono-kohei-1263** [protocolbuffers/protobuf#12400] opened 2023-04-04 07:09 UTC
**What language does this apply to?**
proto3/golang

**Describe the problem you are trying to solve.**
When marshaling proto3 messages to JSON with `protojson.Marshal`, I would like to transfer proto3 int64/uint64/fixed64/sfixed64 values to JSON numbers, not to JSON strings.

**Describe the solution you'd like**
 Is it acceptable to add an option into `protojson.MarshalOptions` to make proto3 int64/uint64/fixed64/sfixed64 values be transferred to JSON numbers?

**Describe alternatives you've considered**
Without using `protojson.MarshalOptions`, I tried to recursively parse protobuf messages and manually transfer to JSON strings, which seems to need handling all kinds of protobuf types and cause complicated implementation.

**Comment by puellanivis** [comment] 2023-04-05 20:03
I’m afraid I might have sent you bad info. This looks to be a duplicate of https://github.com/protocolbuffers/protobuf/issues/8331

**Comment by ono-kohei-1263** [comment] 2023-04-06 01:15
@puellanivis 
Thanks!

**Closed** 2023-04-06 01:15 UTC
Labels: untriaged
