### ISSUE TITLE
ByteSizeConsistencyError when serializing a partial MapEntry

### ISSUE THREAD

**Issue by ryancahoon-zoox** [protocolbuffers/protobuf#7399] opened 2020-04-18 04:34 UTC
**What version of protobuf and what language are you using?**
Version: master
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux 4.4.0-97-generic
Ubuntu 14.04.6 LTS

**What runtime / compiler are you using (e.g., python version or gcc version)**
g++ 4.8.5-4ubuntu8~14.04.2

**What did you do?**
```cpp
TEST(MapSerializationTest, SerializePartialMapEntry) {
  unittest::TestMap source;

  const Reflection *reflection = source.GetReflection();
  const FieldDescriptor *map_field_descriptor =
      source.GetDescriptor()->FindFieldByName("map_int32_int32");
  const FieldDescriptor *key_field_descriptor =
      map_field_descriptor->message_type()->FindFieldByName("key");

  Message *source_map_entry =
      reflection->AddMessage(&source, map_field_descriptor);
  Message *dest_map_entry =
      reflection->AddMessage(&source, map_field_descriptor);

  source_map_entry->GetReflection()->SetInt32(source_map_entry,
                                              key_field_descriptor, 42);

  std::string data;
  io::StringOutputStream str_stream(&data);
  io::CodedOutputStream coded_stream(&str_stream);

  ASSERT_TRUE(source_map_entry->SerializeToCodedStream(&coded_stream));
  EXPECT_TRUE(dest_map_entry->ParseFromString(data));

  EXPECT_TRUE(
      util::MessageDifferencer::Equals(*source_map_entry, *dest_map_entry));
}
```

**What did you expect to see**
Test passes

**What did you see instead?**
```
[ RUN      ] MapSerializationTest.SerializePartialMapEntry
[libprotobuf FATAL google/protobuf/message_lite.cc:87] CHECK failed: (bytes_produced_by_serialization) == (byte_size_before_serialization): Byte size calculation and serialization were inconsistent.  This may indicate a bug in protocol buffers or it may be caused by concurrent modification of .
unknown file: Failure
C++ exception with description "CHECK failed: (bytes_produced_by_serialization) == (byte_size_before_serialization): Byte size calculation and serialization were inconsistent.  This may indicate a bug in protocol buffers or it may be caused by concurrent modification of ." thrown in the test body.
[  FAILED  ] MapSerializationTest.SerializePartialMapEntry (1 ms)
```

The issue seems to be that `MapEntryImpl::_InternalSerialize` doesn't respect `has_key()` and `has_value()` https://github.com/protocolbuffers/protobuf/blob/2c8364bcd199f4ce98892be10cafd7d3e537c0eb/src/google/protobuf/map_entry_lite.h#L279-L283
but `MapEntryImpl::ByteSizeLong` does https://github.com/protocolbuffers/protobuf/blob/2c8364bcd199f4ce98892be10cafd7d3e537c0eb/src/google/protobuf/map_entry_lite.h#L267-L277

**Anything else we should know about your project / environment**
None

**Comment by ssiano** [comment] 2021-02-04 06:19
The test case provided by @ryancahoon-zoox is still failing for Protobuf 3.12 in the way he shows above.

For Protobuf 3.13 and above, it is still failing, but in a different way

```[ RUN      ] MapSerializationTest.Deterministic
[       OK ] MapSerializationTest.Deterministic (15 ms)
[ RUN      ] MapSerializationTest.DeterministicSubmessage
[       OK ] MapSerializationTest.DeterministicSubmessage (42 ms)
[ RUN      ] MapSerializationTest.SerializePartialMapEntry
src/google/protobuf/map_test.cc:3364: Failure
Value of: dest_map_entry->ParseFromString(data)
  Actual: false
Expected: true
[  FAILED  ] MapSerializationTest.SerializePartialMapEntry (0 ms)
[----------] 3 tests from MapSerializationTest (57 ms total)
```

The improvement may be related to has_key() and has_value() being removed from ByteSizeLong() in Commit f77065d, as can be seen at https://github.com/protocolbuffers/protobuf/blob/3.13.x/src/google/protobuf/map_entry_lite.h#L267-L272.

**Comment by deannagarcia** [comment] 2022-07-26 22:54
Sorry for the long response. I'm closing this since the initial failure was fixed. I think the new error might be working as intended since `data` was never initialized.

If I'm missing something and there's still an error, feel free to reopen.

**Closed by deannagarcia** 2022-07-26 22:54 UTC
Labels: bug, c++
