### ISSUE TITLE
PHP extension crashes when "keep_descriptor_pool_after_request" option is enabled

### ISSUE THREAD

**Issue by hakimio** [protocolbuffers/protobuf#9215] opened 2021-11-12 08:27 UTC
**What version of protobuf and what language are you using?**
Version: v3.19.1
Language: PHP v7.4

**What operating system and version?**
Windows 10

**What runtime / compiler are you using**
NTS Visual C++ 2017 x64 (VC15)

**What did you do?**
1. Enable `keep_descriptor_pool_after_request` option
2. Call some route which uses protobuf
3. Call the route a second time

**What did you expect to see**
No crash.

**What did you see instead?**
The PHP extension is crashing/segfaulting

**Anything else we should know about your project / environment**
PHP Extension Build: NTS, VC15
Http server: NGINX with php-cgi

@haberman @TeBoring 

**EDIT:** attached compiled extension.
[protobuf_x64_vc15_php7.4_nts.zip](https://github.com/protocolbuffers/protobuf/files/7525950/protobuf_x64_vc15_php7.4_nts.zip)

**Comment by MrMage** [comment] 2021-12-14 14:37
FYI, I am also encountering crashes when `keep_descriptor_pool_after_request` is set to 1 in two cases:

- after running all my tests on Google Cloud Build. The tests themselves pass, but `php` exits with a segmentation fault _after_ PHPUnit has reported success.
- randomly in production

**Comment by MrMage** [comment] 2021-12-15 09:24
I just found https://github.com/protocolbuffers/protobuf/commit/759a53973690140d0dfae614b6bd190dcbad787f, which might fix this. But it seems like this is not available in any protobuf release yet.

**Comment by hakimio** [comment] 2021-12-15 09:28
@MrMage it's part of `v3.19.1` release.

**Comment by MrMage** [comment] 2021-12-15 10:08
@hakimio thanks for pointing that out! I must have misread the date of the commit. Then this issue seems to be not fixed, yet.

**Comment by MrMage** [comment] 2022-06-06 11:24
FYI, this _might_ have been fixed in #9995. I'll keep monitoring to see if I still see this error with protobuf 3.21.1 installed, and if yes, post an update here. But this can likely be closed.

**Comment by haberman** [comment] 2022-09-01 19:40
Can you create a self-contained repro? These kinds of bugs are really hard to fix at a distance unfortunately.

**Closed** 2023-02-27 23:24 UTC
Labels: bug, php

**Comment by simonberger** [comment] 2024-05-17 16:14
Were there any new insights or had this been closed due to inactivity?

I have this error as well after executing unit tests with codeception.

PHP 8.3 and protobuf extension 3.25.3.

**Comment by haberman** [comment] 2024-05-17 16:29
It was closed due to inactivity and lack of a repro.

If you can reproduce this issue reliably, please feel free to create a new bug report.

**Comment by simonberger** [comment] 2024-06-13 09:09
There is a new issue with a simple reproducer and a PR with a fix. Unfortunately both without any reaction yet.
I expect most of you reported the issue here moved forward without the option. If you are still interested in having this fixed you could have a look at the issue #16894
Maybe you are even willing to try out the likely fix https://github.com/protocolbuffers/protobuf/pull/16993 which would be great.
