### ISSUE TITLE
Python: segfault when accessing a field that its type is a nested message

### ISSUE THREAD

**Issue by oridag** [protocolbuffers/protobuf#12047] opened 2023-02-24 08:33 UTC
Version: 4.21.12
Language: Python

Only managed to reproduce in a docker container, on both arm64 and amd64
Python 3.10

When using a dynamically loaded descriptors (without code gen), accessing a field that its type is a nested message can segfault if the nested message isn't explicitly accessed first. Below is an illustration of the setup that causes the segmentation fault, although I couldn't reproduce with this specific program, probably because occurrence is sensitive to memory layout.
Note that uncommenting the commented out line seems to resolve the issue.

```python
    fdp = FileDescriptorProto(
        name="f.proto",
        package="some.package",
        message_type=[
            DescriptorProto(
                name="ProtoMessage",
                nested_type=[
                    DescriptorProto(
                        name="NestedMessage",
                        field=[
                            FieldDescriptorProto(name="a_text_field", number=1, type=FieldDescriptorProto.TYPE_STRING)
                        ]
                    )
                ],
                field=[FieldDescriptorProto(name="msg_field", number=1, type=FieldDescriptorProto.TYPE_MESSAGE, type_name="NestedMessage")]
            )
        ]
    )

    mf = MessageFactory()
    mf.pool.Add(fdp)
    msgs = mf.GetMessages([fdp.name])
    ProtoMessage = msgs["some.package.ProtoMessage"]
    # nested_msg_class = ProtoMessage.NestedMessage
    msg = ProtoMessage()
    print(msg.msg_field)

```

I couldn't capture a core dump, sorry.

**Comment by acozzette** [comment] 2023-02-24 18:41
Thank you for the bug report. Can you reproduce it with 4.22.0?

**Comment by oridag** [comment] 2023-02-24 22:27
Yes, it reproduces with 4.22.0. In fact, it's even worse. 4.22.0 has a different, probably unrelated bug, where when accessing an inner type it sometimes throws an AttributeError, so there's no mitigation to this bug. I couldn't pin point exactly when it happens, but for a given descriptor and a given nested type in that descriptor, it happens consistently.

**Comment by haberman** [comment] 2023-02-27 19:23
I have a theory about what is going on. To help confirm or deny this theory, could you try the following inside the Docker container where this error occurs?

```
$ python
>>> import google.protobuf.pyext._message
>>> import google._upb._message
```

My theory is that, in the Docker container where the crash occurs, both of these imports will succeed. In the cases where you can't reproduce the crash, I predict that only the second import will succeed.

**Comment by oridag** [comment] 2023-02-27 20:57
Sorry, the first import never succeeds, even in a container where I can reproduce

**Comment by haberman** [comment] 2023-02-27 22:32
Hmm, that's too bad. In that case I don't have any hunches, and without a repro it's going to be hard to make progress.

Any chance you can get us a repro?

**Comment by oridag** [comment] 2023-02-28 11:23
No, sorry. I wasn't able to construct a minimal repro I can share

**Comment by nmariz** [comment] 2023-05-16 19:10
We are having a similar situation in [Connector/Python](https://github.com/mysql/mysql-connector-python). We are upgrading the proto stubs to work with Protobuf 4, but raises a segmentation fault if Protobuf version is > 4.21.12, so using 4.22.x or the latest 4.23.0.
It's very hard to produce a reproducible code, since it happens when running our test suite and it's also not deterministic.

**Comment by haberman** [comment] 2023-05-16 19:18
Hi @nmariz, how many of the details in your case match the original bug report?

In the original report:

1. This issue is said to affect only dynamically loaded types that use `MessageFactory(). GetMessages()`, not generated types.
2. This issue is said to affect a nested message (`some.package.ProtoMessage.NestedMessage`).
3. The issue goes away if the nested message class is explicitly referenced first.

How many of those details match your case?

**Comment by gabe-l-hart** [comment] 2023-05-25 21:00
I'm seeing a very similar problem with a slightly different setup. I don't _quite_ have a concise repro yet, but thought it would be worth sharing my investigation in case it helps.

## Environment Details

* Python Environment: `conda` environment with 3.8.16
    * We've seen it against `3.9` and `3.10` as well in Github Actions
* Protobuf Version: `4.23.1`
* Architecture: Running natively on an M1 (arm) Mac
    * I _believe_ the GH Actions workers where we also saw it are x86, so I don't _think_ it's architecture specific

In order to get the segfault to trigger consistently, I slapped (`@pytest.mark.parametrize("run_num", range(100))`) on my offending unit test. With 100 runs, it reliably triggered at _some_ point, but running the test a single time usually did not trigger the fault.

## Setup Details

We're using custom `DescriptorPool` objects in unit tests in order to isolate some dynamic message generation and avoid name collisions. The main difference between our usecase and the OP is that rather than a submessage, we're using a standard message (`struct_pb2.Struct`) that gets copied over to the temporary pool.

The `pytest` fixture looks like this:

```py
@pytest.fixture(autouse=True)
def temp_dpool():
    """Fixture to isolate the descriptor pool used in each test"""
    dpool = descriptor_pool.DescriptorPool()
    global_dpool = descriptor_pool._DEFAULT
    descriptor_pool._DEFAULT = dpool
    fd = descriptor_pb2.FileDescriptorProto()
    struct_pb2.DESCRIPTOR.CopyToProto(fd)
    dpool.Add(fd)
    yield dpool
    # pylint: disable=duplicate-code
    descriptor_pool._DEFAULT = global_dpool
```

If I add the following lines before `yield dpool`, the segfault goes away (very similar to OP's commented line)

```py
    mf = MessageFactory(dpool)
    msgs = mf.GetMessages([fd.name])
    _ = msgs["google.protobuf.Struct"]
    _ = msgs["google.protobuf.Value"]
    _ = msgs["google.protobuf.ListValue"]
```

The dynamically generated message that triggers the segfault has a descriptor that looks like:

```
name: "Foo"
field {
  name: "js_dict"
  number: 1
  label: LABEL_OPTIONAL
  type: TYPE_MESSAGE
  type_name: ".google.protobuf.Struct"
}
```

The segfault is triggered when performing a `Foo.js_dict` (`getattr`).

## Investigation Details

In trying to get to the bottom of this, I started poking around in `upb`'s C implementation. This lead to [the implementation of `PyUpb_Message_NewStub`](https://github.com/protocolbuffers/upb/blob/main/python/message.c#L543). Specifically, the call to `PyUpb_Descriptor_GetClass` is returning `NULL`, causing the subsequent line (`(void*)PyType_GenericAlloc((PyTypeObject*)cls, 0)`) to segfault.

What I have yet to figure out is _why_ that class lookup fails. Given the workaround fix suggested by the post and the comments [here](https://github.com/protocolbuffers/upb/blob/main/python/message.c#L186) related to the recursively triggered "present" / "non-present" state of the concrete class, my gut feeling is that somehow the fact that `Struct` is "copied" to the temporary pool can trigger a logic bug where the recursive presence setup doesn't trigger correctly.

**Comment by gabe-l-hart** [comment] 2023-06-01 16:01
Some additional information that _might_ help track down the issue: The current workaround I'm using in our tests looks like the following:

```py
@pytest.fixture(autouse=True)
def temp_dpool():
    """Fixture to isolate the descriptor pool used in each test"""
    dpool = descriptor_pool.DescriptorPool()
    global_dpool = descriptor_pool._DEFAULT
    descriptor_pool._DEFAULT = dpool
    fd = descriptor_pb2.FileDescriptorProto()
    struct_pb2.DESCRIPTOR.CopyToProto(fd)
    dpool.Add(fd)
    # WORKAROUND
    mf = MessageFactory(dpool)
    msgs = mf.GetMessages([fd.name])
    _ = msgs["google.protobuf.Struct"]
    _ = msgs["google.protobuf.Value"]
    _ = msgs["google.protobuf.ListValue"]
    yield dpool
    descriptor_pool._DEFAULT = global_dpool
```

If I scoop the workaround out of the body of this `fixture` and put it in a standalone function, the segfault returns somewhat-reliably. I say "somewhat" because even with 500x repeats on the offending test, I can only still only rarely get it to repeat on my laptop (M1 Mac), but it somehow seems to trigger very reliably in GitHub Actions (see [these runs](https://github.com/caikit/caikit/actions/runs/5146459517))

```py
def proto_segfault_workaround(fd, dpool):
    mf = MessageFactory(dpool)
    msgs = mf.GetMessages([fd.name])
    _ = msgs["google.protobuf.Struct"]
    _ = msgs["google.protobuf.Value"]
    _ = msgs["google.protobuf.ListValue"]

@pytest.fixture(autouse=True)
def temp_dpool():
    """Fixture to isolate the descriptor pool used in each test"""
    dpool = descriptor_pool.DescriptorPool()
    global_dpool = descriptor_pool._DEFAULT
    descriptor_pool._DEFAULT = dpool
    fd = descriptor_pb2.FileDescriptorProto()
    struct_pb2.DESCRIPTOR.CopyToProto(fd)
    dpool.Add(fd)
    # WORKAROUND
    proto_segfault_workaround(fd, dpool)
    yield dpool
    descriptor_pool._DEFAULT = global_dpool
```

**Comment by anandolee** [comment] 2023-06-16 01:14
I can't reproduce the error.

We are sorry Ori and Gabe, but without a repro it is really hard for us to make progress. 
Will close this issue as can't repo. Feel free to reopen when there is a repro ready.

**Comment by gabe-l-hart** [comment] 2023-06-16 03:19
No problem @anandolee, thanks for investigating. I felt like I was on the right track while poking around, so I'll try to see if I can get back to it at some point. The workaround here seems reliable and it's admittedly an extreme corner case in our tests!

**Comment by achim-k** [comment] 2023-07-05 19:56
We are also running into this when reading a MCAP file using `mcap-protobuf-support` which [dynamically loads types](https://github.com/foxglove/mcap/blob/db7675fedc1c2da9d1b9e3a58efc7074a43dfdcd/python/mcap-protobuf-support/mcap_protobuf/decoder.py#L65-L83) from the MCAP file.

```py
from mcap_protobuf.reader import read_protobuf_messages


def main():
    topics = ["topic_4"]
    for msg in read_protobuf_messages(sys.argv[1], topics=topics):
        print(msg.proto_msg.header.seq)  # Causes a segfault after the 354th message (3900+ msgs in total)
```

The good thing is, that I can reliably reproduce this with [this MCAP file](https://drive.google.com/file/d/18SX2LrH-gs4lsV2jxR1GLn0wSS5xf5lL/view?usp=drive_link). For easier reproduction, I have created a Dockerfile that installs all necessary dependencies and downloads the MCAP file: https://gist.github.com/achim-k/1a89f808bc052c83f225f19215ced930

Download the gist as zip, extract it and then build and run the docker image like so:
```bash
docker build -t protobuf_segfault .
docker run -it protobuf_segfault
```

**Comment by jtbandes** [comment] 2023-09-20 17:29
Hi @anandolee @haberman – is there any chance that someone would be able to look into this segfault now that a reliable repro has been shared at https://github.com/protocolbuffers/protobuf/issues/12047#issuecomment-1622405787? Thanks 🙏 💐

**Comment by gvashishtha** [comment] 2023-09-23 01:55
@haberman thanks for the fix! When do you expect the next release?

**Comment by jtbandes** [comment] 2023-10-05 01:41
I see that a "24.4" release has gone out, but it doesn't appear to include https://github.com/protocolbuffers/protobuf/commit/b1c4c65658c9f116ad804610c191371f92b9e318.

**Comment by haberman** [comment] 2023-10-09 19:37
Sorry this missed 24.4. This will go out in 25.0, which will be coming in the next few weeks.

**Comment by jtbandes** [comment] 2023-10-09 19:51
Thank you!
Any chance of backporting a fix? It would be great to get a fix for this segfault released for earlier major versions as well.

**Comment by jtbandes** [comment] 2024-01-08 18:33
It would still be nice to get the fix backported if possible :)

**Closed** 2024-02-01 18:20 UTC
Labels: bug, python, 22.x
