### ISSUE TITLE
[ PHP - Internal\Message ] serializeToJsonString() syntax error

### ISSUE THREAD

**Issue by OussamaElgoumri** [protocolbuffers/protobuf#4740] opened 2018-06-07 16:35 UTC
i'am using dialogflow v2 api

when i serialize the `DetectIntentResponse` to json it return an invalid json, 

`{"queryText":"today's weather","languageCode":"en","parameters":{"date":"","geo-city":""},"allRequiredParamsPresent":true,"fulfillmentText":"Sorry I don't know the weather","fulfillmentMessages":[{"text":{"text":["Sorry I don't know the weather"]}}],"intent":{"name":"projects\/kwerio-308a7\/agent\/intents\/3447dea7-95f3-41db-b694-e4268a71dad1","displayName":"weather"},"intentDetectionConfidence":1,"diagnosticInfo":}`

**Comment by TeBoring** [comment] 2018-06-28 07:04
Which implementation are you using? php or c extension?
Do you have code to reproduce?

**Comment by OussamaElgoumri** [comment] 2018-07-03 14:59
i'am using php package and google dialogflow library

```
            return new SessionsResponse(
                $this->sessionsClient->detectIntent($this->session_name, $queryInput)
            );
```

and this is the `SessionsResponse` class

```php

    /**
     * SessionsResponse constructor.
     * @param DetectIntentResponse $response
     */
    public function __construct(DetectIntentResponse $response)
    {
        $this->response = $response;
        $this->queryResult = $response->getQueryResult();
    }

    /* snip */

        /**
     * [ BUG ] https://github.com/google/protobuf/issues?utf8=%E2%9C%93&q=is%3Aissue+serializeToJsonString
     *
     * @return string
     */
    public function toJson()
    {
        return $this->queryResult->serializeToJsonString();
    }

```

**Comment by TeBoring** [comment] 2019-01-22 07:30
By reading your data, it seems not a valid json. The last "diagnosticInfo" has no value.
Close it now because I think the invalid data caused the problem. Feel free to reopen if you think there is a different cause.

**Closed by TeBoring** 2019-01-22 07:30 UTC
Labels: P2, bug, php, wait for user action
