### ISSUE TITLE
C++ JSON parser incorrectly accepts lowercase enum value names.

### ISSUE THREAD

**Issue by xfxyjwf** [protocolbuffers/protobuf#5059] opened 2018-08-17 18:37 UTC
Given this proto definition:
```
enum Category {
    NOT_SPECIFIED = 0;
    LISTINGS = 1;
    REPUTATION = 2;
}
```
The C++ JSON parser should only accept "LISTINGS" as enum field values, but right now it accepts "listings" (converted to lower-case) as well.

For enum fields, proto3 JSON spec says "The name of the enum value as specified in proto is used":
https://developers.google.com/protocol-buffers/docs/proto3#json

"as specified in proto" should be interpreted as "the exactly same name including casing as specified in proto".

**Comment by xfxyjwf** [comment] 2018-08-17 19:26
Apparently C++ JSON parser not only accepts lower-case enum value names, but actually accepts arbitrary casing like "Listings" or "LiStInGs"...

**Comment by xfxyjwf** [comment] 2018-08-17 19:30
Well, that only works if the enum name is defined all upper case. If the enum is defined as:
```
enum Category {
    NotSpecified = 0;
    Listings = 1;
    Reputation = 2;
}
```
Neither "listings" nor "LISTINGS" will be accepted... With the above definition, only "Listings" works.

**Comment by mcy** [comment] 2022-09-01 18:19
It is intended behavior that case matching is insensitive if requested. That said, support for this in the current parser is a bit broken. I have a new implementation of the JSON codec that will ship in our next major release that fixes this. Closing as "done", since it's simply a matter of waiting for the release for this to be fixed.

**Closed by mcy** 2022-09-01 18:19 UTC
Labels: bug, c++, json
