### ISSUE TITLE
Undefined `__android_log_write` on NDK builds

### ISSUE THREAD

**Issue by swansontec** [protocolbuffers/protobuf#2719] opened 2017-02-15 01:35 UTC
When I build Protocol Buffers 3.2.0 using the NDK, I get the following linker error:

```
libtool: link: arm-linux-androideabi-clang++ -std=c++11 -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -isystem/Users/william/tmp/build/prefix/android/arm/include -fPIC -O2 -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -fPIC -march=armv7-a -Wl,--fix-cortex-a8 -o protoc google/protobuf/compiler/main.o  -L/Users/william/tmp/build/prefix/android/arm/lib ./.libs/libprotobuf.a ./.libs/libprotoc.a /Users/william/tmp/build/protobuf/android-arm/protobuf-3.2.0/src/.libs/libprotobuf.a -lz
/Users/william/tmp/build/protobuf/android-arm/protobuf-3.2.0/src/.libs/libprotobuf.a(common.o):google/protobuf/stubs/common.cc:function google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&): error: undefined reference to '__android_log_write'
/Users/william/tmp/build/protobuf/android-arm/protobuf-3.2.0/src/.libs/libprotobuf.a(common.o):google/protobuf/stubs/common.cc:function google::protobuf::internal::DefaultLogHandler(google::protobuf::LogLevel, char const*, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&): error: undefined reference to '__android_log_write'
```

There were no errors on 3.1.0 with an identical build setup.

## Workaround
The problem is that `-llog` needs to be passed to the linker to make the `__android_log_write` function available. By temporarily defining `LDFLAGS="-llog"` before running configure, I can work around the problem. The Protocol Buffers configure script should be doing this automatically.

## Build setup
I have extracted a standalone toolchain from the NDK, and have pointed my environment variables at the NDK-provided tools (`CC`, `CCLD`, `CPP`, `CXX`, `LD`, `AR`, `AS`, `NM`, `OBJCOPY`, `OBJDUMP`, `RANLIB`, `STRINGS`, `STRIP`). I run the standard build steps:

    # Required by the NDK
    export CFLAGS="-march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb"
    export CXXFLAGS="-march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb"
    export LDFLAGS="-march=armv7-a -Wl,--fix-cortex-a8"

    # Normal build steps
    autoreconf -i
    ./configure --enable-static --disable-shared --host=arm-linux-androideabi --with-protoc=protoc
    make

The error occurs when running make.

**Comment by xfxyjwf** [comment] 2017-03-06 23:55
I'm not sure if using autoconf is the right way to build for Android. Before that's officially supported as part of our release build, we will need help from users to make the config file work for Android. Could you help contribute a pull request for it?

**Comment by 4ntoine** [comment] 2017-03-27 08:35
i can confirm this issue on 3.2.0 and workaround working

**Comment by pkubik** [comment] 2020-01-07 17:15
Issue occurs for CMake version too. Configured with:
```
cmake ../cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DANDROID_ABI="arm64-v8a" -DANDROID_NATIVE_API_LEVEL=android-21
```

**Comment by pthom** [comment] 2020-05-07 17:44
I could solve it for cmake with the following patch (based on v3.11.4)

````diff
diff --git a/cmake/CMakeLists.txt b/cmake/CMakeLists.txt
index 8e5e68073..540445a77 100644
--- a/cmake/CMakeLists.txt
+++ b/cmake/CMakeLists.txt
@@ -211,7 +211,6 @@ if (MSVC)
   configure_file(version.rc.in ${CMAKE_CURRENT_BINARY_DIR}/version.rc @ONLY)
 endif (MSVC)
 
-
 get_filename_component(protobuf_source_dir ${protobuf_SOURCE_DIR} PATH)
 
 include_directories(
@@ -228,6 +227,11 @@ else (MSVC)
   set(LIB_PREFIX)
 endif (MSVC)
 
+if (ANDROID)
+    # __android_log_write is required for android
+    link_libraries(log)
+endif(ANDROID)
+
 if (protobuf_UNICODE)
   add_definitions(-DUNICODE -D_UNICODE)
 endif (protobuf_UNICODE)

````


I don't know if I will submit a PR for this, since I am quite inexperience in protobuf, and I did the bare minimum to make it work: I suspect some more checks would be needed.

**Comment by PetrJarosik** [comment] 2020-10-13 06:53
Merge changes made in #7288 please, the protobuf is not buildable for Android target without this fix!

**Comment by s1341** [comment] 2021-02-11 08:53
#8285 fixes this

**Comment by elharo** [comment] 2022-01-28 14:06
Believe this is fixed now. Comment if it reoccurs.

**Closed by elharo** 2022-01-28 14:06 UTC
Labels: enhancement, help wanted, c++, android, P3
