### ISSUE TITLE
[PHP] Wrong behavior of GPBUtil::checkUint32 and GPBUtil::checkInt32 ?

### ISSUE THREAD

**Issue by yplam** [protocolbuffers/protobuf#5101] opened 2018-08-31 10:30 UTC
Version: v3.6.1
Language:PHP
OS: Linux 64 bit

**Test Code**
```
$val_uint32 = 2147483648;
GPBUtil::checkUint32($val_uint32);
var_dump($val_uint32);
$val_int32 = 2147483648;
GPBUtil::checkInt32($val_int32);
var_dump($val_int32);
```

**What did you expect to see**
int(2147483648)
int(-2147483648)

**What did you see instead?**
int(-2147483648)
int(2147483648)

**Comment by TeBoring** [comment] 2018-09-03 18:30
GPBUtil is a internal method. I think you should avoid using that.

**Comment by yplam** [comment] 2018-09-03 22:32
Hi TeBoring, I am not  using GPBUtil. The reason I wrote the test code is to show the bug of GPBUtil.

The maximum value for UInt32 is 0xFFFFFFFF (or 4294967295 in decimal), but GPBUtil::checkUint32 method turns value  bigger than 2147483647 into a negative number，that's what GPBUtil::checkInt32 should do.

**Comment by TeBoring** [comment] 2018-09-03 22:35
This behavior is actually intentional. This makes the result for both 64-bit and 32-bit machines the same.

**Comment by yplam** [comment] 2018-09-04 02:09
My C client send a uint32 value of 2147483648 but my PHP server get a -2147483648, that's weird.

2147483648 is in the range of uint32, but  GPBUtil::checkUint32 make it act as int32.

uint32 in protobuf means 4 bytes unsigned int, right?

**Comment by yplam** [comment] 2018-09-04 02:40
Some quick test:

1. php client send uint32 2147483648, C server receive 2147483648
2. php client send fixed32 2147483648, C server reveive 2147483648
3. C client send uint32 2147483648, php server receive -2147483648
4. C client send fixed32 2147483648, php server receive 0

**Comment by yplam** [comment] 2018-09-04 02:55
Another test:

```
syntax = "proto3";

message  MyMessage {
  uint32 uuid = 1;
}
```

```
$message = new \MyMessage();
$message->setUuid(2147483648);
var_dump($message->getUuid());
$data = $message->serializeToString();
$toMessage = new \MyMessage();
$toMessage->mergeFromString($data);
var_dump($toMessage->getUuid());
```

output:
```
int(-2147483648)
int(-2147483648)
```

**Comment by TeBoring** [comment] 2018-09-04 03:42
How php represent uint32 doesn’t affect the data on wire and also doesn’t
affect what c client receives.
Besides, each language has the freedom to choose integer representation.
e.g., Java use signed integer to represent unsigned integer.

**Comment by TeBoring** [comment] 2018-09-04 03:45
In your tests, only the result for 4 seems incorrect to me. I need to
double check.

**Comment by DrSat** [comment] 2022-04-06 16:22
It seems the bug still present: checkUint32 doesn't cut off values longer than 4 bytes and works wrong for values greater than 0x0FFFFFFF as described earlier.
Does anyone know about progress on this issue?

**Comment by deannagarcia** [comment] 2022-09-01 18:08
Duplicate of https://github.com/protocolbuffers/protobuf/issues/10335, progress will be there so closing this.

**Closed by deannagarcia** 2022-09-01 18:08 UTC
Labels: bug, php
