### ISSUE TITLE
Java generated code collision with field named descriptor

### ISSUE THREAD

**Issue by bufdev** [protocolbuffers/protobuf#5742] opened 2019-02-16 19:29 UTC
Java cannot handle when a field is named `descriptor`, for example:

```
message Foo {
  int64 descriptor = 1;
}
```

Edit: Note that capitalizing `Descriptor` causes this problem, as well as any number of leader or trailing `_`s.

```
Descriptor
 _descriptor
descriptor_
__descriptor
descriptor__
...
```

This will result in bad generated code. The `protoc` compiler should handle this collision.

Note that C++ has a similar problem if a package has `std` as part of it, for example `foo.std.bar`. I could file another bug for this with reproduction steps if it helps.

Fixing this could result in some very big breaking changes. It might be enough for things like this to outlaw certain names. We do this at lint time using our Protobuf linter, but given that the cpp, java, etc plugins are builtin to `protoc`, it feels like these should be outlawed via `protoc`.

**What version of protobuf and what language are you using?**

Version: 3.6.1.3
Language: Java

**What operating system (Linux, Windows, ...) and version?**

Mac, but using Bazel for this reproduction.

**What runtime / compiler are you using (e.g., python version or gcc version)**

Bazel 0.22.0 default settings

**What did you do?**

I've copied reproduction steps to https://github.com/uber/prototool/tree/protobuf-bug/protobuf-bug to make this easy to diagnose. The above Makefile installs a a local (to the directory) copy of Bazel 0.22.0, and attempts to build the code. **Note this is not a Bazel bug, this is clearly a Protocol Buffers bug, I just use Bazel here for ease of reproduction**

Edit: Also note that I have the option `java_multiple_files, java_outer_classname, java_package` set in that example. The above error happens regardless of if those are set or not.

```
git clone https://github.com/uber/prototool
cd prototool
git checkout protobuf-bug
cd protobuf-bug
make
```

**What did you expect to see**

No errors

**What did you see instead?**

```
$ make
/Users/pedge/git/prototool/protobuf-bug/.tmp/Darwin/x86_64/bazel-0.22.0/bin/bazel build //...:all
Starting local Bazel server and connecting to it...
INFO: Invocation ID: f14df5cc-c65a-4ed6-bf9e-d654d6b242db
INFO: Analysed 3 targets (15 packages loaded, 969 targets configured).
INFO: Found 3 targets...
ERROR: /Users/pedge/git/prototool/protobuf-bug/foo/BUILD.bazel:13:1: Building foo/libfoo_proto-speed.jar (1 source jar) failed (Exit 1)
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
/com/foo/Bar.java:88: error: method getDescriptor() is already defined in class Bar
  public long getDescriptor() {
              ^
/com/foo/Bar.java:400: error: method getDescriptor() is already defined in class Builder
    public long getDescriptor() {
                ^
/com/foo/Bar.java:9: error: Bar is not abstract and does not override abstract method getDescriptor() in BarOrBuilder
public  final class Bar extends
              ^
/com/foo/Bar.java:71: error: getDescriptor() in Bar cannot implement getDescriptor() in BarOrBuilder
      getDescriptor() {
      ^
  overriding method is static
/com/foo/Bar.java:153: error: incompatible types: Descriptor cannot be converted to long
        getDescriptor());
                     ^
/com/foo/Bar.java:252: error: Builder is not abstract and does not override abstract method getDescriptor() in BarOrBuilder
  public static final class Builder extends
                      ^
/com/foo/Bar.java:257: error: getDescriptor() in Builder cannot implement getDescriptor() in BarOrBuilder
        getDescriptor() {
        ^
  overriding method is static
/com/foo/Bar.java:364: error: bad operand types for binary operator '!='
      if (other.getDescriptor() != 0L) {
                                ^
  first type:  Descriptor
  second type: long
/com/foo/Bar.java:365: error: incompatible types: Descriptor cannot be converted to long
        setDescriptor(other.getDescriptor());
                                         ^
INFO: Elapsed time: 7.140s, Critical Path: 1.77s
INFO: 2 processes: 2 darwin-sandbox.
FAILED: Build did NOT complete successfully
make: *** [bazel] Error 1
```

**Anything else we should know about your project / environment**

Nothing else special - I purposefully kept the reproduction as simple as possible.

**Comment by BSBandme** [comment] 2019-02-20 14:28
@anandolee , What's the current status for the key words resolution? 
Although descriptor is not key word of Java, but this will conflict with other internal function for java.

Generally I think it's hard to detect all the possible conflicts for every language in protoc.

**Comment by peter-edge** [comment] 2019-02-20 14:33
For reference, other ones I personally cover: https://github.com/uber/prototool/blob/dev/internal/lint/check_package_no_keywords.go#L33

**Comment by BSBandme** [comment] 2019-02-25 03:46
Currently we have some proposal for resolving the conflicts under discussion, we'll update here after we have some decision.

**Comment by elharo** [comment] 2021-09-30 11:45
dupe of #5056

**Closed by elharo** 2021-09-30 11:45 UTC
Labels: bug, java, customer issue, P3
