### ISSUE TITLE
Generated Java code causes "redundant cast to Builder" warnings

### ISSUE THREAD

**Issue by slovdahl** [protocolbuffers/protobuf#5139] opened 2018-09-12 08:36 UTC
**What version of protobuf and what language are you using?**
Version: v3.6.1
Gradle plugin version: v0.8.6
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 16.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
```
$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**What did you do?**

I don't know if this is a regression or always has been like this, this is the first time I'm using the protobuf java stuff.

I prepared a project demonstrating the issue https://github.com/slovdahl/protobuf-java-warnings, but in short:

1. Created a gradle project:
```gradle
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.6'
    }
}

repositories {
    mavenCentral()
}

apply plugin: 'java'
apply plugin: 'com.google.protobuf'

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.6.1'
    }
}

dependencies {
    compile 'com.google.protobuf:protobuf-java:3.6.1'
}

compileJava {
    options.compilerArgs += ['-Xlint']
}
```
2. Created a proto definition:
```protobuf
syntax = "proto3";

package com.foo.bar.proto;

option java_outer_classname = "Event";

message Foo {
    int32 id = 1;
}
```
3. Executed `./gradlew compileJava`, which generates the java code and compiles the generated code.

**What did you expect to see**
No java compiler warnings.

**What did you see instead?**
```
/home/dev/protobuf-test/build/generated/source/proto/main/java/com/foo/bar/proto/Event.java:341: warning: [cast] redundant cast to Builder
        return (Builder) super.clone();
               ^
/home/dev/protobuf-test/build/generated/source/proto/main/java/com/foo/bar/proto/Event.java:347: warning: [cast] redundant cast to Builder
        return (Builder) super.setField(field, value);
               ^
/home/dev/protobuf-test/build/generated/source/proto/main/java/com/foo/bar/proto/Event.java:352: warning: [cast] redundant cast to Builder
        return (Builder) super.clearField(field);
               ^
/home/dev/protobuf-test/build/generated/source/proto/main/java/com/foo/bar/proto/Event.java:357: warning: [cast] redundant cast to Builder
        return (Builder) super.clearOneof(oneof);
               ^
/home/dev/protobuf-test/build/generated/source/proto/main/java/com/foo/bar/proto/Event.java:363: warning: [cast] redundant cast to Builder
        return (Builder) super.setRepeatedField(field, index, value);
               ^
/home/dev/protobuf-test/build/generated/source/proto/main/java/com/foo/bar/proto/Event.java:369: warning: [cast] redundant cast to Builder
        return (Builder) super.addRepeatedField(field, value);
               ^
6 warnings
```

**Comment by slovdahl** [comment] 2018-10-11 06:28
Would you be willing to accept a pull request that fixes this?

**Comment by slovdahl** [comment] 2018-10-16 07:51
Thanks for accepting the fix!

@BSBandme What's your policy regarding new releases, how often are releases made? Not asking that you make a release immediately, just want to know how to set my expectations :slightly_smiling_face:

**Comment by perlun** [comment] 2018-11-28 12:49
@acozzette You seem to have [tagged a 3.6.1.1 release](https://github.com/protocolbuffers/protobuf/releases/tag/v3.6.1.1) 7 days ago, but this version is not yet available in Maven Central from what I can tell: https://search.maven.org/search?q=g:com.google.protobuf

![image](https://user-images.githubusercontent.com/630613/49152727-67265780-f31c-11e8-9ee8-887bece7b700.png)

Also, this commit (dc81f795c791a4ccb61f0317ee47843bc4f07252) doesn't seem to be present on the 3.6.x branch for now: https://github.com/protocolbuffers/protobuf/compare/v3.6.1...3.6.x, so I'm pretty certain it isn't included in the version that got tagged as 3.6.1.1.

If you could cherry-pick this change (or, make someone else do it) and put out a 3.6.1.2 or 3.6.2 version, me (and others) would be incredibly thankful. Thanks in advance! :+1:

**Comment by acozzette** [comment] 2018-11-28 19:41
@perlun That 3.6.1.1 release was just meant to include an important fix that was blocking the Bazel 0.20 release, so I tagged a commit without doing a full release and publishing artifacts and everything. We are going to do a real 3.7 release soon, so that will include all the changes that are currently on master.

**Comment by perlun** [comment] 2018-12-04 21:04
@acozzette Wonderful, thanks for the update. 👍

**Comment by luster** [comment] 2019-01-04 21:30
any update on the timeline for new release?

**Comment by perlun** [comment] 2019-01-08 08:19
Ping @acozzette or others - any updates? (I was reminded about this now since it floods our build output)

**Comment by klaraward** [comment] 2019-02-21 14:41
Another ping, any ETA for the next release?

**Comment by acozzette** [comment] 2019-02-22 04:38
We are working on it now. I think it's probably ready to go but we're going to do another rc release just to be safe before we release 3.7.0.

**Comment by voidzcy** [comment] 2020-03-16 19:07
Seems this issue is still not fixed in `javalite` generated code. I saw those warnings when using `protobuf-javalite:3.11.0`.

**Comment by bmarwell** [comment] 2021-02-02 19:57
please reopen as requested in https://github.com/protocolbuffers/protobuf/issues/8208 by @perezd in https://github.com/protocolbuffers/protobuf/issues/8208#issuecomment-771909507.

**Comment by perezd** [comment] 2021-02-02 20:02
Oops, didn't realize it was closed.

**Comment by bmarwell** [comment] 2021-08-10 08:48
Hi, any progress on this?

**Comment by perezd** [comment] 2021-08-10 16:49
Has this been reproduced w/ our latest java release? (3.17)

**Comment by bmarwell** [comment] 2021-08-12 16:47
Huh, maybe you could add a test. PR https://github.com/protocolbuffers/protobuf/pull/5247 sadly did not add any.

**Comment by danadam** [comment] 2022-02-11 00:40
The script in attachment, with `protoc`, `protobuf-java-3.19.4.jar` and `protobuf-javalite-3.19.4.jar` in current directory, gives output:
```
javac 11.0.13
libprotoc 3.19.4
test proto2 full
test proto3 full
test proto2 lite
java-test/TestProto2.java:147: warning: [cast] redundant cast to Builder
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
             ^
1 warning
test proto3 lite
java-test/TestProto3.java:133: warning: [cast] redundant cast to Builder
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
             ^
1 warning
```
[redundant.cast.sh.txt](https://github.com/protocolbuffers/protobuf/files/8045222/redundant.cast.sh.txt)

**Comment by perezd** [comment] 2022-02-11 17:37
We'll accept PRs to resolve this similar to the others if you'd like.

**Comment by bmarwell** [comment] 2022-02-12 11:42
> We'll accept PRs to resolve this similar to the others if you'd like.

You already did this for non-lite versions:
https://github.com/protocolbuffers/protobuf/commit/dc81f795c791a4ccb61f0317ee47843bc4f07252

**Comment by perezd** [comment] 2022-02-14 18:17
Great! That'll make it easier for someone to send us a PR, appreciate it!

**Closed** 2023-05-17 16:34 UTC
Labels: java, cleanup
