### ISSUE TITLE
Generate kotlin code: Unresolved reference

### ISSUE THREAD

**Issue by lz1998** [protocolbuffers/protobuf#8668] opened 2021-05-27 13:27 UTC
**What version of protobuf and what language are you using?**
Version: 3.17.1
Language: Kotlin

**What operating system (Linux, Windows, ...) and version?**
MacOS

**What runtime / compiler are you using (e.g., python version or gcc version)**
JDK 8

**What did you do?**
1. Protobuf File `onebot_idl/onebot_base.proto`
``` protobuf
syntax = "proto3";
package onebot;

message Message{
    string type = 1;
    map<string, string> data = 2;
}
```
2. Generate kotlin code `protoc -I=onebot_idl --kotlin_out=src/main/kotlin onebot_idl/onebot_base.proto`
3. Unresolved reference: OnebotBase
There are two generated files: **MessageKt.kt** and **OnebotBaseKt.kt**.
    - **OnebotBaseKt.kt** is an empty file.
    - **MessageKt.kt** report an error `Unresolved reference: OnebotBase`
```kotlin
//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: onebot_base.proto

package onebot;

@kotlin.jvm.JvmSynthetic
inline fun message(block: onebot.MessageKt.Dsl.() -> Unit): onebot.OnebotBase.Message =
  onebot.MessageKt.Dsl._create(onebot.OnebotBase.Message.newBuilder()).apply { block() }._build()
object MessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: onebot.OnebotBase.Message.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: onebot.OnebotBase.Message.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): onebot.OnebotBase.Message = _builder.build()

    /**
     * <code>string type = 1;</code>
     */
    var type: kotlin.String
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    /**
     * <code>string type = 1;</code>
     */
    fun clearType() {
      _builder.clearType()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class DataProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>map&lt;string, string&gt; data = 2;</code>
     */
     val data: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DataProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getDataMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.getDataMap()
      )
    /**
     * <code>map&lt;string, string&gt; data = 2;</code>
     */
    @JvmName("putData")
    fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DataProxy>
      .put(key: kotlin.String, value: kotlin.String) {
         _builder.putData(key, value)
       }
    /**
     * <code>map&lt;string, string&gt; data = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setData")
    inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DataProxy>
      .set(key: kotlin.String, value: kotlin.String) {
         put(key, value)
       }
    /**
     * <code>map&lt;string, string&gt; data = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeData")
    fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DataProxy>
      .remove(key: kotlin.String) {
         _builder.removeData(key)
       }
    /**
     * <code>map&lt;string, string&gt; data = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllData")
    fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DataProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
         _builder.putAllData(map)
       }
    /**
     * <code>map&lt;string, string&gt; data = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearData")
    fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DataProxy>
      .clear() {
         _builder.clearData()
       }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun onebot.OnebotBase.Message.copy(block: onebot.MessageKt.Dsl.() -> Unit): onebot.OnebotBase.Message =
  onebot.MessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

```

**What did you expect to see**
no error
**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
![image](https://user-images.githubusercontent.com/9082086/119833892-11a18480-bf32-11eb-90f3-64859865dfe1.png)
![image](https://user-images.githubusercontent.com/9082086/119833967-20883700-bf32-11eb-9ed2-e5208e1ee900.png)

**Anything else we should know about your project / environment**
Nothing

**Comment by deannagarcia** [comment] 2021-05-27 17:06
Hi! I think this is because when you compile you also need to use `--java_out` as well as `--kotlin_out`. I am updating the docs now to reflect this.

**Comment by lz1998** [comment] 2021-05-28 12:17
> Hi! I think this is because when you compile you also need to use `--java_out` as well as `--kotlin_out`. I am updating the docs now to reflect this.

`protoc -I=onebot_idl --kotlin_out=src/main/kotlin --java_out=src/main/java onebot_idl/onebot_base.proto`
Is this correct?

**Comment by deannagarcia** [comment] 2021-06-01 16:53
Are you trying to use lite protos? If so, you should use: `protoc -I=onebot_idl --kotlin_out=lite:src/main/kotlin --java_out=lite:src/main/java onebot_idl/onebot_base.proto`. And if you want to use full protos, then the Gradle KTS should use `protobuf-kotlin` and `protobuf-java` instead of the lite libraries. Other than that, I think this should work.

**Comment by juliocatano** [comment] 2021-06-16 02:06
Yeah, this is also happening to me and I run this command:
`protoc -I=$SRC_DIR --java_out=$DST_DIR --kotlin_out=$DST_DIR $SRC_DIR/*.proto`

**Comment by deannagarcia** [comment] 2021-06-16 17:22
What specific error messages are you seeing? And are there any more details you can give to help me reproduce your error?

**Comment by juliocatano** [comment] 2021-06-20 01:49
@deannagarcia I think I misinterpreted the documentation. So I was hoping that when I chose the Kotlin output, I would be able to just delete the Java files. Maybe the documentation should be clearer in regards that even if your choose to generate the Kotlin classes, you cannot remove the Java classes since the Koltin classes depend on them.

**Comment by deannagarcia** [comment] 2021-06-21 17:23
I have updated the documentation since the original bug that I think reflects this. I'm going to go ahead and close this issue now but let me know if there's anything else I can do to make it more clear!

**Closed by deannagarcia** 2021-06-21 17:23 UTC
