### ISSUE TITLE
Fatal error with v3.14

### ISSUE THREAD

**Issue by gunjanpatidar** [protocolbuffers/protobuf#8278] opened 2021-02-10 03:46 UTC
**What version of protobuf and what language are you using?**
Version: v3.14.0
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
Linux / Ubuntu 18.04.3 LTS

**What runtime / compiler are you using (e.g., python version or gcc version)**
PHP 7.2.24-0ubuntu0.18.04.7

**What did you do?**
execute below code (code pasted at the bottom)

````sh
php test.php
````

**What did you expect to see**
No Error. **Same code returns no error with PHP protobuf extension v3.10.0**

**What did you see instead?**
Fatal Error
````sh
# php test.php
WARNING: file was already added
PHP Fatal error:  Unable to load descriptor: couldn't resolve name '.serviceB.common.StatusB+�ServiceB\TestB�ServiceB\Metadata\TestBbproto3'
 in /serviceB/client/php/src/ServiceB/Metadata/TestB/TestB.php on line 24
````

-----
Testcase: 
[protobuf_testcase.zip](https://github.com/protocolbuffers/protobuf/files/5955733/protobuf_testcase.zip)

./test.php

````php
<?php

spl_autoload_register(function($className) {
        $className = str_replace("\\", DIRECTORY_SEPARATOR, $className);
        $f1 = './serviceA/client/php/src/' . $className . '.php';
        $f2 = './serviceB/client/php/src/' . $className . '.php';
        if (file_exists($f1)) {
                require_once($f1);
        } else {
                require_once($f2);
        }
});

$r1 = new \ServiceA\TestA\A1();
// var_dump($r1);

$r2 = new \ServiceB\TestB\B1();
// var_dump($r2);

?>
````

./serviceA/proto/common/common.proto

````proto
syntax = "proto3";

package serviceA.common;

option php_namespace = "ServiceA\\Common";
option php_metadata_namespace = "ServiceA\\Metadata\\Common";

message Status {
  string message = 1;
  uint32 code = 2;
}
````

./serviceA/proto/testA/testA.proto

````proto
syntax = "proto3";

package serviceA.testA;

option php_namespace = "ServiceA\\TestA";
option php_metadata_namespace = "ServiceA\\Metadata\\TestA";

import "proto/common/common.proto";

message A1 {
  serviceA.common.Status status = 1;
}
````

./serviceB/proto/common/common.proto

````proto
syntax = "proto3";

package serviceB.common;

option php_namespace = "ServiceB\\Common";
option php_metadata_namespace = "ServiceB\\Metadata\\Common";

message Status {
    bool success = 1;
    string message = 2;
    int32 error_code = 3;
}
````

./serviceB/proto/testB/testB.proto

````proto
syntax = "proto3";

package serviceb.testB;

option php_namespace = "ServiceB\\TestB";
option php_metadata_namespace = "ServiceB\\Metadata\\TestB";

import "proto/common/common.proto";

message B1 {
    serviceB.common.Status status = 1;
}
````

**Comment by gunjanpatidar** [comment] 2021-02-10 03:50
Also, no error when using google/protobuf:v3.14.0 PHP library. However the C extension throws the above Fatal error.

**Comment by haberman** [comment] 2021-02-17 18:19
I think I know what is going on (thanks for the excellent repro, btw). The newer version of the code (soon to be released in 3.15.0-rc2) gives a better error message:

> PHP Warning:  proto descriptor was previously loaded (included in multiple metadata bundles?): proto/common/common.proto in /tmp/protobuf_testcase/serviceB/client/php/src/ServiceB/Metadata/Common/Common.php on line 24

The problem is that `.proto` files are uniquely identified by their file name, relative to whatever base or base directories you are using. In this example you appear to have two files whose canonical name is `proto/common/common.proto`. This means that both files cannot be loaded into the same runtime image: loading the second one will fail, which will then cause the symbols from the second file to not be found.

The solution is either to change one of the file names, or alternatively include the parent directory (`ServiceA` / `ServiceB`) in the canonical filename path.

**Closed by haberman** 2021-02-17 18:19 UTC

**Comment by gunjanpatidar** [comment] 2021-02-24 11:33
Hi @haberman,

Thanks for checking this. From your reply, I understand this is happening because of the conflicting paths.

However, since this was working fine with v3.10.0 and breaking in one of the recent releases, shouldn't it be considered a regression?

Also, if this is the intended behaviour, the PHP extension should produce the same error message as the C extension, but that works fine.

Sorry for being too pushy on this but the suggested solution is not convenient nor reliable. As a downstream service which calls multiple other services by loading their clients via composer, it's very hard to ensure their paths do not collide. It also does not make sense for a consumer to dictate where the upstream service places it's proto files.

**Comment by haberman** [comment] 2021-02-24 18:13
I agree that the PHP extension should be fixed to produce the same error message.

I can understand your perspective that this appears to be a regression. But the old behavior is buggy and can't be supported in the longer term.

For example, protobuf reflection generally offers a way to look up a file's reflection from its filename. In C++ you can write:

```c++
  google::protobuf::DescriptorPool::generated_pool()->FindFileByName("proto/common/common.proto");
```

This function should eventually be available in PHP also. If we allowed multiple files named `proto/common/common.proto`, the line above would be ambiguous.

Other languages like C++ already disallow this. It's important that we don't have protos that are loadable in some languages but not others. 

I do apologize that this wasn't checked before, I recognize it is intrusive that we are starting to check this now.

> It also does not make sense for a consumer to dictate where the upstream service places it's proto files.

There is already an expectation that upstream services will not create conflicting PHP class names, yes? If you had two libraries that both defined a class called `Proto\Common\Common`, the class names would conflict. If two libraries both had filenames like `Proto/Common/Common.php` those would conflict too. The same concept applies to .proto files.

**Comment by gunjanpatidar** [comment] 2021-05-25 05:59
Hi @haberman this stand has been recently changed for the golang compiler https://github.com/golang/protobuf/issues/1122, https://github.com/protocolbuffers/protobuf-go/commit/febffdd88e85cb4402205142aaa1a4cc64d0d375

Are there plans to change this for PHP as well? If not we would still need to enforce unique file paths across services.

**Comment by hdevalence** [comment] 2023-02-08 00:26
> There is already an expectation that upstream services will not create conflicting PHP class names, yes?

But the upstream services *are* disambiguating their names. One is defining `package serviceA.common;` and the other is defining `package serviceB.common;`. The requirement that every _source_ filename is globally unique across _all source code_ is unworkable in the real world, where not everyone works for the same company and checks code into the same monorepo.
