### ISSUE TITLE
Provide a ruby native gem for aarch64 linux 

### ISSUE THREAD

**Issue by jtattermusch** [protocolbuffers/protobuf#8682] opened 2021-06-01 07:54 UTC
protobuf ruby builds fine on aarch64 linux (arm64) and the tests are passing there.
The missing piece is that we currently don't provide pre-built package (=native gem) for aarch64 linux.

Related issue:
https://github.com/grpc/grpc/issues/26391

**Comment by jtattermusch** [comment] 2021-06-01 07:58
Ruby artifacts build happens here: https://github.com/protocolbuffers/protobuf/blob/master/kokoro/release/ruby/linux/ruby/ruby_build.sh

https://github.com/protocolbuffers/protobuf/blob/0b8d13a1d4cd9be16ed8a2230577aa9c296aa1ca/ruby/Rakefile#L96

**Comment by jtattermusch** [comment] 2021-10-05 11:28
FTR linux-aarch64 support has been added to rake-compiler-dock in rake-compiler/rake-compiler-dock#54

**Comment by JasonLunn** [comment] 2022-09-01 18:09
Closing this because in version 3.22 protobuf is planning to experiment with releasing only a source gem.

If this experiment is unsuccessful and we revert to building binary gems for some platforms, we'll evaluate whether it makes sense to add aarch64 linux at that time.

CC: @deannagarcia @haberman

**Closed by JasonLunn** 2022-09-01 18:09 UTC
Labels: ruby

**Comment by chadlwilson** [comment] 2023-03-04 06:00
@JasonLunn Was this experiment successful? I am inferring perhaps not, since 3.22 still seems to have binary gems included?

I opened #12144 but now realise it's a possible duplicate of this. Would there be an intention to re-open this?

**Comment by deannagarcia** [comment] 2023-03-07 18:11
We had enough requests for binary gems that we decided to keep them. We are currently working on adding an aarch64 linux binary, and we expect it to be in a patch release for v22.
