### ISSUE TITLE
Protocol Buffer and Maven

### ISSUE THREAD

**Issue by deji04** [protocolbuffers/protobuf#5149] opened 2018-09-14 03:54 UTC
Hi,

I am learning the Protocol Buffer and when I am trying to do the 'mvn test' step, I encountered some issue.

[root@localhost protobuf-master]# mvn test
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.879 s
[INFO] Finished at: 2018-09-14T11:41:56+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/root/protobuf-master). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

This is my maven version:
[root@localhost protobuf-master]# mvn -v
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-18T02:33:14+08:00)
Maven home: /usr/local/src/apache-maven
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-862.11.6.el7.x86_64", arch: "amd64", family: "unix"

Thank you in advance.

**Comment by acozzette** [comment] 2018-09-17 20:55
@deji04 I suspect the problem is that you first need to `cd` into the `java` subdirectory.

**Comment by deji04** [comment] 2018-09-18 03:34
Hi @acozzette 

Yes, I changed directory to the java subdirectory. I encountered some issues again but then I ran mvn:archetype generate and was able to execute the 'mvn test' command.
Now I am in 'mvn install' command and run is not yet finished. 
See my question here : [https://github.com/protocolbuffers/protobuf/issues/5159](url)

Thank you for the response, Adam!

**Comment by acozzette** [comment] 2018-09-18 17:51
OK, let me close this issue since it looks like #5159 covers the remaining problem.

**Closed by acozzette** 2018-09-18 17:51 UTC
Labels: java, question
