### ISSUE TITLE
oneof duplicate names creates uncompilable code

### ISSUE THREAD

**Issue by TobixDS** [protocolbuffers/protobuf#9259] opened 2021-11-26 14:52 UTC
**What version of protobuf and what language are you using?**
Version: 3.17.3
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
makes no difference

**What did you do?**
Compile the following proto file to C++
```
syntax = "proto3";
package oneoftrouble;

message foo {
    oneof bar {
		int32 int_value = 1;
		string Bar = 2;
	}
}
```

**What did you expect to see**
Valid c++ code or a warning/error from protoc

**What did you see instead?**
The generated class contains two methods with identical name
```
class foo {
  :
 void clear_bar();
  :
 void clear_bar();
```

**Comment by fowles** [comment] 2022-09-01 18:43
Duplicate of https://github.com/protocolbuffers/protobuf/issues/10491

**Closed** 2022-09-01 18:43 UTC
Labels: bug, c++, protoc
