### ISSUE TITLE
Python 3 - Unicode errors reading various METADATA.pb files with Python

### ISSUE THREAD

**Issue by bootrino** [protocolbuffers/protobuf#4721] opened 2018-06-04 00:06 UTC
I'm cross posting this because I don't know if it is a problem with protobuf or a problem with Google fonts.

If anyone can help it would be much appreciated.

Here is the issue:

https://github.com/google/fonts/issues/1591

**Comment by acozzette** [comment] 2018-06-18 22:32
@bootrino Could you paste an example of one of these `.pb` files that's causing a parse failure?

**Comment by bootrino** [comment] 2018-06-18 22:52
https://github.com/google/fonts/blob/master/ofl/imfellgreatprimer/METADATA.pb
https://github.com/google/fonts/blob/master/ofl/ptsansnarrow/METADATA.pb
https://github.com/google/fonts/blob/master/ofl/boogaloo/METADATA.pb
https://github.com/google/fonts/blob/master/ofl/nanumbrushscript/METADATA.pb
https://github.com/google/fonts/blob/master/ofl/imfellenglish/METADATA.pb
https://github.com/google/fonts/blob/master/ofl/imfellfrenchcanon/METADATA.pb
https://github.com/google/fonts/blob/master/ofl/playfairdisplaysc/METADATA.pb
https://github.com/google/fonts/blob/master/ofl/lato/METADATA.pb


Plus about 30 more that I can't be bothered getting the URL for.

**Comment by bootrino** [comment] 2018-06-18 23:37
```
(venv35) ubuntu@ip-10-0-0-196:~/code/$ file /usr/share/fonts/truetype/imfellgreatprimer/METADATA.pb
/usr/share/fonts/truetype/imfellgreatprimer/METADATA.pb: UTF-8 Unicode text
(venv35) ubuntu@ip-10-0-0-196:~/code/$
```

Have you tried executing the code fragment in the link above?  Here it is again:

```
import os
from fonts_public_pb2 import FontProto, FamilyProto
from google.protobuf import text_format


for dirpath, dirnames, filenames in os.walk('/usr/share/fonts/truetype'):
    metadataProtoFile = os.path.join(dirpath, 'METADATA.pb')
    if not os.path.exists(metadataProtoFile):
        continue

    metadata = FamilyProto()
    with open(metadataProtoFile) as f:
        text_data = f.read()
    try:
        text_format.Merge(text_data, metadata)
    except Exception as e:
        print(metadataProtoFile)
        print(repr(e))
    continue
```

**Comment by acozzette** [comment] 2018-06-18 23:44
@bootrino Just to get the file reading out of the equation, could you try pasting the data into your Python code as a string and seeing if you're able to parse it successfully that way?

**Comment by bootrino** [comment] 2018-06-18 23:51
Here tis:

```
(venv35) ubuntu@ip-10-0-0-196:~/code/fontprocessor$ python foo.py
Traceback (most recent call last):
  File "/home/ubuntu/venv35/lib/python3.5/site-packages/google/protobuf/text_format.py", line 1239, in ConsumeString
    return six.text_type(the_bytes, 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "foo.py", line 33, in <module>
    text_format.Merge(foo, metadata)
  File "/home/ubuntu/venv35/lib/python3.5/site-packages/google/protobuf/text_format.py", line 533, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/ubuntu/venv35/lib/python3.5/site-packages/google/protobuf/text_format.py", line 587, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/ubuntu/venv35/lib/python3.5/site-packages/google/protobuf/text_format.py", line 620, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/ubuntu/venv35/lib/python3.5/site-packages/google/protobuf/text_format.py", line 635, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/ubuntu/venv35/lib/python3.5/site-packages/google/protobuf/text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)
  File "/home/ubuntu/venv35/lib/python3.5/site-packages/google/protobuf/text_format.py", line 823, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/ubuntu/venv35/lib/python3.5/site-packages/google/protobuf/text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)
  File "/home/ubuntu/venv35/lib/python3.5/site-packages/google/protobuf/text_format.py", line 874, in _MergeScalarField
    value = tokenizer.ConsumeString()
  File "/home/ubuntu/venv35/lib/python3.5/site-packages/google/protobuf/text_format.py", line 1241, in ConsumeString
    raise self._StringParseError(e)
google.protobuf.text_format.ParseError: 15:1 : Couldn't parse string: 'utf-8' codec can't decode byte 0xa9 in position 0: invalid start byte
(venv35) ubuntu@ip-10-0-0-196:~/code/fontprocessor$ cat foo.py
import os
from fonts_public_pb2 import FontProto, FamilyProto
from google.protobuf import text_format
foo = """
name: "IM Fell Great Primer"
designer: "Igino Marini"
license: "OFL"
category: "SERIF"
date_added: "2010-05-17"
fonts {
  name: "IM Fell Great Primer"
  style: "normal"
  weight: 400
  filename: "IMFeGPrm28P.ttf"
  post_script_name: "IM_FELL_Great_Primer_Roman"
  full_name: "IM FELL Great Primer Roman"
  copyright: "© 2007 Igino Marini (www.iginomarini.com mail@iginomarini.com) With Reserved Font Name IM FELL Great Primer Roman"
}
fonts {
  name: "IM Fell Great Primer"
  style: "italic"
  weight: 400
  filename: "IMFeGPit28P.ttf"
  post_script_name: "IM_FELL_Great_Primer_Italic"
  full_name: "IM FELL Great Primer Italic"
  copyright: "© 2007 Igino Marini (www.iginomarini.com mail@iginomarini.com) With Reserved Font Name IM FELL Great Primer Italic"
}
subsets: "menu"
subsets: "latin"
"""

metadata = FamilyProto()
text_format.Merge(foo, metadata)

(venv35) ubuntu@ip-10-0-0-196:~/code/fontprocessor$
```

**Comment by bootrino** [comment] 2018-06-18 23:59
This is the output when the same code as above is run with Python 2.

```
ubuntu@ip-10-0-0-196:~/code/fontprocessor$ python foo.py
ubuntu@ip-10-0-0-196:~/code/fontprocessor$

```

**Comment by acozzette** [comment] 2018-06-20 18:03
Ok, I think it must be choking on the copyright symbol somehow. In UTF-8 that is represented as the two-byte sequence `c2 a9`. Based on that error message it appears that we are attempting to skip over the first byte and start parsing a character from the second byte, though:
```
>>> six.text_type(b'\xc2\xa9', 'utf-8')
'©'
>>> six.text_type(b'\xa9', 'utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 0: invalid start byte
```

**Comment by acozzette** [comment] 2018-06-20 18:32
@bootrino Which protobuf version are you using?

**Comment by bootrino** [comment] 2018-06-20 20:38
I was using 3.5.2.post1

```
(venv35) ubuntu@ip-10-0-0-196:~/code/renderserver$ pip freeze
awscli==1.15.28
botocore==1.10.28
colorama==0.3.9
docutils==0.14
fontmeta==1.6.0
fonttools==3.26.0
jmespath==0.9.3
pkg-resources==0.0.0
**protobuf==3.5.2.post1**
pyasn1==0.4.3
python-dateutil==2.7.3
PyYAML==3.12
rsa==3.4.2
s3transfer==0.1.13
six==1.11.0
(venv35) ubuntu@ip-10-0-0-196:~/code/renderserver$
```

Following this question I upgraded to 3.6 and tried again:

```
(venv35) ubuntu@ip-10-0-0-196:~/code/fontprocessor$ pip install --upgrade protobuf
Collecting protobuf
  Downloading https://files.pythonhosted.org/packages/11/c4/8a35f5af5f26040ae7f3d521875e43429d2955d598fa3f2d0b6b88133bb1/protobuf-3.6.0-cp35-cp35m-manylinux1_x86_64.whl (7.1MB)
    100% |████████████████████████████████| 7.1MB 7.7MB/s
Requirement not upgraded as not directly required: setuptools in /home/ubuntu/venv35/lib/python3.5/site-packages (from protobuf) (39.2.0)
Requirement not upgraded as not directly required: six>=1.9 in /home/ubuntu/venv35/lib/python3.5/site-packages (from protobuf) (1.11.0)
Installing collected packages: protobuf
  Found existing installation: protobuf 3.5.2.post1
    Uninstalling protobuf-3.5.2.post1:
      Successfully uninstalled protobuf-3.5.2.post1
Successfully installed protobuf-3.6.0
```



```
(venv35) ubuntu@ip-10-0-0-196:~/code/fontprocessor$ python foo.py
Traceback (most recent call last):
  File "/home/ubuntu/venv35/lib/python3.5/site-packages/google/protobuf/text_format.py", line 1253, in ConsumeString
    return six.text_type(the_bytes, 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "foo.py", line 34, in <module>
    text_format.Merge(foo, metadata)
  File "/home/ubuntu/venv35/lib/python3.5/site-packages/google/protobuf/text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/ubuntu/venv35/lib/python3.5/site-packages/google/protobuf/text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/ubuntu/venv35/lib/python3.5/site-packages/google/protobuf/text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/ubuntu/venv35/lib/python3.5/site-packages/google/protobuf/text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/ubuntu/venv35/lib/python3.5/site-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/home/ubuntu/venv35/lib/python3.5/site-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/ubuntu/venv35/lib/python3.5/site-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/home/ubuntu/venv35/lib/python3.5/site-packages/google/protobuf/text_format.py", line 888, in _MergeScalarField
    value = tokenizer.ConsumeString()
  File "/home/ubuntu/venv35/lib/python3.5/site-packages/google/protobuf/text_format.py", line 1255, in ConsumeString
    raise self._StringParseError(e)
google.protobuf.text_format.ParseError: 15:1 : Couldn't parse string: 'utf-8' codec can't decode byte 0xa9 in position 0: invalid start byte
(venv35) ubuntu@ip-10-0-0-196:~/code/fontprocessor$
```

**Comment by acozzette** [comment] 2018-06-20 23:16
I think I've figured out a fix in PR #4804. @bootrino Do you want to give that fix a try just to verify that it solves the problem? I should also add a test before I submit that change.

**Comment by acozzette** [comment] 2018-06-20 23:43
I tried with Python 3, and actually my fix is specific to Python 3 because with 2 that `CUnescape` function does something different by returning early. So that might explain why the bug doesn't come up in Python 2.

Now that I think of it I'm not sure of the best way for you to test it out. I don't work with Python too often so I don't know of a good way to do this without publishing a new version to PyPI. But I'm fairly sure this should fix it, so maybe I'll just do a patch release after I submit the change.

**Comment by bootrino** [comment] 2018-06-20 23:56
I just hacked your change straight into the Python code in the venv library and it seemed to work!

Thanks for this I appreciate your help.

**Comment by acozzette** [comment] 2018-06-22 22:22
I'm glad that it worked, but unfortunately I've found that my pull request causes something else to break. The problem is that `CUnescape` is also used here to operate on default values for bytes fields, which are not necessarily UTF-8: https://github.com/google/protobuf/blob/f42d5923f0b6de75611af0a8c8b3354763aece00/python/google/protobuf/descriptor_pool.py#L886

So ultimately I think we need a `CUnescape` function that's capable of unescaping hex and octal escapes for both UTF-8 and raw binary data, and which will work for both Python 2 and 3. I'm afraid I don't have time to work on this now, especially since I don't have a lot of knowledge of Python. But hopefully this summary of the problem will point in the right direction if anyone else wants to give this a try.

**Comment by gpshead** [comment] 2018-07-02 19:15
I'm working on a fix for this internally.  Testing now.

Under Python 3 `text_format` is entirely broken when it comes to parsing text protos that are not ASCII. It is also entirely broken when supposedly generating "utf-8" text protos if someone was unfortunate to use the `as_utf8=True` option on `text_format.MessageToString`.

I too came to this issue via METADATA files as we're updating all sorts of things internally to actually run on Python 3. :)

**Comment by kerstin** [comment] 2018-10-18 15:52
Hi there, I'm running into the same problem (came here via the linked issue [google/fonts#1591](https://github.com/google/fonts/issues/1591)), any update on this?

**Comment by anandolee** [comment] 2018-10-18 18:02
@kerstin, this issue is fixed on July and marked wait for 3.7.0 release. We haven't release 3.7.0 yet, current valid versions still have the problem

**Comment by felipesanches** [comment] 2018-12-03 04:01
This issue negatively impacts the Google Fonts Quality Assurance pipeline. (It crashes a check on FontBakery - https://github.com/googlefonts/fontbakery/)

We will wait for the upcoming protobuf 3.7.0 release. Thanks!

**Comment by anandolee** [comment] 2019-03-14 23:54
Closing it as 3.7.0 is already released

**Closed by anandolee** 2019-03-14 23:54 UTC
Labels: bug, python, wait for 3.7.0 release

**Comment by felipesanches** [comment] 2019-03-15 00:11
Thanks a lot! the upcoming Fontbakery version 0.6.13 to be released next Monday will have a bug fixed by this.
