### ISSUE TITLE
Multi-char unrecognized flags are reported as single char errors

### ISSUE THREAD

**Issue by elharo** [protocolbuffers/protobuf#10099] opened 2022-06-01 14:35 UTC
I ran this protoc command:

$ /google/src/cloud/elharo/CS-message-2022-05-23_160914/google3/blaze-bin/third_party/protobuf/compiler/protocol_compiler -java_out=. /google/src/cloud/elharo/CS-message-2022-05-23_160914/google3/javatests/com/google/io/protocol/test_bridge_proto1.proto
Unknown flag: -j

Unknown flag: -j should be "Unknown flag: -java_out" or even better it should recognize that it's a hyphen that's missing.

**Comment by deannagarcia** [comment] 2022-07-12 16:20
Closing since this is intended behavior

**Closed by deannagarcia** 2022-07-12 16:20 UTC
Labels: bug, help wanted, protoc
