### ISSUE TITLE
C++: conversion to int from uint64 may alter value 

### ISSUE THREAD

**Issue by Finkman** [protocolbuffers/protobuf#7103] opened 2020-01-16 14:20 UTC
**What version of protobuf and what language are you using?**
Version: v3.10.0 until v3.11.2
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 18.04, 64bit

**What runtime / compiler are you using (e.g., python version or gcc version)**
GCC GNU 7.4.0

**What did you do?**
Defined protobuf3 msg common.proto:
```yaml
syntax = "proto3";
package = test;
message Add{
  int32 sumA = 1;
  int32 sumB = 2;
  int32 result = 3;
}
```
ran protoc to generate common.pb.cc and compiled it with gcc.

**What did you expect to see**
Expected to compile common.pb.cc without a warning nor error.

**What did you see instead?**
```
/build/common.pb.cc:261:64: error: conversion to 'google::protobuf::int32 {aka int}' from 'google::protobuf::uint64 {aka long unsigned int}' may alter its value [-Werror=conversion]
           suma_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/build/common.pb.cc:268:64: error: conversion to 'google::protobuf::int32 {aka int}' from 'google::protobuf::uint64 {aka long unsigned int}' may alter its value [-Werror=conversion]
           sumb_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/build/common.pb.cc:275:66: error: conversion to 'google::protobuf::int32 {aka int}' from 'google::protobuf::uint64 {aka long unsigned int}' may alter its value [-Werror=conversion]
           result_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~

```

**Anything else we should know about your project / environment**
I started to rollback to see when the issue started:
Last working version: v3.9.2
First failing version: v3.10.0

**Comment by ycdtosa** [comment] 2020-01-20 14:35
related to issue #7107

**Comment by ycdtosa** [comment] 2020-01-31 16:49
At some point ReadVarint was removed from protobuf.

I had one runtime version of the compiler which would generate the code with the ReadVarint calls

When trying to build those files with a more recent version of the library it will not compile, with the same error you got.

I think that when removing the function,  the version number should change,
and some test should be placed to ensure the header version is compatible.

**Comment by Finkman** [comment] 2020-02-27 08:13
Is there a chance to get progress in here? Is there anything I can do to help to figure out the problem?
Also, #7137 seems to get stuck.

**Comment by Finkman** [comment] 2020-05-28 06:39
Sorry, for pushing it again.
IMHO this should be fixed

**Comment by waltronix** [comment] 2020-12-03 20:06
I tried to upgrade to protobuf v3.14.0 and also get the problem.

Is it planned to fix this?

**Comment by skebanga** [comment] 2021-04-01 12:30
Did you get anywhere with this? I'm getting hit by the same problem

```
error: conversion from ‘google::protobuf::uint64’ {aka ‘long unsigned int’} to ‘google::protobuf::int32’ {aka ‘int’} may change value [-Werror=conversion]
  240 |           cpu_affinity_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
```

**Comment by ycdtosa** [comment] 2021-04-01 13:47
It has been long since I run into this issue. At the time I moved on, and IIRC, I just moved away from master into a release branch.  I got the hint [in this answer to a related issue] https://github.com/protocolbuffers/protobuf/issues/7107#issuecomment-769260721)

Still, I think compiling clean from master should not run into this issue, which as it seems keeps happening.

Hope this helps.

**Comment by skebanga** [comment] 2021-04-01 14:31
Hmm, I am running off a release branch AFAIK

```
$ protoc --version
libprotoc 3.12.3
```

Thanks for the response - maybe I need to downgrade to get back to a version before this issue cropped up.

**Comment by mosdav** [comment] 2021-06-29 21:58
Reproduced also under `protoc` 3.15.8

**Comment by weidonglian** [comment] 2021-07-07 13:19
For those who want to work around this, you could simply generate all your proto cpp and h files into a given folder and create a library. You could also add Private compiler warnings to other platforms.

```
add_library(greeting_gen
  hello.pb.h
  hello.pb.cc
)

target_link_libraries(greeting_gen protobuf::libprotobuf)
if (WIN32)
  target_compile_options(module_data PRIVATE "/wd4244") # https://github.com/protocolbuffers/protobuf/issues/7103
endif()

target_include_directories(greeting_gen PUBLIC
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>
)
```

**Comment by gregstoll** [comment] 2021-07-21 02:50
FWIW it looks like #8769 will fix this.

**Comment by elharo** [comment] 2021-09-13 11:38
should be fixed

**Closed by elharo** 2021-09-13 11:38 UTC
Labels: cleanup, protoc
