### ISSUE TITLE
Issue of using malloc function instead of calloc

### ISSUE THREAD

**Issue by Gautam-zodape** [protocolbuffers/protobuf#9538] opened 2022-02-24 05:58 UTC
I have created an iOS app used protobuf.
I have got issue in penetration testing for usage of malloc function instead of calloc.

Could you update your library with calloc?
If you have any other plan to replace in future release then let me know.

**Comment by elharo** [comment] 2022-02-24 12:26
Please don't open new bugs for the same issue. Dupe of #9533

**Closed by elharo** 2022-02-24 12:26 UTC
