### ISSUE TITLE
Still Detected 8 Bytes Memory Leak After Calling google::protobuf::ShutdownProtobufLibrary()

### ISSUE THREAD

**Issue by ILikeIneine** [protocolbuffers/protobuf#9715] opened 2022-04-01 02:47 UTC
**What version of protobuf and what language are you using?**
Version: master/v3.19.4 (latest
Language: C++
**What operating system (Linux, Windows, ...) and version?**
Windows 11 
**What runtime / compiler are you using (e.g., python version or gcc version)**
MSVC on latest VS2022 with its CRT memory leak detector
**What did you do?**
1. I am writing an demo using proto3 and I initial an message which I predefined on an .proto file
2. I followed the proto3 C++ tutorial guide on official site, using arena to create my message
3. just doing nothing, and VS CRT detected memory leak, before the program exit, I called google::protobuf::ShutdownProtobufLibrary(), but the leak still exists, 8 bytes always;

**What did you expect to see**
no memory leak
**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

Detected memory leaks!
Dumping objects ->
{98} normal block at 0x014A2680, 8 bytes long.
 Data: < G2     > E0 47 32 01 00 00 00 00 
Object dump complete.

**Anything else we should know about your project / environment**

```
#define _CRTDBG_MAP_ALLOC
#include <crtdbg.h>
#include <iostream>
#include <string>
#include "card.pb.h"
#include "ProtocolResolverHelper.hpp"
#include <cassert>
#include "SessionHandler.hpp"
struct Cleanup_t
{
    ~Cleanup_t()
    {
        if (IsDebuggerPresent())
        {
            _CrtSetReportMode(_CRT_WARN, _CRTDBG_MODE_DEBUG);
            _CrtDumpMemoryLeaks();
        }
    }
};
Cleanup_t Cleanup;
int main()
{
    std::string serializedString;
    //    SessionHandler::Start();
    google::protobuf::Arena arena;
    auto* whiteEyeDragon = google::protobuf::Arena::Create<card::Card>(&arena);
    whiteEyeDragon->set_name("whiteEyeDragon");
    whiteEyeDragon->set_id(114514);
    whiteEyeDragon->set_type(card::Card_Type_MONSTER);
    whiteEyeDragon->mutable_desc()->Add("low resistance");
    whiteEyeDragon->mutable_monsinfo()->set_type(card::MonsInfo_Type_NORMAL);
    whiteEyeDragon->mutable_monsinfo()->set_ele(card::MonsInfo_Element_LIGHT);
    std::cout << whiteEyeDragon->DebugString() << std::endl;
    google::protobuf::ShutdownProtobufLibrary();
}
```

```
==========  output  ==========
Detected memory leaks!
Dumping objects ->
{98} normal block at 0x014A2680, 8 bytes long.
 Data: < G2     > E0 47 32 01 00 00 00 00 
Object dump complete.
==============================
```

**Comment by fowles** [comment] 2022-04-01 17:35
Any chance you can run this in a mode that tells you the source location of the allocation that was leaked?

**Comment by ILikeIneine** [comment] 2022-04-02 03:56
> Any chance you can run this in a mode that tells you the source location of the allocation that was leaked?
Yes, and I tried multiple times, the leaking memory block CRT detected was all the same.

My problem was kind of similar to this:
 [https://stackoverflow.com/questions/70240164/detected-memory-leaks-in-c]

but I'm not sure weather the problem was caused by MSVC CRT it self.... I ran the same demo on WSL ubuntu 20.04 with the 
latest version of protocol buffer, and Valgrind did not report the memory leak  >< 
 
And still I want to know what caused the differences between them, it did bothered me for a long time.  
Thanks very much! here donate u cups of tee for your works! 🍵🍵🍵☕☕☕

**Comment by fowles** [comment] 2022-04-02 17:33
You say the leaking memory block was the same each time, but I specifically asked for a source location.  Can you point to file:line of the allocation that is leaking?  Likely compiling with debug symbols will be enough to get you there.

**Comment by ILikeIneine** [comment] 2022-04-06 02:20
No, sorry I can't make it. I've tried following microsoft doc and set  ` _crtBreakAlloc = 98` which refers to the allocating number tag, but it did not trigger a break and the program just end. 
I think it's CRT's ploblem. I tried another codes without protobuf, still got similar faults. 
and maybe there is the explaination( I'm not sure= =  
>False positives
>_CrtDumpMemoryLeaks can give false indications of memory leaks if a library marks internal allocations as normal blocks >instead of CRT blocks or client blocks. In that case, _CrtDumpMemoryLeaks is unable to tell the difference between user >allocations and internal library allocations. If the global destructors for the library allocations run after the point where you call >_CrtDumpMemoryLeaks, every internal library allocation is reported as a memory leak. Versions of the Standard Template >Library earlier than Visual Studio .NET may cause _CrtDumpMemoryLeaks to report such false positives.

**Comment by deannagarcia** [comment] 2022-05-02 20:57
Agreed that this seems like an issue outside of protobuf, closing the issue.

**Closed by deannagarcia** 2022-05-02 20:57 UTC

**Comment by harshr094** [comment] 2023-05-19 19:15
Where you able to fix it? Find the cause of it? I am also facing similar issue

**Comment by gocohen** [comment] 2024-03-18 10:24
Same here, I am seeing many leaks on windows even after invoking `google::protobuf::ShutdownProtobufLibrary()`
