### ISSUE TITLE
[Ruby] 3.15 regression: Cannot get repeated field values using bracket notation

### ISSUE THREAD

**Issue by dazuma** [protocolbuffers/protobuf#8317] opened 2021-02-19 20:43 UTC
**What version of protobuf and what language are you using?**
Version: 3.15.0
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
Various (tried on both gLinux x86_64, Mac Catalina x86_64)

**What runtime / compiler are you using (e.g., python version or gcc version)**
Using the prebuilt release binary for Ruby.

**What did you do?**
```ruby
require "google/protobuf"
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("blah.proto", syntax: :proto3) do
    add_message "TestProto" do
      optional :single, :string, 1
      repeated :multi, :string, 2
    end
  end
end
TestProto = Google::Protobuf::DescriptorPool.generated_pool.lookup("TestProto").msgclass
message = TestProto.new(single: "hello", multi: ["a", "b"])
p message.single
p message["single"]
p message.multi
p message["multi"]
```

**What did you expect to see**
This is what I see under google-protobuf 3.14.0:
```
"hello"
"hello"
["a", "b"]
["a", "b"]
```

**What did you see instead?**
This is what I see under google-protobuf 3.15.0:
```
"hello"
"hello"
["a", "b"]
""
```

**Comment by haberman** [comment] 2021-02-19 22:27
Closing as duplicate of https://github.com/protocolbuffers/protobuf/issues/8311

**Closed by haberman** 2021-02-19 22:27 UTC
