### ISSUE TITLE
[Question] Autogenerated tag on generated files

### ISSUE THREAD

**Issue by CelineVc** [protocolbuffers/protobuf#7880] opened 2020-09-09 07:01 UTC
As I do not have enough permissions to ask a question in the google group, I'll ask it here anyway. 
Is there a way to add an auto generated tag in the cs files that are generated?
I currently have problems with the rule SA1518: File is required to end with a single newline character
I think the StyleCop Analyzers are ignoring files with those autogenerated tags automatically.
Or is there an other way to work around this?
I tried ignoring it, but then the cs files that need this rule are also ignored.
It looks that the generated file is empty too. Maybe that's the issue. 
I created the same question here: https://github.com/grpc/grpc-dotnet/issues/1043
and here: https://groups.google.com/g/grpc-io/c/ZdNwCnZNqRk as I don't know who is actually generating the cs files.
I'm pretty new to grpc and protobuf.

Thanks!

**What version of protobuf and what language are you using?**
Version: 3.13.0
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Micosoft Windows 10 Pro - 10.0.19041 Build 19041

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**
1. Create a project with Stylecop.Analyzers and FxCopAnalyzers, where SA1518 is handled as an error.
2. Add a proto without a service 
3. Rebuild your project

**What did you expect to see**
A cs file with an autogenerated tag on top, even when it's empty.

**What did you see instead?**
A style error, and an empty generated cs file.
![image](https://user-images.githubusercontent.com/52781305/92564557-a582d180-f279-11ea-8688-9451ea3a31bc.png)

**Comment by deannagarcia** [comment] 2020-10-22 20:32
Resolved in another thread: https://groups.google.com/g/grpc-io/c/ZdNwCnZNqRk

**Closed by deannagarcia** 2020-10-22 20:32 UTC

**Comment by mongoDynamo** [comment] 2022-12-13 01:23
Having this same issue when trying to generate CS files using protobuff + grpc. 

Error is : `FileNameGrpc.cs(1,1): error SA1518: File is required to end with a single newline character` 

<img width="456" alt="image" src="https://user-images.githubusercontent.com/38298138/207202949-a2da2ab5-3821-4f85-8736-d64dff564611.png">


I'm trying to just get this to build using the example files from here : https://developers.google.com/protocol-buffers/docs/csharptutorial

This is my proto file in my project : 

`syntax = "proto3";
package tutorial;

import "google/protobuf/timestamp.proto";

message Person {
  string name = 1;
  int32 id = 2;  // Unique ID number for this person.
  string email = 3;

  enum PhoneType {
    MOBILE = 0;
    HOME = 1;
    WORK = 2;
  }

  message PhoneNumber {
    string number = 1;
    PhoneType type = 2;
  }

  repeated PhoneNumber phones = 4;

  google.protobuf.Timestamp last_updated = 5;
}

// Our address book file is just one of these.
message AddressBook {
  repeated Person people = 1;
}`

And this is my CSProj pieces : 

`<ItemGroup>
    <PackageReference Include="Grpc.Tools" />
    <PackageReference Include="Google.Protobuf" />
  </ItemGroup>`

and 

`<ItemGroup>
    <Protobuf Include="FileName.proto" GrpcServices="Client" />
  </ItemGroup>`

**Comment by mongoDynamo** [comment] 2022-12-13 01:25
> Resolved in another thread: https://groups.google.com/g/grpc-io/c/ZdNwCnZNqRk

Could you reopen this question. The resolution in the other thread is that the OP just changed the build to not fail with the error.

**Comment by PingvinB** [comment] 2023-02-23 22:11
I think this is the problem isn't it? 

> Does your .proto file contain any service definitions (as opposed to just protobuf messages)? If not, no *Grpc.cs file should be generated (as there are no services that gRPC could use).

Proto files that only contain protobuf message still generate a *Grpc.cs file. And that generated .cs file is completely empty which causes the StyleCop Analyzer to not skip it.

**Comment by AArnott** [comment] 2023-09-16 18:58
I'm having the exact same problem. SA1518 is complaining about a totally empty file. 4 .cs files are generated and 3 of them are full and have the appropriate `auto-generated` header. But one is totally empty. 
These are generated by two .proto files that I copied into my project from a 3rd party project.

**Comment by AArnott** [comment] 2023-09-16 19:02
I was able to work around it by creating an .editorconfig file in my obj directory with this content:

```
[*.cs]
dotnet_diagnostic.SA1518.severity = none
```

I then had to add it explicitly to my csproj:

```xml
  <ItemGroup>
    <EditorConfigFiles Include="..\..\obj\.editorconfig" Link=".editorconfig" />
  </ItemGroup>
```

That allowed me to suppress SA1518 only from the generated code but keep the rule turned on for my own user code.
