### ISSUE TITLE
[Reopened] Incorrect json serialization of empty StringValue

### ISSUE THREAD

**Issue by serhiikushch** [protocolbuffers/protobuf#6667] opened 2019-09-18 16:31 UTC
**What version of protobuf and what language are you using?**
Version: v3.9.1.
Language: PHP 7.3

**What operating system (Linux, Windows, ...) and version?**
Linux

**What did you do?**
I have a message defined as following:
```
syntax = "proto3";
package generated;

import "google/protobuf/wrappers.proto";

message Foo {
    Bar bar = 1;
}

message Bar {
    google.protobuf.StringValue field = 1;
}
```
**What did you expect to see**
When converting this message to json string like:
```php
$message = new Foo(['bar' => new Bar(['field' => ''])])
echo $message->serializeToJsonString();
```
should return:
```
{"bar":{"field":""}}
```
**What did you see instead?**
```
{"bar":{"field":}}
```
that results in `Syntax error` after applying `json_decode`

**Anything else we should know about your project / environment**
I'm using c extension, however php package does not have this issue.
Detailed example with tests and docker file https://github.com/serhiikushch/protobuf-issue

**Comment by Sixuan** [comment] 2019-09-30 15:37
Anyone can take a look at this issue? We've heard aa bunch of people that are having the same issue and had to switch to a different library. 

Thanks!

**Comment by TeBoring** [comment] 2019-09-30 17:15
```
testSerialize(string $expected, \Google\Protobuf\Internal\Message $message)
```

Does changing ```\Google\Protobuf\Internal\Message``` to the actual type solve the problem?

**Comment by TeBoring** [comment] 2019-09-30 17:44
Seems the problem is because the array constructor with StringValue has some problems.
For now, could you use setter to set value?

**Comment by serhiikushch** [comment] 2019-09-30 18:37
> ```
> testSerialize(string $expected, \Google\Protobuf\Internal\Message $message)
> ```
> 
> 
> Does changing `\Google\Protobuf\Internal\Message` to the actual type solve the problem?

No it's just type checking and changing it does not have any impact on functionality


> Seems the problem is because the array constructor with StringValue has some problems.
> For now, could you use setter to set value?

unfortunately not. we faced this issue on serializing GRPC service response(message structure is similar to my example)

**Comment by TeBoring** [comment] 2019-09-30 20:47
Fixed in https://github.com/protocolbuffers/protobuf/pull/6713

**Closed** 2019-09-30 21:43 UTC
