### ISSUE TITLE
[C#] Memory Leak in ToByteString()

### ISSUE THREAD

**Issue by indy-singh** [protocolbuffers/protobuf#12217] opened 2023-03-13 13:10 UTC
**What version of protobuf and what language are you using?**
```xml
<PackageReference Include="Google.Cloud.BigQuery.Storage.V1" Version="3.6.0" />
<PackageReference Include="Google.Protobuf" Version="3.22.1" />
<PackageReference Include="Google.Protobuf.Tools" Version="3.22.1" />
```
**Language**: C#

**What operating system (Linux, Windows, ...) and version?**
```bat
OS Name:                   Microsoft Windows Server 2019 Standard
OS Version:                10.0.17763 N/A Build 17763
```
**What runtime / compiler are you using (e.g., python version or gcc version)**
```xml
<TargetFramework>net6.0</TargetFramework>
```
**What did you do?**
```protobuf
syntax = "proto3";


message ExampleRecord {
  string name = 1;
  int32 id = 2;
  string email = 3;
}
```
And then
```csharp
var records = new List<ExampleRecord>
{
	new()
	{
		Email = "1@domain.com",
		Id = 1,
		Name = "1"
	},
	new()
	{
		Email = "2@domain.com",
		Id = 2,
		Name = "2"
	},
	new()
	{
		Email = "3@domain.com",
		Id = 3,
		Name = "3"
	}
};

var writerSchema = new ProtoSchema
{
	ProtoDescriptor = ExampleRecord.Descriptor.ToProto()
};

for (int i = 0; i < 1_000_000; i++)
{
	var protoData = new AppendRowsRequest.Types.ProtoData
	{
		WriterSchema = writerSchema,
		Rows = new ProtoRows
		{
			SerializedRows = { records.Select(x => x.ToByteString()) }
		}
	};
}
```

**What did you expect to see**
I know this is a contrived example, but send a lot of data to BigQuery and have just switched Storage Write API (that forces you to use Protobuf) and as far as I can tell, it leaks when they are a lot of invocations to `ToByteString`.

**What did you see instead?**
It leaks when they are a lot of invocations to `ToByteString`.
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

I used [this](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/main/bigquery-storage/api/BigQueryStorage.Samples/AppendRowsPending.cs) as a example to build from.

Cheers,
Indy

**Comment by indy-singh** [comment] 2023-03-13 13:12
![image](https://user-images.githubusercontent.com/1906778/224711732-03cb925d-2729-4e4c-b233-0741c8d0dc60.png)

Is why I think it is `ToByteString()`.

**Comment by indy-singh** [comment] 2023-03-13 13:18
This is the increased memory we are seeing on prod; excuse the old fashioned graph (they work!).

![image](https://user-images.githubusercontent.com/1906778/224713372-16c63aac-dac1-4b96-b8da-e0dede8124e2.png)


Cheers,
Indy

**Comment by jskeet** [comment] 2023-03-13 18:10
I'll try to reproduce this, but I strongly suspect this isn't actually a *leak*, but a matter of just generating a lot of garbage.
It's the end of my working day here in the UK, but I'll try to reproduce this first thing in the morning.

**Comment by indy-singh** [comment] 2023-03-13 18:23
Hi @jskeet,

The choice of wording could definitely be better; it allocates more than we expected; especially when compared to the legacy insertAll method.

Previously, we used the legacy [insertAll method](https://cloud.google.com/bigquery/docs/reference/rest/v2/tabledata/insertAll) and this is 1:1 switch for the Storage Write API using the [default stream](https://cloud.google.com/bigquery/docs/reference/storage/rpc/google.cloud.bigquery.storage.v1#google.cloud.bigquery.storage.v1.BigQueryWrite.AppendRows).

To give more realistic context and numbers; we insert around 30-40 times per minute bucket and with each insert doing 160,000 rows 

![image](https://user-images.githubusercontent.com/1906778/224794289-db273582-f00a-4eca-93bc-2ad876e333de.png)


For now we have had to go back to using the legacy insertAll method; but we are keen to get back to the newer API as soon as we can.

Cheers,
Indy

**Comment by jskeet** [comment] 2023-03-13 18:33
Again, I'm not going to look at this in detail until tomorrow, but:

- What is the size of each record? (If you call `CalculateSize()` on a sample record, what's the result?)
- What's the size of each full request? (If you're adding 160,000 rows to a single `AppendRowsRequest.Types.ProtoData`, I'd expect that to become pretty big...)
- What does your legacy insertAll code look like? (Are you writing huge requests there as well, or writing more frequent but smaller requests?)

**Comment by indy-singh** [comment] 2023-03-13 20:34
Hi @jskeet,

1. From our DEMO environment with a sample size of 2,654. The smallest record size is 85, the largest is 244, with an avg size of 165. The std dev is 35. I do not expect our LIVE environment to massively difference in terms of record shape and size, the number of requests will be the biggest difference. But happy to repeat this step tomorrow.
2.  From our DEMO environment:
```
count_of_rows_in_full_request	size_of_full_request_in_bytes
215	34600
197	32962
220	35767
212	34680
257	43417
197	31340
219	37535
179	28254
189	32000
175	28501
189	31020
139	23961
135	22237
131	22733
```

I do expect the number for our LIVE environment to be dramatically different.

3. This is one for tomorrow.

> If you're adding 160,000 rows to a single AppendRowsRequest.Types.ProtoData, I'd expect that to become pretty big...

Sorry, that is on me. I should be more clearer. Our LIVE environment has 12 servers that are constantly given information to send to BigQuery. The service that sends to BigQuery pumps every 20 seconds on each box, and we don't process more than 10,000 items from the backing queue in one go. So in reality every 20 seconds each box is sending roughly 4000-5000 'rows'. The logic behind this did not change when we migrated from legacy insertAll to Storage Write API.

Cheers,
Indy

**Comment by indy-singh** [comment] 2023-03-13 21:54
Ahhh, it's the addition onto `SerializedRows`! 

https://github.com/indy-singh/bigquery_storage_write_api_high_memory_allocation/commit/5b324f254a10139f41044235de6c89b41004baa3

```
DoLegacyInsertTest
Took: 94 ms
Allocated: 70,428 kb
Peak Working Set: 23,732 kb
Gen 0 collections: 17
Gen 1 collections: 0
Gen 2 collections: 0

DoStorageWriteApiTest1
Took: 63 ms
Allocated: 70,428 kb
Peak Working Set: 23,588 kb
Gen 0 collections: 17
Gen 1 collections: 0
Gen 2 collections: 0

DoStorageWriteApiTest2
Took: 2,984 ms
Allocated: 1,003,172 kb
Peak Working Set: 990,768 kb
Gen 0 collections: 158
Gen 1 collections: 59
Gen 2 collections: 6
```

Cheers,
Indy

**Comment by indy-singh** [comment] 2023-03-14 08:43
As promised.

> 1. From our DEMO environment with a sample size of 2,654. The smallest record size is 85, the largest is 244, with an avg size of 165. The std dev is 35. I do not expect our LIVE environment to massively difference in terms of record shape and size, the number of requests will be the biggest difference. But happy to repeat this step tomorrow.

For our LIVE environment with a sample size of 27,464. The smallest record size is 79, the largest is 255, with an avg size of 160.2683877075444218. The std dev is 23.4661203284678910.
> 2. From our DEMO environment:
> 
> ```
> count_of_rows_in_full_request	size_of_full_request_in_bytes
> 215	34600
> 197	32962
> 220	35767
> 212	34680
> 257	43417
> 197	31340
> 219	37535
> 179	28254
> 189	32000
> 175	28501
> 189	31020
> 139	23961
> 135	22237
> 131	22733
> ```
> 
> I do expect the number for our LIVE environment to be dramatically different.

For our LIVE environment:-

```
count_of_rows_in_full_request	size_of_full_request_in_bytes
2629	419487
2637	424459
2597	416253
2670	428342
2757	442919
2673	430326
2639	421473
2529	402102
2675	427347
2888	465010
2684	433572
2813	451870
2633	419867
2622	422025
2720	433600
2582	412649
2637	423563
```

Cheers,
Indy

**Comment by indy-singh** [comment] 2023-03-14 09:11
Hi @jskeet,

That sounds great. I only put it here because of the initial misdiagnose; happy for it to be moved to where ever it is meant to live.

Cheers,
Indy

**Comment by jskeet** [comment] 2023-03-14 09:23
@indy-singh: Humbug - it turns out I can't transfer it between organizations. Let's leave it here for now - or we could close this one and you could open a new issue in https://github.com/googleapis/google-cloud-dotnet. I suspect the next step will be a repro that's like these benchmarks, but *actually writing* into BigQuery (in a test environment, of course!). At that point, it would definitely be better in google-cloud-dotnet. Let me know how you'd like me to proceed. (And would you like me to create a fork with my benchmark code so far for you to experiment with?)

**Comment by jskeet** [comment] 2023-03-14 09:51
> Ah that is unfortunate. I've no preference where this issue lives, happy to defer to you on this matter. If I was going to open a new issue I'd rather open it with all the leg/grunt work done so we can get into the weeds of the issue.
> Happy to throw together the next step, along with the CREATE TABLE so that we can get a 1:1 test environment.

Fabulous, thanks. In that case I'll close this issue now, and look forward to seeing a new one in the google-cloud-dotnet repo.

See https://github.com/jskeet/bigquery_storage_write_api_high_memory_allocation/tree/separate-benchmarks for my changes.

**Closed by jskeet** 2023-03-14 09:51 UTC
Labels: c#, investigation

**Comment by indy-singh** [comment] 2023-03-14 11:05
Sounds great fella, I'm AFK for the rest of today but it should be done this week 🤞🏽 

Cheers,
Indy

**Comment by indy-singh** [comment] 2023-03-22 09:55
For anyone arriving via Google search et al, this was a flawed analysis please see https://github.com/googleapis/google-cloud-dotnet/issues/10034#issuecomment-1479240140

Cheers,
Indy
