### ISSUE TITLE
Invalid javadoc generation for enum types

### ISSUE THREAD

**Issue by Scottmitch** [protocolbuffers/protobuf#9612] opened 2022-03-10 18:28 UTC
**What version of protobuf and what language are you using?**
Version: [v3.19.4](https://github.com/protocolbuffers/protobuf/releases/tag/v3.19.4)
Language: Java

**What operating system (Linux, Windows, ...) and version?**
macOS 12.2.1

**What runtime / compiler are you using (e.g., python version or gcc version)**
OpenJDK 17.0.2+8-LTS

**What did you do?**
1. `git clone git@github.com:Scottmitch/servicetalk-1.git`
2. `cd servicetalk`
3. `git checkout origin/grpc_javadoc_test`
4. `cd servicetalk-grpc-protoc`
5. `../gradlew clean test`

Proto file that reproduces the issue: https://github.com/apple/servicetalk/blob/main/servicetalk-grpc-protoc/src/test/proto/test_shared.proto

**What did you expect to see**
No javadoc warnings.

**What did you see instead?**
Missing `@param` and duplicate `@return` tag

```
/home/runner/work/servicetalk/servicetalk/servicetalk-grpc-protoc/build/generated/sources/proto/test/java/test/shared/TestShared.java:1505: warning: @return has already been specified
       * @return This builder for chaining.

> Task :servicetalk-grpc-protoc:testJavadoc
error: warnings found and -Werror specified
```

**Area of interest**
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/java/java_enum_field.cc#L862 `LIST_INDEXED_GETTER` -> `LIST_INDEXED_SETTER`

**Comment by elharo** [comment] 2022-03-17 20:41
Reproduced in protoc-explorer. The buggy generated code looks like this:

```
     /**
       * <code>repeated .test.shared.SharedReply.Until until = 1;</code>
       * @param index The index of the value to return.
       * @return The enum numeric value on the wire of until at the given index.
       * @return This builder for chaining.
       */
      public Builder setUntilValue(
          int index, int value) {
        ensureUntilIsMutable();
        until_.set(index, value);
        onChanged();
        return this;
      }
```

**Comment by elharo** [comment] 2022-03-17 20:46
This looks like a minimal reproducible case:

```
syntax = "proto3";

package test.shared;

message Foo {
  enum Bar {
    QUX = 0;
  }
  Bar baz = 2;
}

message Bars {
  repeated Foo.Bar baz = 1;
}
```

**Comment by elharo** [comment] 2022-03-17 20:47
Test case can loop thorugh the output and verify that no two successive lines start with        `* @return`

**Comment by Scottmitch** [comment] 2022-03-17 22:22
Hopefully the "Area of interest" is in the issue description is helpful :)

**Comment by elharo** [comment] 2022-03-18 12:13
Very. Thanks. I'm fixing this in goole3 and it will eventually make its way back out into Github.

**Comment by elharo** [comment] 2022-03-22 12:51
Fixed in google3. It will make its way into Github at the next sync.

**Closed by elharo** 2022-03-22 12:51 UTC
Labels: bug, java, protoc, P3

**Comment by Scottmitch** [comment] 2022-04-16 15:42
@elharo - any idea what release this will be targeted for?
