### ISSUE TITLE
CodedInputStream GC pressure. 

### ISSUE THREAD

**Issue by tactical-drone** [protocolbuffers/protobuf#9894] opened 2022-05-02 11:41 UTC
**What version of protobuf and what language are you using?**
Version: since forever
Language: C#

**What operating system (Linux, Windows, ...) and version?**
All of them

**What runtime / compiler are you using (e.g., python version or gcc version)**
.net 7

**What did you do?**
Ran netcode that does nothing. 

**What did you expect to see**
No GC pressure

**What did you see instead?**
Gc pressure from CodedInputStream  coming from protobuf. 

**Anything else we should know about your project / environment**
It seems that the object would support reuse trivially if you could "reset" the cur index on that stream. Not sure why this is not an issue. (those hacks on the web suggesting resetting the underlying stream does not work)

**Comment by jskeet** [comment] 2022-07-12 19:21
Please provide more details of what code you're running. If it really "does nothing" then CodedInputStream won't be involved - so presumably *something* is reading. A minimal example would be ideal.

**Comment by jskeet** [comment] 2022-07-19 11:04
Closing due to lack of information. @tactical-drone if you add some more information so I can reproduce this, I'll happily reopen it.

**Closed by jskeet** 2022-07-19 11:04 UTC
Labels: help wanted, c#

**Comment by tactical-drone** [comment] 2022-08-05 18:42
Turns out the API was there all along. I just must have [missed](https://github.com/protocolbuffers/protobuf/blob/9f58ee3f04fe5ae013c8014a773a46db54382546/csharp/src/Google.Protobuf/MessageExtensions.cs#L152
) it. 

That extension leads to [this](https://github.com/protocolbuffers/protobuf/blob/79c3d07c63e711255e0d566c9b876706e978686a/csharp/src/Google.Protobuf/ByteString.cs#L58) which I did not see before. 

In any case the problem is solved. gj
